### PR TITLE
fix missing arg in naughty.notification detroyed signal

### PR DESCRIPTION
**Pull request by manilarome**
fixes https://github.com/awesomeWM/awesome/issues/3091. Just tell me if I need to change the argument's description.

### CODE REVIEW

**Comment by psychon** [comment]
I'm not sure about this. All signals on objects have the objects as first argument. For example, the docs for `swapped` on `screen` say there are two argument:
- The other screen
- `is_source`

This just implicitly assumes that the object is emitted on a screen which is also, well, "participating".

**Comment by manilarome** [comment]
Oh, okay. Thanks for the clarification. Maybe I'm just using the `destroyed` signal in wrong way haha. I'll just close this and the issue. Thanks again!

**Comment by Elv13** [comment]
Thanks for this PR.

I think we need a proper plan before merging (or not merging) this. All object signals have an implicit `self` first argument. A minority of the `@signal` doc has it, but the vast majority doesn't.

We have `@classsignal` [here](https://github.com/awesomeWM/awesome/blob/master/docs/config.ld#L352) to specify signals that are only class level and not object+class. It should be assumed that all `@signal` without this attribute have a `self`.

For the object property, we already have the magic to auto-add this everywhere. I guess we need the same magic to fix this #3091. This would go into `config.ld`. That file is very hard to read because `ldoc` doesn't expose the Lua stdlib, so everything re-invent the API wheel in raw code (because `require()` and `dofile()` are not there, it also has to be a giant file... Then there is the weird way the HTML template calls the code in `config.ld` that make that file even harder to understand.

So if we merge this, then we have to go trough the entire API and add all implicit `self`. I think this will be a real nightmare to maintain. The alternative is to modify `config.ld` to auto-add the implicit `self` when `@classsignal` is not present. This means we still have to `grep` the codebase `@signal` to make sure all of them are properly using (or not using) `@classsignal`. Then also make sure the ones with `self` get fixed.

Sorry for turning a simple fix into a large and boring multi hour project. I wont have time to do it in the near term. Patches would be appreciated. But fixing the "there is missing self in the signal doc" is really a project we have to undertake to improve our doc and help ease the learning curve. Implicit concepts are horrible documentation bugs.

**Comment by manilarome** [comment]
I see. Thanks for the detailed explanation! I'll keep that in mind! I really should read and learn more about the API and the source code.

**Comment by psychon** [comment]
Closing to prevent this from getting accidentally merged. I'll reopen #3091 instead.

**Pull request closed without merging**
