### PR TITLE
Allow to add group rules to hotkeys_popup default instance

### PR DESCRIPTION
**Pull request by barjo**
see https://github.com/awesomeWM/awesome/issues/1694

### CODE REVIEW

**Comment by actionless** [comment]
please squash the commits

**Comment by barjo** [comment]
Thanks :+1:

**Comment by blueyed** [comment]
Thanks!

Is this meant to give me the Firefox specific entries when calling it from a Firefox window?

The following in `globalkeys` does not give me those:

```lua
    awful.key({ modkey, 'Shift'           }, "ß",      hotkeys_popup.show_help,
              {description="show help", group="awesome"}),
```

**Comment by barjo** [comment]
you have to require the firefox hotkeys in your `rc.lua`

```rc.lua
local hotkeys_popup = require("awful.hotkeys_popup").widget
-- Enable VIM help for hotkeys widget when client with matching name is opened:
require("awful.hotkeys_popup.keys.vim")
require("awful.hotkeys_popup.keys.firefox")
```

**Pull request merged**
