### PR TITLE
New widget system

### PR DESCRIPTION
**Pull request by psychon**
Here it is, finally. Feel free to merge.

Looking forward to hear what stuff I broke :-)

ToDo (in a separate PR, this one is big enough already (EDIT: Did it here anyway)):

- [x] Add caches for `:fit` again
- [x] Add caches for `:layout` again

Old version was at PR #404

### CODE REVIEW

**Comment by blueyed** [comment]
No errors with my config so far.. moving to "next".

**Comment by psychon** [comment]
I am running into the following and I don't know why, but don't have the time to investigate right now. Will do so (after this is merged, if needed).

```
Error while drawing widget: ...chon/projects/awesome/build/lib/wibox/widget/systray.lua:43: attempt to index local 'context' (a nil value)
stack traceback:
	...chon/projects/awesome/build/lib/wibox/widget/systray.lua:43: in function 'func'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:243: in function <...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:242>
	[C]: in function 'xpcall'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:242: in function 'call'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:261: in function 'draw'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:268: in function 'draw'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:268: in function 'draw'
	...e/psychon/projects/awesome/build/lib/wibox/hierarchy.lua:268: in function 'draw'
	/home/psychon/projects/awesome/build/lib/wibox/drawable.lua:134: in function 'do_redraw'
	/home/psychon/projects/awesome/build/lib/wibox/drawable.lua:316: in function '?'
	/home/psychon/projects/awesome/build/lib/gears/timer.lua:151: in function </home/psychon/projects/awesome/build/lib/gears/timer.lua:150>
	[C]: in function 'xpcall'
	/home/psychon/projects/awesome/build/lib/gears/timer.lua:150: in function </home/psychon/projects/awesome/build/lib/gears/timer.lua:148>
```

**Comment by blueyed** [comment]
I've seen a similar traceback now:

    Error while drawing widget: …/awesome/lib/wibox/widget/systray.lua:43: attempt to index local 'context' (a nil value)
    stack traceback:
            …/awesome/lib/wibox/widget/systray.lua:43: in function 'func'
            …/awesome/lib/wibox/hierarchy.lua:217: in function <…/awesome/lib/wibox/hierarchy.lua:216>
            [C]: in function 'xpcall'
            …/awesome/lib/wibox/hierarchy.lua:216: in function 'call'
            …/awesome/lib/wibox/hierarchy.lua:235: in function 'draw'
            …/awesome/lib/wibox/hierarchy.lua:242: in function 'draw'
            …/awesome/lib/wibox/hierarchy.lua:242: in function 'draw'
            …/awesome/lib/wibox/drawable.lua:131: in function 'do_redraw'
            …/awesome/lib/wibox/drawable.lua:313: in function '?'
            …/awesome/lib/gears/timer.lua:151: in function <…/awesome/lib/gears/timer.lua:150>
            [C]: in function 'xpcall'
            …/awesome/lib/gears/timer.lua:150: in function <…/awesome/lib/gears/timer.lua:148>

The line numbers differ, but that might be because you have local changes?!

**Comment by psychon** [comment]
It's a simple copy&paste error that I introduced in a rebase. `hierarchy:draw(context, cr)` calls functions with argument `arg` (undefined variable, always `nil`) when it was really meant to be `context`. Sorry. Will push a fix when I can. (This only breaks the systray since nothing else uses the `context` argument and thanks to `xpcall` this doesn't have any more bad consequences)

**Comment by blueyed** [comment]
> Sorry. Will push a fix when I can.

Great.  Assigning this PR to you then: feel free to merge in case this is added.

Any update on the profiling front?
I think that even if this was slower (which is probably is not), it provides more room for improvement then the current approach?

**Comment by psychon** [comment]
A quick benchmark:
```lua
local gettime = require("socket").gettime
local function measure(f, iter)
    local start = gettime()
    for i = 1, iter do
        f()
    end
    local now = gettime()
    return (now - start) / iter, now - start
end
local function benchmark(f, ...)
    local iters = nil
    local time, time_total = 0, 0
    while time_total < 1 do
        iters = iters and iters * 2 or 1
        time, time_total = measure(f, iters)
    end
    print(..., tostring(time) .. " per iteration", "(" .. tostring(iters) .. " iterations and " .. tostring(time_total) .. " time for that)")
end

local function create_wibox()
    local w = awful.wibox({ position = "top", screen = 1 })

    -- Widgets that are aligned to the left
    local left_layout = wibox.layout.fixed.horizontal()
    left_layout:add(mylauncher)
    left_layout:add(mytaglist[1])
    left_layout:add(mypromptbox[1])

    -- Widgets that are aligned to the right
    local right_layout = wibox.layout.fixed.horizontal()

    right_layout:add(mytextclock)
    right_layout:add(mylayoutbox[1])

    -- Now bring it all together (with the tasklist in the middle)
    local layout = wibox.layout.align.horizontal()
    layout:set_left(left_layout)
    layout:set_middle(mytasklist[s])
    layout:set_right(right_layout)

    w:set_widget(layout)

    awesome.emit_signal("refresh")
    awesome.emit_signal("refresh")
end

local wb = create_wibox()

local function relayout_textclock()
    mytextclock:emit_signal("widget::layout_changed")
    awesome.emit_signal("refresh")
    awesome.emit_signal("refresh")
end

local function redraw_textclock()
    mytextclock:emit_signal("widget::redraw_needed")
    awesome.emit_signal("refresh")
    awesome.emit_signal("refresh")
end

local function update_textclock()
    mytextclock:emit_signal("widget::updated")
    awesome.emit_signal("refresh")
    awesome.emit_signal("refresh")
end

benchmark(create_wibox, "create wibox")
benchmark(update_textclock, "update textclock")
benchmark(relayout_textclock, "relayout textclock")
benchmark(redraw_textclock, "redraw textclock")
```
With git master:
```

**Pull request merged**
