### PR TITLE
Use focus.filter in awful.client.focus.(global_)bydirection

### PR DESCRIPTION
**Pull request by mphe**
`awful.client.focus.bydirection` and `global_bydirection` don't check for clients actually being focusable. This is fixed with this commit by filtering clients using `focus.filter`.

### CODE REVIEW

**Review by actionless — APPROVED** [review]
LGTM, however adding testcase to cover this would be also nice

**Review by psychon — APPROVED** [review]

**Comment by mphe** [comment]
@actionless is there any existing test case that can be adapted quickly? I don't really know how to properly write test cases for awesome.

**Comment by actionless** [comment]
these 2 tests are a bit related: https://github.com/awesomeWM/awesome/blob/master/tests/test-awful-client.lua#L145-L177

**Comment by Aire-One** [comment]
@mphe any update on the tests?

**Comment by mphe** [comment]
I completely forgot this PR.
Last time I worked on this, I couldn't get the integration tests to run, and then never returned to fix it.
I just checked again and it still won't run. It opens a xephyr window and then just hangs for a while until a timeout occurs. There seems to be a problem with the dbus connection. Here's the log: [log.txt](https://github.com/awesomeWM/awesome/files/7833317/log.txt).

**Comment by sclu1034** [comment]
The lines about DBus are most likely just fallout from the error before that:

```
(EE)
Fatal server error:
(EE) Server is already active for display 5
	If this server is no longer running, remove /tmp/.X5-lock
	and start again.
```

But it's hard to tell why that would happen.
I guess you could try to run just the integration tests (`make check-integration`) in case that lock file is from the previous test step.

**Comment by mphe** [comment]
That works, but I still get a bunch of timeout errors.
I'll try to add the tests in the near future.

```
There were 19 errors:
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-awful-client.lua: Error: timeout waiting for signal in step 11/138 (@20) (...345-fc75197c9584/git/awesome/tests/test-awful-client.lua:221).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-awful-placement.lua: Error: timeout waiting for signal in step 1/50 (@20) (...-fc75197c9584/git/awesome/tests/test-awful-placement.lua:54).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-awful-rules.lua: Error: timeout waiting for signal in step 1/15 (@20) (...9345-fc75197c9584/git/awesome/tests/test-awful-rules.lua:337).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-client-borders.lua: Error: timeout waiting for signal in step 1/25 (@20) (...5-fc75197c9584/git/awesome/tests/test-client-borders.lua:139).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-client-shape.lua: Error: running function for step 1/4 (@1): ...345-fc75197c9584/git/awesome/tests/test-client-shape.lua:11: Failed to execute child process “xeyes” (No such file or directory)
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-client-signals.lua: Error: timeout waiting for signal in step 1/14 (@20) (...5-fc75197c9584/git/awesome/tests/test-client-signals.lua:8).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-client-swap.lua: Error: timeout waiting for signal in step 1/3 (@20) (...9345-fc75197c9584/git/awesome/tests/test-client-swap.lua:8).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-current-desktop.lua: Error: timeout waiting for signal in step 1/13 (@20) (...-fc75197c9584/git/awesome/tests/test-current-desktop.lua:34).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-input-binding.lua: Error: timeout waiting for signal in step 5/26 (@20) (...45-fc75197c9584/git/awesome/tests/test-input-binding.lua:100).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-maximize.lua: Error: running function for step 1/111 (@1): /usr/share/lua/5.3/lgi/override/Gdk.lua:23: bad argument #1 to 'registerlock' (userdata expected, got nil)
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-resize.lua: Error: timeout waiting for signal in step 1/45 (@20) (...4ff6-9345-fc75197c9584/git/awesome/tests/test-resize.lua:9).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-screen-changes.lua: Error: timeout waiting for signal in step 1/5 (@20) (...5-fc75197c9584/git/awesome/tests/test-screen-changes.lua:19).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-selection-getter.lua: Error: timeout waiting for signal in step 4/9 (@20) (...fc75197c9584/git/awesome/tests/test-selection-getter.lua:102).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-selection-transfer.lua: Error: timeout waiting for signal in step 2/7 (@100) (...75197c9584/git/awesome/tests/test-selection-transfer.lua:102).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-selection-watcher.lua: Error: timeout waiting for signal in step 3/5 (@20) (...c75197c9584/git/awesome/tests/test-selection-watcher.lua:106).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-spawn.lua: Error: timeout waiting for signal in step 3/22 (@20) (...-4ff6-9345-fc75197c9584/git/awesome/tests/test-spawn.lua:165).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-spawn-snid.lua: Error: timeout waiting for signal in step 1/4 (@20) (...-9345-fc75197c9584/git/awesome/tests/test-spawn-snid.lua:23).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-struts.lua: Error: timeout waiting for signal in step 19/24 (@20) (...4ff6-9345-fc75197c9584/git/awesome/tests/test-struts.lua:436).
 - /mnt/77089dd0-7483-4ff6-9345-fc75197c9584/git/awesome/tests/test-titlebar.lua: Error: timeout waiting for signal in step 2/19 (@20) (...f6-9345-fc75197c9584/git/awesome/tests/test-titlebar.lua:69).
```

**Comment by mphe** [comment]
Added a test case.

**Comment by mphe** [comment]
Fixed.

**Review by Aire-One — APPROVED** [review]

**Comment by Aire-One** [comment]
Everything is green. I'll give a chance to Mergify for automatic merge

**Comment by actionless** [comment]
is mergify disabled mb or smth?

**Comment by psychon** [comment]
https://github.com/awesomeWM/awesome/pull/3225/checks says for Mergify that the following checks are missing:

- `Build & Test`
- `Update API docs`

Does this work in other PRs? From a quick look at this PR, there are checks with name e.g. `Build & Test / lua 5.2` and `Update API docs / main`. However, I am not entirely what exactly the name of a check is. There might be some kind of hierarchy with GitHub shows via `/`.

**Comment by mphe** [comment]
Any update on this?

**Pull request merged**
