### PR TITLE
Remember mouse position per screen

### LINKED ISSUE #478: Remember mouse position per screen
The (relative) screen position of the mouse on a screen should be remembered and restored when moving the focus to another screen.

Could be done for the following functions first / only / in the beginning:

    awful.key({ modkey, "Control" }, "j", function () awful.screen.focus_relative( 1) end),
    awful.key({ modkey, "Control" }, "k", function () awful.screen.focus_relative(-1) end),

### PR DESCRIPTION
**Pull request by Bew78LesellB**
The mouse position is saved and restored when focusing another screen

If the target screen has no saved mouse position, the relative position
of the current screen is used

This should close #478

### CODE REVIEW

**Comment by Elv13** [comment]
This is a good addition to awful, the patch look sane to me. One other thing you usually want when doing this is moving the mouse when a client is moved from screen to screen so the mouse remain on the client (if it is focussed)

I guess you might also want to try my implementation of this, it does a few more things like drawing a red circle around the mouse cursor when it is automatically moved. This is overkill for the default implementation like yours, but I like it
https://github.com/elv13/collision

**Comment by Bew78LesellB** [comment]
here you are, it should be fine now

**Comment by psychon** [comment]
Don't you also have to modify all the uses of this table so that they have a `screen.` prefix?

**Comment by Bew78LesellB** [comment]
aargh, how did I forgot that...

if I do the modifications, then a commit --amend, then a force push, will it break something ?

**Comment by psychon** [comment]
Nah, feel free

**Comment by Bew78LesellB** [comment]
okay, done !

**Comment by blueyed** [comment]
Thanks!

Some nitpicking: I would have liked for this to be a single commit in master.

**Pull request merged**
