### PR TITLE
Elv13 prompt hook v2

### PR DESCRIPTION
**Pull request by blueyed**
Continuation of #52, assumes #34 to be merged.

/cc @Elv13

### CODE REVIEW

**Comment by psychon** [comment]
Fine by me

**Comment by Elv13** [comment]
+1

So, I guess you want to rebase this one first?

**Comment by blueyed** [comment]
Rebased.  Let's see if it still passes.. ;)

**Comment by blueyed** [comment]
@Elv13 mentioned that this would be (would have a potential for) a nice addition to the default config, but that could be done in a new PR.

**Comment by blueyed** [comment]
Rebased and seems to be fine - but https://github.com/awesomeWM/awesome/pull/489 should go in first.

**Comment by Elv13** [comment]
While I think about it, another PR should also add an API to add new default hooks for the prompt. This could be used to implement VI style prompt shortcuts by adding escape. For this, layered keygrabbers would also need to be properly supported, but this is just an example (EMACS mode could be implemented (well, extended given `CTRL+A/E` and some others are already implemented) directly). 

/me also wonder is generic hooks for modified text could be added to implement syntax highlight, but this is just dreaming and would required substantial changes to decouple the prompt text and the displayed one

**Comment by Bew78LesellB** [comment]
@Elv13 I'm currently doing a big library, which will have (with a lot of other features) layered grabbers and dynamic keymap, for every possible use, from tag management to prompt editText with vim style keybinds.. This is in WIP, and doesn't work ATM, but it will ;) 

Maybe when finished (in a long time..) I will make a separate library with only key* stuff. For those who doesn't want the full lib.

**Comment by Elv13** [comment]
@Bew78LesellB Well, I guess the issues with layered grabbers should be treated as bugs in Awesome and fixed internally rather than adding an abstraction layer on top the the current API (the internal one should handle it)

**Comment by Bew78LesellB** [comment]
@Elv13 yeah this is another way to think the issue, but I still didn't progress in the study of Awesome's C code, so I'm currently making what I'm good at.. (love lua now!) 
If you can fix this internally, this will surely speed-up things!

**Comment by blueyed** [comment]
@Bew78LesellB 
I am not sure that you will need too much from the C side in awesome.

I think it would be a great opportunity for you to address this where it's meant to be fixed.  Whenever you work around something, just consider fixing it in the core.. :)

**Comment by Bew78LesellB** [comment]
@blueyed Oh I never thought of that !

The thing is that I added some concept in my lib, on top of the lua api (well, in fact, on top of the capi, I'm rewriting a lua api..), and I think everything with theses concepts.. 

As they are kind of specific to me, I'm not sure it's a good idea to add them in the core of awesome..

**Comment by blueyed** [comment]
Rebased on master (fixing a conflict), added some doc, moving to "next" milestone.

**Comment by blueyed** [comment]
I've also made the hook's return value handling a bit smarter in https://github.com/blueyed/awesome/commit/7925e6a6f5d3e42191dbcaea1958808761b604dc.  Does that make sense?

**Comment by blueyed** [comment]
@psychon @Elv13 ping

**Comment by psychon** [comment]
Uhm. Your latest commit looks fine to me (thanks!) and the rest was already decided to be good before, right? So I guess everything is good (sorry, I don't really want to look too deeply into the prompt code.)

**Comment by blueyed** [comment]
https://github.com/blueyed/awesome/commit/7925e6a6f5d3e42191dbcaea1958808761b604dc is also new.

**Comment by psychon** [comment]
I trust you on that one. :-)

**Comment by Elv13** [comment]
+1

**Pull request merged**
