### PR TITLE
Add configuration for https://mergify.io

### PR DESCRIPTION
**Pull request by psychon**
Fixes: https://github.com/awesomeWM/awesome/issues/2260
Signed-off-by: Uli Schlachter <psychon@znc.in>

### CODE REVIEW

**Comment by psychon** [comment]
Seems like Codacy recently-ish renamed the status that it reports and I copied the name from some too old PR, will do a force push to update to `Codacy/PR Quality Review`.

**Comment by blueyed** [comment]
@jd 

From the statuses:

> mergify/pr — .mergify.yml is missing

Would it make sense to consider / use the one from this (or rather the PR itself in general) already?

**Comment by blueyed** [comment]
> Would it make sense to consider / use the one from this (or rather the PR itself in general) already?

Scratch that - thought it would be bad myself, and then read up on the issue.

**Comment by jd** [comment]
I've opened https://github.com/Mergifyio/mergify-engine/issues/31 as per @Elv13 request.
If there's any other feature you'd like to see feel free to open issues.
(Not sure at this stage if there's anything left to prevent merging this?)

**Comment by jd** [comment]
@psychon Your understand is correct.

**Comment by jd** [comment]
@Elv13 you're good with that now?

**Comment by Elv13** [comment]
@jd Have all issues raised in the other thread are addressed or at least have concrete and scheduled plan to fix them? Some of them are more theoretical and not an immediate threat. However the one like having your own code to detect if a PR is mergeable instead of trusting GitHub wont let you merge it otherwise it one I consider more serious given its a behavior known to change from time to time. I don't have time to do another review, so I will trust you do making a summary of the progress.

**Comment by jd** [comment]
@Elv13 Yeah, they have been addressed or bugs have been opened but I think we've done most of them by now.

GitHub data are only used to know what's the state of the branches and the what the status check (CI) reports, and that's what actually is reported by the UI you see. The way you talk about that makes me think that you imagined Mergify would continuously try to merge until GitHub lets him succeed? If that's what you understood, that's not definitely never has been the case. :)

**Comment by jd** [comment]
Let's do this. Ping me if you need any help.

**Comment by blueyed** [comment]
:fireworks: :)

**Pull request merged**
