### PR TITLE
fix(awful: placement: no_overlap): use new placement infrastructure

### LINKED ISSUE #2030: awful.placement.centered + awful.placement.no_overlap
Output of `awesome --version`:

```
awesome v4.2-173-ga7d24d10-dirty (Human after all)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**
1)
```lua
  awful.rules.rules = {
      { rule = { },
        properties = {
          focus = awful.client.focus.filter,
          raise = true,
          keys = awesome_context.clientkeys,
          buttons = awesome_context.clientbuttons,
          placement =
            awful.placement.no_offscreen +
            awful.placement.centered +
            awful.placement.no_overlap,
          size_hints_honor = false,
          screen = awful.screen.preferred,
        },
        callback = function(c)
            awful.client.setslave(c)
        end
      },
}
```

2) choose floating layout

3) open few clients

**Actual result:**

``` lua
            awful.placement.centered +
            awful.placement.no_overlap,
```
and
``` lua
            awful.placement.no_overlap +
            awful.placement.centered,

```
are producing different results and only the last of placements got applied correctly, so either clients are centered but overlapping each other , either they not overlapping but starting to open from top left corner of the screen

**Expected result:**

first client opens in the center, each other opens next to it without overlapping previous ones

### PR DESCRIPTION
**Pull request by actionless**
Fixes #2030

### CODE REVIEW

**Comment by blueyed** [comment]
> actionless deleted a comment from codecov bot an hour ago

Is this mb related to the original comment now being off?!

**Comment by actionless** [comment]
@blueyed no, i've removed one commit from the history

**Comment by blueyed** [comment]
weird then - the comment does not reflect the status in the "main" area.

**Comment by actionless** [comment]
btw anyway you can see the current status on their website

**Comment by blueyed** [comment]
Does this also help with https://github.com/awesomeWM/awesome/issues/1092?

**Comment by blueyed** [comment]
Sry-  the old close-reopen trick.

**Comment by actionless** [comment]
yup, i've got it

re #1092 -- the second commit which i removed was targeting to fix it, but i didn't figured out what was wrong with it, so i'll mb submit it as a separate PR later on

**Comment by actionless** [comment]
it seems what removing commit from history made coveralls crazy -- should i rebase the commit so it'll hash a new hash?

**Comment by actionless** [comment]
@blueyed now they all finally happy

**Comment by actionless** [comment]
@psychon you were participating in #2030 conversation too :-)

**Comment by blueyed** [comment]
Awesome!
Waiting for @Elv13 a bit, but otherwise we should merge it soonish.
Thanks!

**Comment by Elv13** [comment]
Sorry for the delay. I was stuck in airports for most of the past 3 days. Thanks for the commit. Lets ignore the subtle API change and merge this.

Also, what was the other commit? #1092 was never hard to fix, but it would have broken the API and this is the kind of commit that usually cause a storm of unexpected side effects (like those maximization commits). So I silently ignored it all this time.

**Comment by actionless** [comment]
>Also, what was the other commit?

>unexpected side effects

:-)

**Pull request merged**
