### PR TITLE
CMake: Check if we need libm for round()

### PR DESCRIPTION
**Pull request by psychon**
Fixes: https://github.com/awesomeWM/awesome/issues/969
Signed-off-by: Uli Schlachter <psychon@znc.in>

P.S.: Who said that CMake is easier than autotools? Can we switch to meson instead? :-(

### CODE REVIEW

**Comment by blueyed** [comment]
> Who said that CMake is easier than autotools?

Yeah, it often looks similar, if the magic fails.

> Can we switch to meson instead?

Your call.. :)

**Comment by Elv13** [comment]
I still prefer CMake to othre obscure alternative (and I hate autotools). While I agree that when the magic fails, your on your own, I still argue that CMake is the most popular system right now and have plenty of third party modules and support.

**Comment by blueyed** [comment]
@psychon 
You were right: it conflicts..  please feel free to cherry-pick into master directly.

**Comment by psychon** [comment]
Done (and once again in a way so that GitHub doesn't notice -- sorry!)

**Comment by blueyed** [comment]
You would have to add "Closes: …" to it.

**Comment by blueyed** [comment]
Thanks! :)

**Comment by psychon** [comment]
...or I would have to push to the branch of the PR before pushing to master.

**Pull request closed without merging**
