### PR TITLE
stop keygrabber on hide through click

### LINKED ISSUE #2434: Hotkey popup blocks input once after hiding through click
Output of `awesome --version`:

    awesome v4.2 (Human after all)
     • Compiled against Lua 5.3.4 (running with Lua 5.3)
     • D-Bus support: ✔
     • execinfo support: ✔
     • xcb-randr version: 1.5
     • LGI version: 0.9.2

**How to reproduce the issue:**

Load any awesome configuration using the default hotkeys popup, show it with the assigned keybinding and click on the popup to hide it.

**Actual result:**

Input fields, editors etc. do not immediately receive focus, only upon the first keypress after hiding the popup. This keypresses is not propagated through to the client.

**Expected result:**

Hiding the popup through clicking should show the same behaviour as hiding it by a keypress does.

### PR DESCRIPTION
**Pull request by PeterNerlich**
fixes #2434

### CODE REVIEW

**Comment by psychon** [comment]
Why `awful.keygrabber:stop()` instead of `awful.keygrabber.stop()? I.e., why `:` instead of `.`?

**Comment by PeterNerlich** [comment]
> Why `awful.keygrabber:stop()` instead of `awful.keygrabber.stop()`? I.e., why `:` instead of `.`?

I admit, I'm new to awesome and currently trying to tinker my own thing together by looking closely at how the hotkeys popup does it, so I have no idea how things are done "usually". But I went by [the API](https://awesomewm.org/apidoc/classes/awful.keygrabber.html), where `awful.keygrabber:stop ()` is listed as a method, while `awful.keygrabber.stop` is listed as a deprecated function.

**Comment by psychon** [comment]
I went with what the other piece of code in this file did. ;-)

Now that you mention it... I guess that this might not even work. The "other" code in keygrabber did not provide an argument, so it just stopped the keygrabber that was started last.

But `awful.keygrabber:stop()` is equivalent to `awful.keygrabber.stop(awful.keygrabber)`. Since `awful.keygrabber` is not a keygrabber instance... uhm, does this work? (No time to test right now, sorry)

**Comment by actionless** [comment]
what about deduplicating those lines like that?

```diff
diff --git a/lib/awful/hotkeys_popup/widget.lua b/lib/awful/hotkeys_popup/widget.lua
index f8ab93d77..e52621395 100644
--- a/lib/awful/hotkeys_popup/widget.lua
+++ b/lib/awful/hotkeys_popup/widget.lua
@@ -449,8 +449,8 @@ function widget.new(args)
         })
         mywibox:set_widget(pages[1])
         mywibox:buttons(gtable.join(
-                awful.button({ }, 1, function () mywibox.visible=false end),
-                awful.button({ }, 3, function () mywibox.visible=false end)
+                awful.button({ }, 1, function () widget_obj:hide() end),
+                awful.button({ }, 3, function () widget_obj:hide() end)
         ))
 
         local widget_obj = {}
@@ -471,6 +471,7 @@ function widget.new(args)
         end
         function widget_obj.hide(_self)
             _self.wibox.visible = false
+            awful.keygrabber.stop()
         end
 
         return widget_obj
@@ -526,7 +527,6 @@ function widget.new(args)
                 elseif key == "Prior" then
                     help_wibox:page_prev()
                 else
-                    awful.keygrabber.stop()
                     help_wibox:hide()
                 end
             end
```

**Comment by actionless** [comment]
and to address keygrabber instance thing (not tested):

```diff
diff --git a/lib/awful/hotkeys_popup/widget.lua b/lib/awful/hotkeys_popup/widget.lua
index f8ab93d77..13868908f 100644
--- a/lib/awful/hotkeys_popup/widget.lua
+++ b/lib/awful/hotkeys_popup/widget.lua
@@ -441,6 +441,10 @@ function widget.new(args)
             border_color = self.border_color,
             shape = self.shape,
         })
+        local widget_obj = {
+            current_page = 1,
+            wibox = mywibox,
+        }
         mywibox:geometry({
             x = wa.x + math.floor((wa.width - width - self.border_width*2) / 2),
             y = wa.y + math.floor((wa.height - height - self.border_width*2) / 2),
@@ -449,13 +453,10 @@ function widget.new(args)
         })
         mywibox:set_widget(pages[1])
         mywibox:buttons(gtable.join(
-                awful.button({ }, 1, function () mywibox.visible=false end),
-                awful.button({ }, 3, function () mywibox.visible=false end)
+                awful.button({ }, 1, function () widget_obj:hide() end),
+                awful.button({ }, 3, function () widget_obj:hide() end)
         ))
 
-        local widget_obj = {}
-        widget_obj.current_page = 1
-        widget_obj.wibox = mywibox
         function widget_obj.page_next(_self)
             if _self.current_page == #pages then return end
             _self.current_page = _self.current_page + 1
@@ -471,6 +472,9 @@ function widget.new(args)
         end
         function widget_obj.hide(_self)
             _self.wibox.visible = false
+            if _self.keygrabber then
+                awful.keygrabber.stop(_self.keygrabber)
+            end
         end
 
         return widget_obj
@@ -518,7 +522,7 @@ function widget.new(args)
         local help_wibox = self._cached_wiboxes[s][joined_groups]
         help_wibox:show()
 
-        return awful.keygrabber.run(function(_, key, event)
+        help_wibox.keygrabber = awful.keygrabber.run(function(_, key, event)
             if event == "release" then return end
             if key then
                 if key == "Next" then
@@ -526,11 +530,11 @@ function widget.new(args)
                 elseif key == "Prior" then
                     help_wibox:page_prev()
                 else
-                    awful.keygrabber.stop()
                     help_wibox:hide()
                 end
             end
         end)
+        return help_wibox.keygrabber
     end
 
     --- Add hotkey descriptions for third-party applications.
```

**Comment by Elv13** [comment]
ldoc isn't very predictable when it comes to `:` vs. `.` in `@classmod`. There is *many* issues like that in the doc. I had an idea a while ago to monkey-patch ldoc (since it's dead upstream) and replace that function, but so far I have been lazy on that issue (and I barely have enough time to slowly catch up on the reviews of the 12.5k patchset I have in my merge cue **and** I went on creating that new `awful.spawn` series because I spent too much effort on a stackoverflow post).

**Comment by actionless** [comment]
@PeterNerlich ping

**Comment by Elv13** [comment]
@actionless I updated the PR manually. If you want to integrate your changes, please do so. Otherwise I guess we be squash this version?

**Comment by actionless** [comment]
@Elv13 done

**Comment by PeterNerlich** [comment]
Sorry for my absence/silence. I have no objections or further opinions about this. I'll just observe your code decisions and try to learn...

**Pull request merged**
