### PR TITLE
menubar.utils: Allow to add programs with OnlyShowIn option being set

### PR DESCRIPTION
**Pull request by Perlovka**
Bug: https://github.com/awesomeWM/awesome/issues/2377

Signed-off-by: Michael Perlov <perlovka@gmail.com>

### CODE REVIEW

**Comment by psychon** [comment]
Why do you think that Lua string match is the right matching operation here?
The specification only says:

> A list of strings identifying the desktop environments that should display/not display a given desktop entry.
> 
> By default, a desktop file should be shown, unless an OnlyShowIn key is present, in which case, the default is for the file not to be shown.
> 
> If $XDG_CURRENT_DESKTOP is set then it contains a colon-separated list of strings. In order, each string is considered. If a matching entry is found in OnlyShowIn then the desktop file is shown. If an entry is found in NotShowIn then the desktop file is not shown. If none of the strings match then the default action is taken (as above).
> 
> $XDG_CURRENT_DESKTOP should have been set by the login manager, according to the value of the DesktopNames found in the session file. The entry in the session file has multiple values separated in the usual way: with a semicolon.
> 
> The same desktop name may not appear in both OnlyShowIn and NotShowIn of a group.

https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

I agree that "if a matching entry is found" is ambiguous, but I doubt that this means "Lua's regex match".
(Note that we completely ignore this `$XDG_CURRENT_DESKTOP` dance, but whatever)

At best, I would allow to interpret the spec to say "both `$XDG_CURRENT_DESKTOP` and the value in the desktop file are a list of strings; a match is found if they have some common entry".

**Comment by Perlovka** [comment]
The point is to allow user to override .desktop file setting. Let's say, I have installed XFCE and KDE and I want see their applications in awesome menu. Lua will return true on string.match("XFCE", ""), allowing to override .desktop file restriction. I just adopted current code to previous version, where match was used.

**Comment by Perlovka** [comment]
Well, there is one more solution: check utils.wm_name for non-empty value before processing, since program.show is by default set to true:
```lua
    if utils.wm_name ~= "" then
        if program.OnlyShowIn then
            program.show = false -- Assume false until found
            for _, wm in ipairs(program.OnlyShowIn) do
                if wm == (utils.wm_name) then
                    program.show = true
                    break
                end
            end
        else
            program.show = true
        end
    end
```

**Comment by Perlovka** [comment]
Added fix to check if wm_name is empty.

**Comment by Elv13** [comment]
@actionless we could add `menubar.utils.ignore_onlyshowin` later and merge this?

**Comment by blueyed** [comment]
@jd 
> mergify/pr Pending — Change requests need to be dismissed

with:

> actionless approved these changes See review ￼ Dismiss review
> Elv13 approved these changes See review ￼ Dismiss review
> blueyed was requested for review

**Comment by jd** [comment]
@blueyed sorry I might be late to the party, now all I see is that `codecov/patch` is missing :)

**Comment by blueyed** [comment]
@jd 
It still says:
> mergify/pr Pending — Change requests need to be dismissed

**Comment by jd** [comment]
@blueyed This PR is old, I suspect this is a leftover. What's wrong is listed here:
https://github.com/awesomeWM/awesome/pull/2379/checks?check_run_id=43834990

codecov is missing.

**Pull request merged**
