### PR TITLE
Handle missing trailing slash in $XDG_DATA_HOME

### PR DESCRIPTION
**Pull request by majutsushi**

### CODE REVIEW

**Comment by blueyed** [comment]
Without it there will be two slashes then though.

**Comment by Elv13** [comment]
Most parsers (as is almost all) handle that internally.

**Comment by majutsushi** [comment]
In fact, this is even specified by POSIX:

http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap03.html#tag_03_266

**Comment by blueyed** [comment]
Well, but why add it on purpose?
I mean in https://github.com/awesomeWM/awesome/pull/1631/files#diff-123b9113b71ac42b91d0bad8c68ddf81L23.

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
