### PR TITLE
Don't use sleep to implement timeouts in the test runner

### LINKED ISSUE #1075: Test runner keeps stdin, stdout and stderr open after exit
Running the test normally:
```
$ time ./tests/run.sh test-benchmark.lua
[...]
./tests/run.sh test-benchmark.lua  0,18s user 0,06s system 17% cpu 1,373 total
```
Running the test "unnormally":
```
$ time sh -c './tests/run.sh test-benchmark.lua | cat' 
[...]
sh -c './tests/run.sh test-benchmark.lua | cat'  0,19s user 0,06s system 0% cpu 2:00,29 total
```
This happens because the test runner doesn't clean up behind it all that well. There is still a `sleep 120` running that keeps stdout open and so `cat` doesn't exit.

While this is a very, very low priority issue, I still think that this is not good.

### PR DESCRIPTION
**Pull request by psychon**
Fixes #1075.

### CODE REVIEW

**Comment by blueyed** [comment]
The test failure in https://travis-ci.org/awesomeWM/awesome/jobs/162428537 is:
```
+tail -n 100000 -f --pid 19991 /tmp/tmp.FIqtr6S48m/_awesome_test.log
2016-09-24 14:05:54 W: awesome: a_glib_poll:373: Last main loop iteration took 1.253062 seconds! Increasing limit for this warning to that value.
2016-09-24 14:06:21 W: awesome: a_glib_poll:373: Last main loop iteration took 3.057327 seconds! Increasing limit for this warning to that value.
2016-09-24 14:06:25 W: awesome: a_glib_poll:373: Last main loop iteration took 3.088155 seconds! Increasing limit for this warning to that value.
2016-09-24 14:06:45 W: awesome: a_glib_poll:373: Last main loop iteration took 3.348293 seconds! Increasing limit for this warning to that value.
2016-09-24 14:06:54 W: awesome: a_glib_poll:373: Last main loop iteration took 5.422233 seconds! Increasing limit for this warning to that value.
2016-09-24 14:07:15 W: awesome: a_glib_poll:373: Last main loop iteration took 7.604736 seconds! Increasing limit for this warning to that value.
2016-09-24 14:07:53 W: awesome: a_glib_poll:373: Last main loop iteration took 9.493200 seconds! Increasing limit for this warning to that value.
+set +e
+wait 19991
+code=124
+set -e
+[ 124 != 0 ]
+echo Awesome exited with status code 124
Awesome exited with status code 124
+grep -q -E ^Test finished successfully$ /tmp/tmp.FIqtr6S48m/_awesome_test.log
+echo ===> ERROR running /home/travis/build/awesomeWM/awesome/tests/test-awful-client.lua! <===
===> ERROR running /home/travis/build/awesomeWM/awesome/tests/test-awful-client.lua! <===
+grep --color -o --binary-files=text -E .*[Ee]rror.*|.*assertion failed.* /tmp/tmp.FIqtr6S48m/_awesome_test.log
+true
+expr 0 + 1
+errors=1
```

Apparently there was a timeout (124).
This should be logged as such I presume.

I will restart the build, maybe it will pass then, but I think there should be a clearer message in that case.

**Comment by Elv13** [comment]
Yes, I saw this 2 time out of 5 builds of my yesterday PRs. It is due to slow nodes. The build that finishes under 3 minutes never have this, but the ones that take ~12+ do. I hope @psychon test-client daemon and other optimizations will improve this. It was know when the multi-screen test PR were merged and have a FIXME in the code when it was bumped to 120 seconds. There was a little chat on IRC about this too. It was decided to go ahead as the issues that PR fixes were important and the build problems were not directly related to commits themselves. It simply put too much stress on the build system. It didn't hinder local commit bisecting, it only timeout because it is slow, not broken.

**Comment by blueyed** [comment]
@Elv13 
I see, thanks for the explanation!

@psychon 
Can you improve this PR please to have a clear message in case of `code == 124`,  please?

**Comment by psychon** [comment]
Done

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
