### PR TITLE
build-utils/dist.sh: fix shellcheck warnings and add usage

### PR DESCRIPTION
**Pull request by blueyed**
[ci skip]

### CODE REVIEW

**Comment by psychon** [comment]
Could you try re-building an old release tarball and check that you get (pretty much) the same result? If so: :+1:

**Comment by blueyed** [comment]
@psychon 
I see your valid concern, but raise an "it would be better if a 3rd party would do just that" - to keep errors from my side out of the equation.. ;)

**Comment by psychon** [comment]
Well, okay. However, then you'll have to ping me here in a month since I won't get to do it before then (needs a computer with a pgp key, thus I can only do it at home and I'll be travelling for the next weeks).

**Comment by blueyed** [comment]
Looked into it a bit more, and now it will produce the same md5 sum for the archives.

**Pull request merged**
