### PR TITLE
Shape rotations

### PR DESCRIPTION
**Pull request by psychon**
This adds helper functions to `gears.shape` that simplify the rotation of shapes.

### CODE REVIEW

**Comment by psychon** [comment]
Question: What would be good names for these functions? Is left/right/180° good? Is something like "clockwise" better?

**Comment by Elv13** [comment]
Thanks for taking care of this. It was overdue. The reason while I didn't made this earlier (if I recall, there was some discussions in one of the shape API PR) is that I at some point wanted to include this in the `transform` method so you could do `shape.transform(shape.powerline) : flip_left() : shrink_by(4,4) : translate_by(2,2)`. This is a cool API, but it does create a very, very expensive function call...

(I am well aware you know all that) It is important to point out that this is classical CS theory. Just like RegEx and some other algorithm, affine transformation composition is a really cool math application. It is "compiled" once and then have an `O(1)` execution time, even if there is 9999 transformations. However with this API, each transformation does it own matrix thing (cairo does some multiplication of its own in the background, and we do some on our side). Each transformation become an iteration and is executed everytime the shape is applied/drawn (because it depend on the width/height/current_matrix inputs values). So if we give a nice API like this (and it is really, really useful), don't we kind of shoot the users in the foot if their wiboxes get repainted too often? Game engine use OpenCL/CUDA for this kind of operations for good reasons. Of course, we don't do as many of those as they do (and we do so in 2D), but still. In theory, it could be possible to "compile" this into an `O(1)` matrix and cache it into the hierarchy (just like `fit`). I investigated this a little, but it is non-trivial to implement.

What's your opinion of this? I am in the micro-optimization territory or is it something we should care about? I totally agree this is very useful. I shared similar code a few time on IRC and some of my module have equivalent functions (because I need centroid based rotation, origin rotation are mostly useless).

**Comment by psychon** [comment]
> (if I recall, there was some discussions in one of the shape API PR) 

Yup, that plus some question about it on IRC that I recently saw is why I wrote this (but I didn't try to find that discussion again).

> I am in the micro-optimization territory

Yup, you are.

--------

But if you want, let's think about a more useful API: 
Needed features are likely: Margins (your `shrink_by(4,4):translate_by(2,2)`-example is just a margin of 2 on each side) and rotations by multiples of 90 degrees.

Arbitrary translation/scaling/rotation will likely move the shape outside of the area assigned to it and this will likely not work (e.g. due to clipping). So, this is not needed. Also, the API is intended as a convenience API, not a "make everything possible" API (people who want that can define their own wrapper-shape-functions).

So I guess we should not merge this PR and instead I propose an API break:
Instead of `:transform()` enabling all of the matrix-API, it just provides few functions:
- rotate_left
- rotate_right
- rotate_180 (I still don't like that name, but "flip" doesn't really fit either)
- mirror_horizontally (or is flip_left / flip_right better?)
- mirror_vertically
- set_margin_{left,right,top,bottom}
- set_margin (setting all margins at once)

This provides three features: Rotation, mirroring and margins. Rotation and mirroring are independent (the order in which they are applied does not matter) and for margins we just say that they should be applied first (before rotation/mirroring).
Also, this can be implemented in O(1) time and space (although the constant is slightly higher in both cases than it previously was, but whatever).

What do you think? Is the current "make everything possible `:transform`" needed or can we remove that and switch to the above?

**Comment by psychon** [comment]
@Elv13 (Untested) but how about something like https://gist.github.com/psychon/09cb6511766b28ef0bb272bde41397af ? (Feel free to pick this up, if you want)

**Comment by psychon** [comment]
I vote for merging this. If we latter add a "more complete" convenience-API, this can be changed accordingly or deprecated. For now, this provides the most-often-needed feature in a simpler form.
(And I'll pass on the task for writing that "more complete" convenience-API to someone else)

**Comment by Elv13** [comment]
The PR or the gist? As I will take a closer look tomorrow

**Comment by psychon** [comment]
This PR.

**Pull request closed without merging**
