### PR TITLE
Various fixes / improvements to prompt.run / completion

### PR DESCRIPTION
**Pull request by blueyed**
I've came up with these when looking into completion issues.

This fixes e.g. `Shift-Tab` and completion from inside of the command (not at then end).

~~It also fixes the directory detection/handling for Lua 5.2, adding `awful.util.is_dir`.~~ (extracted)

### CODE REVIEW

**Comment by psychon** [comment]
I don't think this version of `awful.util.is_dir` is portable / works correctly everywhere. Besides that, I have no clue about the completion code and just trust you.

**Comment by blueyed** [comment]
@psychon 
`f:seek("end")` does not work (anymore?!) - it now returns 9.2233720368548e+18 for dirs..

Could we make luafilesystem a dependency, and then just use `lfs.attributes(path, 'mode')=='directory'`?

A slower alternative would be `os.execute("test -d past")`, but that should be avoided.

**Comment by Elv13** [comment]
```
Could we make luafilesystem a dependency, and then just use lfs.attributes(path, 
```

LGI already has that function from GLib, no need for new dependencies beside maybe `Gio`

**Comment by blueyed** [comment]
Just for reference: the current PR introduced a few regressions/bugs that I will have to look into.

**Comment by blueyed** [comment]
> LGI already has that function from GLib, no need for new dependencies beside maybe Gio

Can you provide some code that would do this, please?

**Comment by Elv13** [comment]
> > LGI already has that function from GLib, no need for new dependencies beside maybe Gio
>
> Can you provide some code that would do this, please?

Not until next week, I have some work deadlines to meet, you can look at `fd_async`  from my config, there is something similar. Of course we need to wrap it in a `lua` friendly API, but `Gio` > `LuaFilesystem` as it integrate with our event loop and is asynchronous with co-routines.

**Comment by psychon** [comment]
$ lua -e 'g = require("lgi").GLib ; print(g.file_test("/tmp", { g.FileTest.IS_DIR }))'
    true
    $ lua -e 'g = require("lgi").GLib ; print(g.file_test("/etc/passwd", { g.FileTest.IS_DIR }))' 
    false
    $ lua -e 'g = require("lgi").GLib ; print(g.file_test("/not-exist", { g.FileTest.IS_DIR }))' 
    false

The other possible flags (`IS_REGULAR`, `IS_SYMLINK`, `IS_EXECUTABLE` and `EXISTS`) sound interesting, too.

**Comment by psychon** [comment]
Should some of this be rebased and merged (and perhaps the unrelated `is_dir` one gets its own PR)?

**Comment by blueyed** [comment]
Yes.  I've extraced `is_dir` in https://github.com/awesomeWM/awesome/pull/536.

I would still need to closer at the rest, according to my previous comment:

> Just for reference: the current PR introduced a few regressions/bugs that I will have to look into.

**Comment by psychon** [comment]
Closing for lack of activity

**Pull request closed without merging**
