### PR TITLE
Docs overhaul

### PR DESCRIPTION
**Pull request by blueyed**
This is https://github.com/awesomeWM/awesome/pull/37 rebased / adjusted for master.

It can be viewed at http://codeprobe.de/tmp/awesome-doc/.

### CODE REVIEW

**Comment by blueyed** [comment]
It doesn't break anything obvious: https://travis-ci.org/blueyed/awesome/builds/51465169

**Comment by juw** [comment]
Actually this merge would introduce some whitespace issues, spelling errors and delete some information from the docs. The following patches fix that and more:
```patch
From 7cdf6d16af70975bac7f6810d266d906b7f5ad0e Mon Sep 17 00:00:00 2001
From: Julian Wollrath <jwollrath@web.de>
Date: Fri, 20 Feb 2015 15:21:51 +0100
Subject: [PATCH 1/3] Fixup newly introduced whitespace issues.

Signed-off-by: Julian Wollrath <jwollrath@web.de>
---
 awesomeConfig.cmake   | 2 +-
 lib/awful/ewmh.lua.in | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/awesomeConfig.cmake b/awesomeConfig.cmake
index c4763496a36d..e2bb98c49eea 100644
--- a/awesomeConfig.cmake
+++ b/awesomeConfig.cmake
@@ -272,7 +272,7 @@ set(AWESOME_THEMES_PATH      ${AWESOME_DATA_PATH}/themes)
 # }}}
 
 # {{{ Configure files
-file(GLOB_RECURSE awesome_lua_configure_files RELATIVE 
+file(GLOB_RECURSE awesome_lua_configure_files RELATIVE
     ${SOURCE_DIR}
     ${SOURCE_DIR}/lib/*.lua.in
     ${SOURCE_DIR}/docs/capi/*.lua.in
diff --git a/lib/awful/ewmh.lua.in b/lib/awful/ewmh.lua.in
index 07300f3e2ccc..348de09591c8 100644
--- a/lib/awful/ewmh.lua.in
+++ b/lib/awful/ewmh.lua.in
@@ -156,7 +156,7 @@ function ewmh.activate(c)
 end
 
 --- Tag a window with its requested tag
--- 
+--
 -- @client c A client to tag
 -- @tag[opt] t A tag to use. If omitted, then the client is made sticky.
 function ewmh.tag(c, t)
-- 
2.1.4
```
```patch
From d2b64c09d20738bd9221507aa2c30dd4e8fdf8c6 Mon Sep 17 00:00:00 2001
From: Julian Wollrath <jwollrath@web.de>
Date: Fri, 20 Feb 2015 15:22:44 +0100
Subject: [PATCH 2/3] Add missing changes due to docs-overhaul.

Signed-off-by: Julian Wollrath <jwollrath@web.de>
---
 docs/02-contributing.md | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/docs/02-contributing.md b/docs/02-contributing.md
index 2e9b88fb92e2..2861690e94d5 100644
--- a/docs/02-contributing.md
+++ b/docs/02-contributing.md
@@ -1,9 +1,9 @@
-# Contrubuting
+# Contributing
 
 
 ## Bugs
 
-Please look at http://awesome.naquadah.org/bugs/
+Please look at `https://github.com/awesomeWM/awesome/issues`.
 
 ## Style
 
@@ -59,6 +59,7 @@ If you plan to submit patches, you should follow the following guidelines.
   `Signed-off-by: Your Name <you@example.com>` line to the
   commit message (or just use the option `-s` when commiting);
 - make sure that you have tests for the bug you are fixing.
+- if possible, add a unit test to the test suite under spec/.
 
 ### Patches
 
-- 
2.1.4
```
```patch
From 8fcf3e407b4df96ab805b767c2327301f7dc6c4d Mon Sep 17 00:00:00 2001
From: Julian Wollrath <jwollrath@web.de>
Date: Fri, 20 Feb 2015 15:24:26 +0100
Subject: [PATCH 3/3] Beautify docs a little bit.

Signed-off-by: Julian Wollrath <jwollrath@web.de>
---
 docs/01-readme.md | 4 +++-
 docs/config.ld.in | 8 ++++++++
 2 files changed, 11 insertions(+), 1 deletion(-)

diff --git a/docs/01-readme.md b/docs/01-readme.md
index 243444f169af..051388ca241d 100644
--- a/docs/01-readme.md
+++ b/docs/01-readme.md
@@ -1,4 +1,6 @@
-# awesome
+# Readme
+
+## About awesome
 
 awesome is a highly configurable, next generation framework window manager for X.
 
diff --git a/docs/config.ld.in b/docs/config.ld.in
index 810a3cbb4310..5f30693821c9 100644
--- a/docs/config.ld.in
+++ b/docs/config.ld.in
@@ -13,6 +13,8 @@ pretty='lua'
 style="!pale"
 backtick_references=true
 merge=true
+use_markdown_titles = true
+wrap=true
 topics={
     '00-authors.md',
     '01-readme.md',
@@ -25,6 +27,12 @@ tparam_alias('tag', 'tag')
 -- Should be default, but is not.  Sets up "@tab" => "@tparam table".
 tparam_alias('tab', 'table')
 
+-- More fitting section names
+kind_names={topic='Documentation',module='Libraries'}
+
+-- Sort modules alphabetically
+sort_modules=true
+
 file = {
     -- LUA libraries
     'capi/',
-- 
2.1.4
```

**Comment by juw** [comment]
I just pushed the above mentioned to 'https://github.com/juw/awesome.git docs' for your consideration.

**Comment by blueyed** [comment]
Thanks!

What do you think about adding a symlink to the README, which has been moved inhttps://github.com/juw/awesome/commit/097f8bac3a5f3196440e365a77e754b2947a01a8?

**Comment by juw** [comment]
One could certainly do that, to have the README at the classic place.
So yes, why not.

Am Sat, 21 Feb 2015 12:01:06 -0800
schrieb Daniel Hahler <notifications@github.com>:

**Comment by blueyed** [comment]
Rebased it on master, merged @juw's improvements and created the README symlink.

**Comment by juw** [comment]
I just realized, that 'make ldoc' does not work because of two errors.
I pushed fixes for that to 'https://github.com/juw/awesome.git docs'.

Am Sun, 22 Feb 2015 13:05:50 -0800
schrieb Daniel Hahler <notifications@github.com>:

**Comment by blueyed** [comment]
@juw 

> I just realized, that 'make ldoc' does not work because of two errors.

Yes, I've noticed the same.  Thanks for fixing it - merged.

**Comment by blueyed** [comment]
I've pushed the current state to: http://codeprobe.de/tmp/awesome-doc/

I think it's generally good to be merged, but would like to see some other review(s).

**Comment by Elv13** [comment]
look promising. `screen` is a class, `wibox` too

**Comment by blueyed** [comment]
@Elv13 

> screen is a class

Are you referring to http://codeprobe.de/tmp/awesome-doc/libraries/screen.html#screen ?

**Comment by Elv13** [comment]
I am referring to the left page categories ("Libraries", "Classes", "Documentation")

**Comment by juw** [comment]
I changed screen and everything wibox related to be mentioned as
classes in the docs. As before, this can be found under
'https://github.com/juw/awesome.git docs'.

**Comment by blueyed** [comment]
Merged, rebased on master and updated the online doc: http://codeprobe.de/tmp/awesome-doc/

I plan to merge this in the next days. /cc @psychon

**Comment by psychon** [comment]
I don't have much to say. Quickly scrolled through the full diff and things look promising.

Only thing that I can wish for: A quick summary on how to write ldoc comments in 02-contributing.md. This could also quickly explain the discount format, whatever that is. Perhaps with a link at the end to more docs?

**Comment by juw** [comment]
I added a section about how to document the files. As before, the
changes can be found under `https://github.com/juw/awesome.git docs`.

> This could also quickly explain the
> discount format, whatever that is.

It is just a bit enhanced Markdown parser.

**Comment by blueyed** [comment]
Cool. Merged and fixed a bit.

I've also changed the "Patches" section, leaving the possibility of git-send-email: https://github.com/awesomeWM/awesome/commit/14d3f7cfbb9c4edbd6f38834e28f8750f1da829d

@psychon 
Is this OK like this?

**Comment by juw** [comment]
> Cool. Merged and fixed a bit.
Cheers.
 
I just found another unnecessary usage of HTML,
https://github.com/juw/awesome/commit/214b3c74548b65294a71d6cf4a24699932fbe546
gets rid of it.

**Comment by blueyed** [comment]
Merged again.  I've also looked at the list from `ag '<\w+>'` and fixed some remaining usages of wrong html markup.

I've also changed/removed the ignore for `awful.widget.common`, and added some (probably incomplete/wrong) documentation for it: https://github.com/awesomeWM/awesome/commit/bfb79eef00681e79a0fc3a1f2c1d4d9b7f8fb30d

**Comment by juw** [comment]
And one more fix for the contributing guide:
https://github.com/juw/awesome/commit/9f3daea1f1a6f67932b7ee874a1dccb29c30b81d

**Comment by juw** [comment]
And one other thing I stumbled upon: What benefit has it to keep basically empty module docs e.g. as we have it for awful or gears? IMHO there should be either a short description along the lines of "this module is the parent for all awful.* modules and includes them" or we should drop them from the docs, since there is no real value in having them.

**Comment by blueyed** [comment]
> there should be either a short description along the lines of "this module is the parent for all awful.* modules and includes them" or we should drop them from the docs

Yes.  That's what I've done for awful.widget.

I think it's good to have / use them for cases like awful.widget though, where the widget mechanism could be described.

**Comment by juw** [comment]
> I think it's good to have / use them for cases like awful.widget
> though, where the widget mechanism could be described.

Good point. Sadly I am not very familiar with the widget system, so I
can not write something meaningful. But maybe
http://awesome.naquadah.org/wiki/Widgets_in_awesome can serve as a
starting point for who ever has enough knowledge and is willing to
write something.

**Comment by juw** [comment]
https://github.com/juw/awesome/commit/4b300cda7b1996b9e3787bd1d37d640edcd3207c drops the remaining empty module descriptions from the docs.

**Comment by juw** [comment]
The remark with respect to `@param[opt] ...` can be ignored. https://github.com/juw/awesome/commit/52fc7249fd6f7a39fe5410b2730af2f35f7392f6 takes care of all places that I could find via `grep -Enr '^*-*[Oo]ptional' lib | sed '/\[opt\]/d'` where usage of `@param[opt] ...` is reasonable.

**Comment by blueyed** [comment]
> The remark with respect to @param[opt] ... can be ignored. 

Ok, cool! :)

**Comment by juw** [comment]
In case you did not notice: Somehow the unrelated commit https://github.com/awesomeWM/awesome/commit/30b6fcbbd1c1196f43355bcd11db31c59accc108 creeped into this pull request…

**Comment by juw** [comment]
One other thing: Why is the C-API documented in extra files and not in the C source code? [LDoc can parse C files](https://stevedonovan.github.io/ldoc/manual/doc.md.html#Extension_modules_written_in_C). As example, I sketched (quick and dirty) how this could look for the keygrabber API (see https://github.com/juw/awesome/commit/8254fd4b72a0346d908941ce5ad2c90c69faf412). Small disclaimer: I am not sure, if this would break doxygen. What are your thoughts? Is this something worthwhile to do?

**Comment by blueyed** [comment]
Not sure about 30b6fcb - it does not show up in `git diff master..` and is displayed more light above..

> One other thing: Why is the C-API documented in extra files and not in the C source code?

I don't know. 
@psychon 
What do you think about @juw's comment above - improving / moving the documentation into the C files?

For now I am going to merge this PR - without the last commit (https://github.com/juw/awesome/commit/8254fd4b72a0346d908941ce5ad2c90c69faf412).

**Comment by blueyed** [comment]
> I am not sure, if this would break doxygen

This could be tested / checked easily.

I think it's a good idea.  It keeps the documentation nearer to what it documents.

Please feel free to create a new / separate PR for this - starting with your last commit - in case there's nothing we're overseeing.

**Comment by psychon** [comment]
Feel free to move the API docs into the C files. I know that ldoc can parse that, but I never tried it myself. I guess the reason for the current state is "luadoc" and moving things over likely means that "stuff" breaks less often.

However, I don't know how things like `.instances` and `:emit_signal` would work...

Also, do we really need doxygen on the C source files? I'm bad with using docs and just browse the source code directly (and I guess I already know too much about awesome's internals anyway). @blueyed  You looked into doxygen, is the result usable and should it be kept?

**Comment by blueyed** [comment]
> You looked into doxygen, is the result usable and should it be kept?

Not really, just fixed some warnings.  You can see it generated at: http://codeprobe.de/tmp/awesome-doc/html/

**Comment by psychon** [comment]
Doesn't seem helpful to me

**Pull request merged**
