### PR TITLE
tests: improve assert message in test-maximize

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Why does codecov complain about `awful.layout.suit.magnifier`?  https://codecov.io/gh/awesomeWM/awesome/compare/052cda939b8a5ce1cf2152a89b48b6fa55a0dbb5...913580d6d46d7b98174925415686aa0b46c68e76/src/lib/awful/layout/suit/magnifier.lua  /cc @codecov-io

**Comment by psychon** [comment]
> Why does codecov complain about awful.layout.suit.magnifier?

Only explanation that I could provide: We have a race somewhere. In some executions awesome is so slow that the layout did not yet run when the next layout is set...?

**Comment by Elv13** [comment]
This now conflicts with #1608. The other PR add yet more `assert()` messages and other goodies. I suggest either cherry picking these commits into this PR or closing it.

**Comment by blueyed** [comment]
Added it to #1608: https://github.com/awesomeWM/awesome/pull/1608/commits/531d24125fb9395fa50408623f669813d483349e.

**Pull request closed without merging**
