### PR TITLE
Only use useless_gap with multiple tiled clients

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/awesomeWM/awesome/issues/564.

### CODE REVIEW

**Comment by psychon** [comment]
How about adding a special setting for useless gaps when only a single client is visible (which defaults to either 0 or the "normal gaps", whatever you prefer)? That might make Elv13 and the user he mentions happy.

This version is also fine with me.

**Comment by blueyed** [comment]
@psychon 
Thanks for your feedback.  See the fixup commit.

**Comment by psychon** [comment]
:+1:

**Comment by actionless** [comment]
i have this exception from time to time now:

```
Error during delayed call: /usr/share/awesome/lib/awful/client.lua:230: bad argument #1 to 'get' (screen expected, got string)
stack traceback:
        [C]: in field 'get'
        /usr/share/awesome/lib/awful/client.lua:230: in function 'awful.client.visible'
        /usr/share/awesome/lib/awful/client.lua:246: in function 'awful.client.tiled'
        /usr/share/awesome/lib/awful/layout/init.lua:124: in field '?'
        /usr/share/awesome/lib/gears/timer.lua:164: in function </usr/share/awesome/lib/gears/timer.lua:163>
        [C]: in function 'xpcall'
        /usr/share/awesome/lib/gears/timer.lua:163: in function </usr/share/awesome/lib/gears/timer.lua:161>
```

**Comment by blueyed** [comment]
@actionless 
This happens in `client.visible`.
Fixed in 58bd21a.  Thanks!

**Pull request closed without merging**
