### PR TITLE
doc: mention to select a tag on awful.tag.add (#1509)

### PR DESCRIPTION
**Pull request by sudo-nice**

### CODE REVIEW

**Comment by Elv13** [comment]
I think `selected` can/should be inside as one of the property (along with the others)

**Comment by sudo-nice** [comment]
I didn't notice that, thank you. I've updated th PR, please, check.

**Comment by blueyed** [comment]
I will cherry-pick and slightly amend it.

**Comment by blueyed** [comment]
```diff
diff --git i/objects/tag.c w/objects/tag.c
index 970d79b0..f8bf7874 100644
--- i/objects/tag.c
+++ w/objects/tag.c
@@ -46,7 +46,7 @@
  *        gap_single_client  = true,
  *        gap                = 15,
  *        screen             = s,
- *        selected           = true
+ *        selected           = true,
  *    })
  *
  *    awful.tag.add("Second tag", {
@@ -55,8 +55,8 @@
  *        screen = s,
  *    })
  *
- * Note, the example above sets "First tag" selected. Without selecting tag
- * explicitly you will find yourself out of any selected tag.
+ * Note: the example above sets "First tag" to be selected explicitly,
+ * because otherwise you will find yourself without any selected tag.
  *
  * **Accessing tags**:
  *
```

Does it make (more) sense?

**Comment by sudo-nice** [comment]
@blueyed 
Thank you, the PR is updated.

**Comment by blueyed** [comment]
@sudo-nice 
You wouldn't have to do it (I would have committed it directly, in your name), but OK: good practice for you I guess.. ;)

**Comment by blueyed** [comment]
Thanks again, @sudo-nice!

**Pull request merged**
