### PR TITLE
config: sloppy focus: ignore mouse::enter if mouse was not moved

### PR DESCRIPTION
**Pull request by blueyed**
When raising a client's transient_for window, the parent window gets
also raised.  This might trigger a `mouse::enter` signal for the parent
window, if it was not visible at the mouse pointer's position before.

The sloppy focus handler in the default config now ignores any
`mouse::enter` events, when the mouse coordinates have not changed since
the last signal.

### CODE REVIEW

**Comment by blueyed** [comment]
In my own config I was remembering the client from the last signal and compared it to the one from the current signal, which might be better and/or could be used additionally.

It helped to ignore the signal when using `rofi`, which uses a temporary redirected / on-top window.

**Comment by psychon** [comment]
Isn't this exactly the reason why `client_ignore_enterleave_events()` exists in the C code? To avoid spurious enter signals. This problem could be fixed by adding such calls around `stack_refresh` in the C code.

Long-term (aka "if anyone ever wants those signals to occur"), we could provide a context argument to the `mouse::enter` signal that says if the mouse was really moved or if this happened because some client was configured suitably...

**Comment by r8b7xy** [comment]
Your pull request solve the problem with unclutter I've mentioned in [#202](https://github.com/awesomeWM/awesome/issues/202) but I've found one drawback - cursor unhide when I close last client under hidden cursor. Do you have any idea how to fix this issue?

**Comment by blueyed** [comment]
@r8b7xy 
Can you check if the last change (https://github.com/blueyed/awesome/commit/0438133dfc3fc699368e53df98b5f8f1f31e93bc) still fixes it for you? (it only looks at the client)
That might also fix the issue mentioned in your comment above.

At least it helps with the extra popup about potentially forgotten attachments from Thunderbird after the "Send" dialog.  This wasn't focused for me.

**Comment by r8b7xy** [comment]
``` lua
- run_once("unclutter")
+ run_once("unclutter -root")
```
and your last change (blueyed@ 0438133) fix the problem.
With previous configuration I've mentioned here (copycat-killer/awesome-copycats#81) and root option cursor sometimes blinked.
Thank you.

**Comment by blueyed** [comment]
@psychon 
> Isn't this exactly the reason why `client_ignore_enterleave_events()` exists in the C code?

Not sure if it would help here: the problem exists with e.g. Thunderbird, too:

 - maximized Thunderbird main window as the only client on a tiled tag
 - right click on a mail, choose "Forward as => Attachment"
 - the "Compose" window pops up, which is handled via rules, and will be not below the mouse cursor

    { rule = { class = "Thunderbird", instance = "Msgcompose" },
      properties = { floating = true }},

 - the main window gets focused, instead of the new one

This is not really reproducible, but lead me to dig out this old PR again.

It seems like `mouse::enter` really should not be triggered in this case, and is not done so anymore after looking closely at it.

Any ideas why `mouse::enter` might have been triggered, or what else might have caused this?

**Comment by psychon** [comment]
The only commit that I remember that messes with enter/leave would be d96c4d61a9a50b205f8b2e01635775cd4bc90fb5. However, I don't think that should make a difference here. Dunno...

**Comment by Elv13** [comment]
Can this be closed or is it sitll relevant?

**Comment by Elv13** [comment]
Closing for lack of activity re-open if needed.

**Comment by blueyed** [comment]
Revisited my code.

What do you think?

```lua
-- Enable sloppy focus.

-- Skip focusing the client if the mouse wasn't moved (to a new client, and
-- in general).
do
  local sloppyfocus_last
  local sloppyfocus_timer
  local sloppyfocus_timeout = 0.1

  client.connect_signal("mouse::enter", function(c)
    if not use_sloppy_focus then  -- NOTE: I am using this for toggling it, but could/should connect/reconnect the signal instead.
      return
    end
    if awful.layout.get(c.screen) == awful.layout.suit.magnifier or
        not awful.client.focus.filter(c) then
      return
    end

    -- Stop any existing timer.
    if sloppyfocus_timer then
      sloppyfocus_timer:stop()
      sloppyfocus_timer = nil
    end

    -- Check if focused already (when moving back and forth).
    if client.focus == c then
      sloppyfocus_last = nil
      return false
    end

    local mcoords = mouse.coords()
    sloppyfocus_last = {x = mcoords.x, y = mcoords.y}

    sloppyfocus_timer = timer.start_new(sloppyfocus_timeout, function()
      mcoords = mouse.coords()
      if (mcoords.x == sloppyfocus_last.x and mcoords.y == sloppyfocus_last.y) then
        c:emit_signal("request::activate", "mouse_enter", {raise = false})

        -- Reset state and stop timer.
        sloppyfocus_last = nil
        sloppyfocus_timer = nil

        return false
      end

      -- Update mouse position, and restart timer.
      sloppyfocus_last.x = mcoords.x
      sloppyfocus_last.y = mcoords.y

      return true
    end)
  end)
end
```

**Pull request closed without merging**
