### PR TITLE
fix deprecation warning

### PR DESCRIPTION
**Pull request by aroig**
Fixes a deprecation warning resulting from the recent API changes.

### CODE REVIEW

**Comment by psychon** [comment]
The travis build failed, could you also fix the following: `lib/awful/widget/tasklist.lua:18:7: unused variable client`
(Feel free to squash this change into your commit so that this pull request still only has a single commit)

**Comment by aroig** [comment]
Done! Sorry for not having checked travis' complaints.

**Comment by psychon** [comment]
Thanks

**Comment by Elv13** [comment]
Thanks, sorry for the deprecation warning noise

**Pull request merged**
