### PR TITLE
Fullscreen test

### PR DESCRIPTION
**Pull request by psychon**
This adds the test requested by https://github.com/awesomeWM/awesome/pull/1764#pullrequestreview-36937688.
Edit: Also related to: https://github.com/awesomeWM/awesome/pull/1781

### CODE REVIEW

**Comment by psychon** [comment]
The build failure should be addressed by #1798.

**Comment by blueyed** [comment]
Please rebase.

**Comment by psychon** [comment]
> Please rebase.

Done, Travis is looking at the result.

**Comment by blueyed** [comment]
They liked it!
Thanks!

**Pull request merged**
