### PR TITLE
Add another declarative example

### PR DESCRIPTION
**Pull request by Elv13**
Requested by rnabinger on IRC

aAA

### CODE REVIEW

**Comment by psychon** [comment]
I find the resulting image confusing. How about adding different colors to make it a bit easier to tell which progressbar is which? (I was actually thinking in the wrong direction here and wondered where the free space comes from...)

**Comment by actionless** [comment]
in that casse it would be better to use not just 3 different colors, but 3 different gradients, to represent the direction

**Comment by Elv13** [comment]
Done

pick8

**Comment by Elv13** [comment]
pick8

as requested by actionless

**Pull request merged**
