### PR TITLE
Make client.focusable writable from Lua

### LINKED ISSUE #237: Set window as unfocusable
Was trying to find a way to set specific window un-focusable. 
For example, since the video live wallpaper doesn't play nice with compositing managers I'm using mpv as follows ` mpv --no-input-default-bindings --no-osc --fs --on-all-workspaces <filename ` which puts mpv on all workspaces in fullscreen mode and I can use on top of it with transparency enabled.
The problem rises with the window being focusable - when i switch tags or switching between open clients the video getting focus and hiding everythin under it (which is pretty obvious). Though if it would be possible to make it unfocusable it will work "perfectly" for the use I need, plus will allow the gimmick (a bit hackish though) of live video wallpaper for awesome ;)

### PR DESCRIPTION
**Pull request by blueyed**
It uses an extra boolean to keep track of if `c.focusable` has been set.

It's possible to unset the overriding by setting it to `nil`, i.e.
`client.focus.focusable = nil`.

Fixes #237

### CODE REVIEW

**Comment by blueyed** [comment]
@psychon 
Thanks for your feedback!

I've addressed the issues in the fixup-commit.

**Comment by psychon** [comment]
:+1:

**Comment by osleg** [comment]
The client spawns unfocusable.
Everything works fine untill clicking on it. While it remains it's unfocusable status it does still focus on tag switch.

**Comment by blueyed** [comment]
> While it remains it's unfocusable status it does still focus on tag switch.

What do  you mean exactly?
It seems to happen for me only, if it's the only client on that tag. Do you mean that?
(This does not appear to come from "autofocus").

**Comment by osleg** [comment]
1. Spawn unfocusable client
2. Change to tag with this client only
3. Click on it with mouse
4. Change to another tag that have other clients
Expected behaviour on change: one of the focusable clients getting focus, unfocusable client losing it
What does happen: unfocusable client always in focus until you manualy switch to another client, and it intercept focus on every tag switch

**Comment by blueyed** [comment]
@osleg 
I could reproduce it that way.  I've added a commit (c380da4) to address this.

**Comment by osleg** [comment]
It does not intercept focus anymore but still remains focused if it was focused before tag switch

**Comment by blueyed** [comment]
You mean when going back to the tag where it was forcefully focused?

**Comment by osleg** [comment]
No, like this:
tag 1 = 2 urxvt clients
running mvp with `--on-all-workspaces` the rule on mvp is
```
    { rule = { instance = "mpvldb" },
          properties = { focusable = false,
                         below = true,
                         floating = true,
                         maximized = true
                        } },

```

Now going to tag[2], clicking on mvp window and going back to tag[1] - mvp 
still focused. Explicitly focusing another window and mvp losing focus for 
good.

**Comment by psychon** [comment]
I think that "becomes focus" issue is basically https://awesome.naquadah.org/bugs/index.php?do=details&task_id=574 and doesn't have anything to do with this change.
AFAIK the problem is that the focus history (awful.client.focus.history) ignores awful.client.focus.filter and thus a sticky client is always "more recent" in the focus history than clients on another tag.
In the case at hand: Once the unfocusable client is in the focus history, autofocus (and other code paths) will happily focus it.

I'm not sure how exactly this should be fixed. When the other cycles through the history by hand, the "true" focus history should be used, I guess. But anything automatical should honor focus.filter.

Anyway: I don't think this is related to this changes.

**Comment by blueyed** [comment]
I think the change to client.focus.history.add (https://github.com/blueyed/awesome/commit/c380da4ff156aec9ec08731e023e4864fed7fa93) is bad, but that autofocus should use focus.filter.

I will change that - but then in a separate PR, because it's really different / another fix.

**Comment by blueyed** [comment]
@osleg 
Can you try if https://github.com/awesomeWM/awesome/pull/242 works as expected for you?

**Pull request closed without merging**
