### PR TITLE
Added _hover & _click to client buttons

### PR DESCRIPTION
**Pull request by legostax**
Every client button type (e.g. minimize, maximize_inactive, maximize_active, close) has the option to show a different icon when the mouse hovers over it or a "button::press" signal is sent.
Hopefully my documentation isn't too repetitive...
Signed-off-by: Lego Stax legostax@gmail.com

### CODE REVIEW

**Comment by Elv13** [comment]
Thanks for this. The CI wants you to fix some unused function arguments

```
    lib/awful/titlebar.lua:648:56: unused argument mod
    lib/awful/titlebar.lua:648:61: unused argument x
    lib/awful/titlebar.lua:648:64: unused argument y
    lib/awful/titlebar.lua:663:50: unused argument mod
    lib/awful/titlebar.lua:663:55: unused argument x
    lib/awful/titlebar.lua:663:58: unused argument y
```

Otherwise `titlebar_floating_button_normal_active_click` sigh... How long before we get 16 layers of options `5*2*2^16` titlebar variables, yay! Anyway, can't argue with hover/pressed as other WMs have them

I would however rename `click` to `press`

**Comment by legostax** [comment]
> lib/awful/titlebar.lua:648:56: unused argument mod, x, y

Fixed this one, but I'm pretty lost as far as using `mouse.is_left_mouse_button_pressed` to fix the second one.  I've tried it in my `rc.lua` by running a timer that fires every second.  I hold the left mouse button and it still returns false.  Any ideas?

**Comment by Elv13** [comment]
Just name the arguments `_` if you don't use them (like in Go)

**Comment by Elv13** [comment]
Ok, good, the linting now works. We currently don't have integration tests for this, so I guess it can be merged. Testing it isn't impossible, but it wont be funny.

**Comment by legostax** [comment]
I tested it for close, maximize, and minimize buttons.  I imagine ontop, sticky, and floating should work too.  However, I don't know what would happen if the _inactive/_active or _normal/_focus attributes were omitted.

**Comment by Elv13** [comment]
Thanks

**Pull request merged**
