### PR TITLE
awful.tag: emit property:: signals only on change

### PR DESCRIPTION
**Pull request by blueyed**
This can have a significant performance impact in case you listen to the
property::hide signal to auto-hide tags for example.

### CODE REVIEW

**Comment by Elv13** [comment]
+1

**Comment by psychon** [comment]
Sorry, I don't get the commit message. What's messing with the "hide" property so much? As far as I see, nothing in awesome ever sets it (we don't even provide a setter for it).

The patch itself is obviously correct, but while you are at it, you should also fix this in `awful.client.property.set`.

**Comment by blueyed** [comment]
@psychon 
I've added a new commit for `awful.client.property.set`.

As for the "hide" property: I am setting it myself (to autohide empty, non-current tags), and it gets respected/queried in `lib/awful/widget/taglist.lua`

**Comment by blueyed** [comment]
Merged in bd885f59 and ae7c7ff3.

**Pull request closed without merging**
