### PR TITLE
luacheck: configure it for .luacheckrc itself

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by psychon** [comment]
Uhm, why? Which problem does this fix?

**Comment by actionless** [comment]
@psychon it's not enabled in travis but if you have autolinter enabled in your editor then luacheck raises:

```
  1 .luacheckrc|2 col 1 warning| setting non-standard global variable 'std'
  2 .luacheckrc|5 col 1 warning| setting non-standard global variable 'self'
  3 .luacheckrc|8 col 1 warning| accessing undefined variable 'files'
  4 .luacheckrc|11 col 1 warning| accessing undefined variable 'files'
  5 .luacheckrc|14 col 1 warning| setting non-standard global variable 'read_globals'
  6 .luacheckrc|36 col 1 warning| setting non-standard global variable 'globals'
```

**Comment by actionless** [comment]
some offtopic:


`X    codecov/project — 80.66% (-0.01%) compared to 52011a6`

mb we could configure codecov not to react on such small values?

**Comment by blueyed** [comment]
Yeah, Neomake made me do this.. ;)

**Pull request merged**
