### PR TITLE
fix(gears: colors: recolor_image): always duplicate the surface

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by psychon** [comment]
Fine with me, although technically this is a breaking change since some code out there could depend on this function not creating a copy of the surface.

**Comment by actionless** [comment]
but from reading documentation no one could get an impression what it's modifying existing object if it's not a string with path

in documentation is stated what it returns recolored image

so IMO it's a fix, not API change

**Comment by actionless** [comment]
i was just never noticing the bug because never attempting to use the same image with different colors until yesterday :)

**Comment by actionless** [comment]
BUMP

**Review by sclu1034 — APPROVED** [review]

**Comment by Aire-One** [comment]
I think this is ok for merge.

However, I understand the concern @psychon has.
Would it be a good practice to wrap this change behind an `awesome.api_lvl > 4` condition? So the old behavior wouldn't be break and we still introduce the fix into the code base.

Maybe it's a bit overshot for such a bug fix?

**Comment by actionless** [comment]
i feeling a bit stupid repeating myself, but here we are:

that behavior was always a bug, nothing  in the documentation implies what the current behavior is intentional

**Review by Elv13 — APPROVED** [review]
Yeah, this is a bug, I agree.

**Pull request merged**
