### PR TITLE
Send a default action when notification is closed by user

### LINKED ISSUE #3182: Clicking notification does not urgent/raise client
This issue has been reported on reddit and seems to be an regression from v4.3. If this is not a regression please just close this one. I tried searching the existing issues but wasn't able to find something related.

[Reddit Post](https://www.reddit.com/r/awesomewm/comments/itsb5o/clicking_to_notifications_doesnt_raise_app/)

Output of `awesome --version`:

v4.3 according to the reddit discussion.

**How to reproduce the issue:**

Click on a notification sent by a client (for example Spotify)

**Actual result:**

The notification disappears, that's all.

**Expected result:**

Clicking a notification in v4.3 seems to have raised the sending client and set it to urgent. This does not work with the latest git version anymore.

Note that I didn't have time to verify the behavior in v4.3 yet but the reddit user reports that it worked that way. See link above.

**Workaround**

Using the following signal handler seems to at least mimic the old behavior:

```lua
local naughty = require('naughty')
local cst = require("naughty.constants");

naughty.connect_signal('destroyed', function(n, reason)
    if not n.clients then return end
    if reason == cst.notification_closed_reason.dismissed_by_user then
        for _, cli in ipairs(n.clients) do
            cli.urgent = true
            cli:emit_signal("request::activate", {raise=true})
        end
    end
end)
```

### PR DESCRIPTION
**Pull request by BarbUk**
Really fix #3182

### CODE REVIEW

**Review by Elv13 — APPROVED** [review]

**Comment by seqizz** [comment]
Thanks!
This looks like properly switching to the target channel, at least on on Slack & Telegram.

**Comment by BarbUk** [comment]
> Thanks!
> 
> With this, looks like I can properly switching to the target channel, at least on on Slack & Telegram.

I tested different notifications and applications from my side:

 - chrome / gmail (with two chrome instances running): it open the correct tab/mail
 - slack: open the correct channel
 - mattermost: open the correct channel

So it seems to work.

> Yet I am not sure if we should include the feature (which is given [here](https://github.com/awesomeWM/awesome/issues/3182#issuecomment-1753211773)) directly into WM or leave it out.

It needs more work to handle edge case I think.
I could include it in another PR under a config flag like `naughty.config.follow_clicked_notification`.

In any case, it should be documented somewhere if people like to jump to the right client when clicking a notification.

**Review by actionless — APPROVED** [review]
thanks 👌😺

**Comment by BarbUk** [comment]
FYI this PR fix https://github.com/awesomeWM/awesome/issues/3182 but it's not a perfect solution as it send a default action for all notification dismissed by a user.

So if I have a notification with two actions (default, action 1, action 2), and I click on the second action, it will send:
 - default
 - action 2
 
I'll make another PR with a proper fix.

**Pull request merged**
