### PR TITLE
fix(hotkeys_popup: new): workaround gears.table.join() stopping on first nil element

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by actionless** [comment]
@Elv13 oops, sorry, i hotfixed formatting and didn't noticed what you've reviewed already

**Comment by actionless** [comment]
ok :D

**Comment by Elv13** [comment]
Ignore the unrelated build failures, I have yet to investigate them. I will see once I clear my open PRs. Some of my spawn tests are race_prone/unreliable.

**Comment by actionless** [comment]
@psychon with the default config you need to open `gvim` and press <kbd>mod</kbd>+<kbd>s</kbd>

**Comment by psychon** [comment]
See #2440

**Comment by actionless** [comment]
thanks!

**Comment by psychon** [comment]
> @psychon with the default config you need to open `gvim` and press <kbd>mod</kbd>+<kbd>s</kbd>

And then? That opens the popup showing gvim key bindings...

Ahh, the problem is that some of the "headlines" have no keys below them. Okay.

**Pull request closed without merging**
