### PR TITLE
ldoc: use custom ldoc.ltp for improved HTML title

### PR DESCRIPTION
**Pull request by blueyed**
This should help a lot with making the docs appear better in search results (https://github.com/awesomeWM/awesome/issues/1275).

### CODE REVIEW

**Comment by actionless** [comment]
could you make a screenshot of how it looks when built?

**Comment by blueyed** [comment]
@actionless 
I've checked that `<title>` tags are changed with this..
A screenshot would not really help, but the idea is that https://duckduckgo.com/?q=watch+site%3Ahttps%3A%2F%2Fawesomewm.org%2Fapidoc%2F&ia=web would look better.

**Comment by actionless** [comment]
ah, it's only about <title>? no visible markup changes at all?

**Comment by blueyed** [comment]
Yes.. the `<title>` however is visible in the browser's titlebar / tab / etc.

This is based on the default template, with only adjustments for title (based on what is used in `<h1>`s already further down).

**Comment by Elv13** [comment]
thanks

**Comment by Elv13** [comment]
Build failed because lua.org is under DDOS (or we had too many awesome contributions today, choose one)

**Pull request merged**
