### PR TITLE
docs: move documentation to C source

### PR DESCRIPTION
**Pull request by blueyed**
This is a followup of https://github.com/awesomeWM/awesome/pull/177, rebased on master.

Discussion should continue there for now.

### CODE REVIEW

**Comment by psychon** [comment]
Looks all fine with me, but the change that gets rid of the `.in` extension and in turn apparently also causes C source code to be copied around seems weird to me. For the Lua code we had a reason to do so at least (expanding `@AWESOME_VERSION@`).

**Comment by blueyed** [comment]
It has been done after https://github.com/awesomeWM/awesome/pull/177#issuecomment-86660343 - where the `.c` files had been moved to `.in` before.

The `COPYONLY` for the C/all files gets done to build the documentation from it AFAIK.

@juw 
Can you chime in?

(as a sidenote: I've seen some weird behaviour when the build aborted (because of some ldoc config error from my experimenting): this caused recursive `.build-.*` dirs somehow, but might have been related to my disk running full)

**Comment by juw** [comment]
Am Sat, 20 Jun 2015 03:54:56 -0700
schrieb Daniel Hahler <notifications@github.com>:

> It has been done after
> https://github.com/awesomeWM/awesome/pull/177#issuecomment-86660343 -
> where the `.c` files had been moved to `.in` before.
> 
> The `COPYONLY` for the C/all files gets done to build the
> documentation from it AFAIK.
> 
> @juw 
> Can you chime in?
Exactly, since the documentation is now contained in the .c files, they
also contain `@AWESOME_VERSION@`, which has to be processed by cmake.
Of course, one could hand-pick only the files, that need to be
processed plus the header files, but its way easier, to just copy
everything and build with the whole source out of tree, to not run into
weird problems during the build.

> 
> (as a sidenote: I've seen some weird behaviour when the build aborted
> (because of some ldoc config error from my experimenting): this
> caused recursive `.build-.*` dirs somehow, but might have been
> related to my disk running full)
I have never experienced something like that, so your guesses are as
good as mine.

Cheers.

**Comment by juw** [comment]
Am Sat, 20 Jun 2015 03:54:56 -0700
schrieb Daniel Hahler <notifications@github.com>:

> It has been done after
> https://github.com/awesomeWM/awesome/pull/177#issuecomment-86660343 -
> where the `.c` files had been moved to `.in` before.
> 
> The `COPYONLY` for the C/all files gets done to build the
> documentation from it AFAIK.
Actually, the `COPYONLY` is only done for the docs/*.md files, so that
we can describe in the docs where and how to use `@AWESOME_VERSION@`
without it getting replaced by cmake. The files need to be present in
the actual build directory, so that ldoc can process them during the
generation of the docs.

Cheers.

**Comment by psychon** [comment]
:+1:

**Comment by actionless** [comment]
default themes became broken:
```
$ grep "@" /usr/share/awesome/themes/ -R | head
Binary file /usr/share/awesome/themes/default/submenu.png matches
/usr/share/awesome/themes/default/theme.lua:theme.taglist_squares_sel   = "@AWESOME_THEMES_PATH@/default/taglist/squarefw.png"
/usr/share/awesome/themes/default/theme.lua:theme.taglist_squares_unsel = "@AWESOME_THEMES_PATH@/default/taglist/squarew.png"
/usr/share/awesome/themes/default/theme.lua:theme.menu_submenu_icon = "@AWESOME_THEMES_PATH@/default/submenu.png"
/usr/share/awesome/themes/default/theme.lua:theme.titlebar_close_button_normal = "@AWESOME_THEMES_PATH@/default/titlebar/close_normal.png"
/usr/share/awesome/themes/default/theme.lua:theme.titlebar_close_button_focus  = "@AWESOME_THEMES_PATH@/default/titlebar/close_focus.png"
/usr/share/awesome/themes/default/theme.lua:theme.titlebar_ontop_button_normal_inactive = "@AWESOME_THEMES_PATH@/default/titlebar/ontop_normal_inactive.png"
/usr/share/awesome/themes/default/theme.lua:theme.titlebar_ontop_button_focus_inactive  = "@AWESOME_THEMES_PATH@/default/titlebar/ontop_focus_inactive.png"
/usr/share/awesome/themes/default/theme.lua:theme.titlebar_ontop_button_normal_active = "@AWESOME_THEMES_PATH@/default/titlebar/ontop_normal_active.png"
/usr/share/awesome/themes/default/theme.lua:theme.titlebar_ontop_button_focus_active  = "@AWESOME_THEMES_PATH@/default/titlebar/ontop_focus_active.png"
```

**Comment by blueyed** [comment]
@actionless 
Fixed in 32b5842.

Regarding the "recursive .build* dir" issue (which I've mentioned above), see https://github.com/awesomeWM/awesome/pull/273.

**Comment by actionless** [comment]
oops, did not noticed that new commit

**Pull request merged**
