### PR TITLE
request::activate with client.movetoscreen

### PR DESCRIPTION
**Pull request by blueyed**
@Elv13 
Is using the context with the signal here done correctly / as you would expect it?

### CODE REVIEW

**Comment by Elv13** [comment]
thanks

I like the movetoscreen idea, this will be useful, I may merge this later on. For now I still need to review some of the earlier PR

**Comment by blueyed** [comment]
I think this should be improved to check if the client is currently focused before changing the screen / as early as possible.
Otherwise the focus might have changed already, e.g. because of autofocus etc.

**Comment by blueyed** [comment]
I've moved the second commit (for client.swap.global_bydirection) into a separate PR: https://github.com/awesomeWM/awesome/pull/158

**Comment by blueyed** [comment]
I've amended the previous commit, and fixed it to only send the signal when the screen property gets changed.

This is untested.

**Comment by blueyed** [comment]
Rebased it on master.

**Comment by psychon** [comment]
Fine by me

**Pull request closed without merging**
