### PR TITLE
Add functional tests via Xephyr/Xvfb/xdotool

### PR DESCRIPTION
**Pull request by blueyed**
Follow-up of https://github.com/awesomeWM/awesome/pull/133

 ~~- [ ] This might make use of `busted` (more), instead of only using the custom runner.  Needs to be investigated / refactored then.~~
 - [x] Rebase/squash on master (without https://github.com/blueyed/awesome/commit/260bd9c58db767e09193da98b61ecbb3ef6f147c).

### CODE REVIEW

**Comment by blueyed** [comment]
Is the `tests` dir good for this?
Could/should it be merged with `spec/`?

**Comment by blueyed** [comment]
Adding this to the "next" milestone: I'd really like to get this into master to better check PRs in the future.

**Comment by blueyed** [comment]
@psychon 
I'd appreciate feeback on this, especially regarding the file locations and if this could be integrated / make use of busted.

**Comment by psychon** [comment]
Well, I don't think this should go to spec, since it is something else than the lua tests.

I don't really want to stare too much at this. Let's just hope that it works good enough and fix it if something breaks? :-)

**Comment by blueyed** [comment]
Ok, merged in 611438a.

btw: the existing tests would have caught #300 already..

**Comment by blueyed** [comment]
I think there should be a target in the Makefile (via CMakeLists.txt) for this.

Could `test` be made to depend on `check` and this?
While `check` does not require awesome to be built, this test runner does - so that `make test` would trigger a build, while `make check` won't.

But then there's the warning from CMake about using `test` anyway, so another target could be used for this explicitly?

> CMake Warning (dev) at CMakeLists.txt:330 (add_custom_target):
  Policy CMP0037 is not set: Target names should not be reserved and should
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

>  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.

**Pull request closed without merging**
