### PR TITLE
Add beautiful.get_merged_font; fix doc / load_font

### PR DESCRIPTION
**Pull request by blueyed**
This is meant to get a new font with adjusted attributes, e.g.

    font_focus = beautiful.get_font_copy(theme.font, "bold")

### CODE REVIEW

**Comment by psychon** [comment]
This doesn't actually add the function that the commit message claims is added. I don't have any other complaints.

**Comment by blueyed** [comment]
@psychon 
Good catch.. :)
I've renamed it after the fact.  Will add it as `get_font_copy` then, OK?

**Comment by psychon** [comment]
I liked the "merge" in the name more, because the "copy stuff" doesn't matter that much IMO. For me it seems more important that this adds some more "properties" to a font.

**Comment by blueyed** [comment]
Oh sorry, I've meant to use the `get_merged_font` actually (only the Github desc was off).
Will use it as this then.

**Pull request closed without merging**
