### PR TITLE
fix(awful: rules): don't raise every focusable client on awesome startup

### PR DESCRIPTION
**Pull request by actionless**
re: #2095

### CODE REVIEW

**Comment by psychon** [comment]
I wonder if this patch makes more sense:
```diff
diff --git a/lib/awful/ewmh.lua b/lib/awful/ewmh.lua
index 139e8e1a5..3ddb9f29f 100644
--- a/lib/awful/ewmh.lua
+++ b/lib/awful/ewmh.lua
@@ -116,7 +116,7 @@ function ewmh.activate(c, context, hints) -- luacheck: no unused args
 
     -- Minimized clients can be requested to have focus by, for example, 3rd
     -- party toolbars and they might not try to unminimize it first.
-    if ret ~= false and hints.raise then
+    if ret ~= false and hints.raise and not awesome.startup then
         c.minimized = false
     end
 
```
By the comment seen here, this is about requests sent by 3rd party toolbars, so this code should not be necessary during startup. I don't really know if this patch is better than this PR, but at least my versions feels less "magic" or "huh? why does it look at `awesome.startup`?!?" to me. What do you think?

**Comment by psychon** [comment]
But this PR is also fine with me

**Comment by Elv13** [comment]
I like @actionless version more, it has a smaller scope so is less prone to side effects like "hey, I *want* this to happen, why block me" for whatever weird use case someone comes up with.

**Comment by psychon** [comment]
Uhm, what happened to the mergify status and mergify itself?

**Comment by actionless** [comment]
@jd ping

**Pull request merged**
