### PR TITLE
fix(doc): gears.table.keys: s/integer keys/integer/

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
btw: is `#gears.table.keys(tab)` a good / recommended way to get the length of (any) table?

**Review by sclu1034 — APPROVED** [review]

**Review by Elv13 — APPROVED** [review]

**Comment by sclu1034** [comment]
> btw: is `#gears.table.keys(tab)` a good / recommended way to get the length of (any) table?

That's `O(n^4)`. Something like this would be a better option:

```lua
function gtable.count_keys(t)
    local count = 0
    for _, _ in pairs(t) do
        count = count + 1
    end
    return count
end
```

**Comment by Aire-One** [comment]
> btw: is `#gears.table.keys(tab)` a good / recommended way to get the length of (any) table?

Let's see:
`gears.table.keys` returns a table with all keys on a given table. The length of this table of keys would be the number of keys on the initial table. So, I guess, yes.

It works only because `gears.table.keys` uses `pairs` to iterate over the table keys, so it also gets keys for "non-attributes properties".

**Comment by Elv13** [comment]
@sclu1034 Can you do a PR for this?

For now I will merge this PR once the CI finishes

**Review by Aire-One — APPROVED** [review]

**Pull request merged**
