### PR TITLE
Travis: merge BUILD_APIDOC and DO_CHECKQA

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/awesomeWM/awesome/issues/1710.

Should fail now.

### CODE REVIEW

**Comment by blueyed** [comment]
Works (i.e. fails): https://travis-ci.org/awesomeWM/awesome/builds/220295560

**Comment by psychon** [comment]
:+1: thanks!

**Comment by psychon** [comment]
Should I just merge #1711 to handle that dependency?

**Comment by blueyed** [comment]
Yeah, I thought GitHub would notice that it's a single commit now and then I would have squashed it from the UI.

**Comment by psychon** [comment]
Thanks for handling this!

**Pull request closed without merging**
