### PR TITLE
Update awesomerc.lua

### PR DESCRIPTION
**Pull request by legion151**
Just a comment in rc.lua - hopefully preventing future people searching for hours.

### CODE REVIEW

**Comment by legion151** [comment]
Tried to define a rule for "Edit Event" dialog of thunderbird/lightning with a rule like
`name = "Edit Event*"` 
This worked on restarting awesome but not on opening new dialogs.
A person called pppp in irc-chan remembered he had this prob a while a go too, so i thought a comment might help to save some peoples time.

**Comment by blueyed** [comment]
@legion151 
Thanks.

@McSinyx 
What do you mean?

I was thinking that the comment might not be necessary after all, if there is another problem/bug that could be fixed instead.  (since every comment means that someone might read it, although typically not necessary).

**Comment by actionless** [comment]
i'll stick to @Elv13 , it should go to docs, not as comment

**Comment by Elv13** [comment]
I am not against, let's wait for @legion151 a bit more and do that if he/she has no time/will to further develop this concept.

The problem itself isn't new https://github.com/awesomeWM/awesome/issues/977 and more people will eventually hit it.

**Comment by actionless** [comment]
@psychon the problem described in that comment seems to happen only with web pages/apps but idk this to became a bikeshed so whatever :D

**Comment by legion151** [comment]
Sure enough - fixing the underlying problem would be a far more elegant way. Unfortunately I am not that deep into the source. Also, as far as I understand, the problem should hit all apps/applications changing or setting titles dynamically. I guess in those cases the problem cannot be fixed within awesome since the only reasonable point in the life-cycle of a window to check the rules, is on creation. Even if they can be evaluated correctly after that, no user would want the window to be changed or put away automatically after it appeared - or worse, while he is already interacting with it.

After reading the comments i would stick with @Elv13. I am one of those people who never saw that page before - sadly. However that wouldn't solve the problem that people will stumble. My research on the problem did not lead me there. 
So what about linking the documentation in the rc.lua file as a comment?

And rewrite the comment in a more general way?

**Pull request merged**
