### PR TITLE
WIP: Test runner speed

### PR DESCRIPTION
**Pull request by psychon**
This is my trying to speed up the test runner by getting of its 0.1 seconds time interval. The PR only exists so that I get a Travis build. Perhaps someone will even check if the build is faster than our current builds so that I do not have to do that? :-)
@blueyed Feel free to re-do https://github.com/awesomeWM/awesome/commit/88db9023005d7204f69469c341ed5eaf559f640a and merge it to master, or something.

P.S.: Everyone, have a happy new year.

### CODE REVIEW

**Comment by blueyed** [comment]
@psychon 
> P.S.: Everyone, have a happy new year.

Thanks!  Same for you and all awesome contributors! :)

**Comment by Elv13** [comment]
> Perhaps someone will even check if the build is faster than our current builds so that I do not have to do that? :-)

After 3 iterations (compared that with that structs PR), it doesn't seem to have a statistically significant difference, but I guess it can't hurt. Thanks for this. As proven by all the "slow event loop iterations" warnings, the time is spent mostly in the lua code (and luacov itself), not in the sleeps. Cutting the idle time can only do so much.

**Comment by blueyed** [comment]
Restarted the  build, let's see if it is really random.

**Comment by Elv13** [comment]
I restarted it a few time and it passed, the failing target isn't always the same. So yes, it is really "random" (for some "this is a race condition" definition of "random")

**Comment by psychon** [comment]
>> Feel free to re-do 88db902 and merge it to master, or something.

> What do you mean?
> Seems weird to require this?!

We have `set -e`. `((errors++))` returns the old value. So the first time this is done, the command is considered to have "failed" and `run.sh` aborts. Thus, after the first test failure, the runner aborts and following tests are not executed.
Fix: The usual (and ugly) `|| true`.

**Comment by psychon** [comment]
Superseded by #1345. There I just use a timer with timeout zero instead of doing magic with a glib idle callback.

**Comment by psychon** [comment]
Oh and: Bummer that this does not help on Travis (I guess the other PR then also does not help). Thanks for checking and sorry that I did not have the time yesterday to look into it myself! For the new PR I at least made sure that it helps on my local computer.

**Pull request closed without merging**
