### PR TITLE
Luacheck

### PR DESCRIPTION
**Pull request by psychon**
As suggested by @mindeunix [here](https://github.com/awesomeWM/awesome/pull/673#issuecomment-180891340), this adds Luacheck integration to awesome. In the process of fixing the (mostly harmless) warnings, a couple of bugs were found, e.g.:
https://github.com/awesomeWM/awesome/commit/56d19017f86b7a779f8314a3ada35614ae576364
https://github.com/awesomeWM/awesome/commit/d8ccc7cbb9cd6503d1c3766397dfd4b256a5e5f5
https://github.com/awesomeWM/awesome/commit/be44f9065a0eea6fab9a14f6673d86548215c3a9
https://github.com/awesomeWM/awesome/commit/299d8edbb5beabf9c1380a17f6882bb525477da7
https://github.com/awesomeWM/awesome/commit/f0243a4be8f37d1d86d48e6299acf6398fb7726d
https://github.com/awesomeWM/awesome/commit/6e5b520028f366745cd642f69d3bf257c1cfc5b5
https://github.com/awesomeWM/awesome/commit/562ac176f9a7aaa9300995763abbe95ca18c398f
https://github.com/awesomeWM/awesome/commit/32512b55e56f49c3c3c3369fee12bca6d3de0037
https://github.com/awesomeWM/awesome/commit/fd75af29f41777552db7d758ea70b8b567546477
https://github.com/awesomeWM/awesome/commit/6fe4582a714a79d77b7b9baecb41e0bf162731a7
(Yup, I did really tiny commits for these fixes)

I think these examples are enough to argue that running luacheck is a good thing for us.

### CODE REVIEW

**Comment by psychon** [comment]
Yay. `test-urgent.lua` is broken and this change (https://github.com/psychon/awesome/commit/cb8f6843460a6135abda52282829a72df55998f7#diff-bee6edb560243d2c841ad2ddc2b70a57L68) uncovers the brokeness...

**Comment by blueyed** [comment]
Awesome!

**Comment by psychon** [comment]
"This branch has conflicts that must be resolved" <- I'd propose that I push my "fix all of our Lua files" stuff directly to master so that these patches don't bitrot. This PR is then only about adding the actual Luacheck support. If no one complaints, I'll do the fixes and rebase soonish.

**Comment by Elv13** [comment]
> - I'd propose that I push my "fix all of our Lua files" stuff directly to master

+1, there is some good ones in that

**Comment by blueyed** [comment]
You could still have it in a/this PR for review first.
(The conflicts are likely easy to fix anyway)

The issue with the focus test is weird btw, although I have not looked into it yet.

**Comment by psychon** [comment]
Rebased on master (and cleaned up the remaining commits a bit).

This can be merged now, if no one disagrees.

**Pull request merged**
