### PR TITLE
keygrabber: Add test for multiple instance creation (#2712)

### PR DESCRIPTION
**Pull request by alfunx**
Add test for #2712 / #2741.

Putting the asserts in different step-functions didn't work, and one step-function without `count` didn't do it either. Am I missing something or is this fine?

### CODE REVIEW

**Comment by Elv13** [comment]
Thanks a lot!

For the next time it might be more scalable if it was done in 6 functions instead of an if/elseif on `count`, but this isn't important. Thanks again for writing tests for bugs I totally caused.

**Comment by Elv13** [comment]
I merged the other PR so you can rebase this on master (for the test to pass)

**Comment by alfunx** [comment]
No worries!

> For the next time it might be more scalable if it was done in 6 functions instead of an if/elseif on `count`, but this isn't important.

That's what I meant, I added a WIP commit. However the asserts fail this way, I suspect it's due to the functions being called in parallel practically (https://github.com/awesomeWM/awesome/blob/master/tests/_runner.lua#L110). Is there a nicer way of doing this?

**Comment by Elv13** [comment]
you can call `awesome.sync()` or simply check with `if` instead of `assert`. If the function returns `nil`, it will be executed again until it timeout. This helps getting rid of the race conditions. Note that using `count` doesn't mean your code is immune to races. They are just less likely because there's a longer delay. It could fail from time to time, just like this one I recently found https://github.com/awesomeWM/awesome/pull/2738/commits/68f6a567d1887e3039c2f16cabfbdeec70d7aded .

**Comment by alfunx** [comment]
Thanks, that makes sense - updated and squashed!

**Pull request merged**
