### PR TITLE
Fix function pointer casts in client.c

### PR DESCRIPTION
**Pull request by psychon**
The getters for properties already get the object as their second
argument, so there is no need to get the object again from Lua.

Fixes: https://github.com/awesomeWM/awesome/issues/2299
Signed-off-by: Uli Schlachter <psychon@znc.in>

### CODE REVIEW

**Comment by actionless** [comment]
Merge fail?

**Comment by blueyed** [comment]
Looks like "Codacy/PR Quality Review" is required and does not report?!

**Comment by Elv13** [comment]
> Would be nice to have the "Details" linked there.

https://github.com/Mergifyio/mergify-engine/issues/115

Look like we will be able to do the (saner) opposite and rebase the branch onto masted instead of merging master into the PR. This will get rid of some wierdness.

**Comment by Elv13** [comment]
I will do Mergifyio/mergify-engine#115 manually for now (git rebase -i origin master). Mergify should not try to merge master into PR, that's fragile compared to rebasing on master. And even if rebasing fails, at least you know *why*.

**Comment by alfunx** [comment]
@Elv13 It looks like you rebased master on psychon/fix-2299... ([git log](https://i.imgur.com/o0eVpxw.png))

**Comment by Elv13** [comment]
> @Elv13 It looks like you rebased master on psychon/fix-2299... (git log)

? I didn't touch `master`? I put the 4 commits on this PR above master HEAD, which was the idea. Mergify was trying to do something funny by merging master into the PR, and kept failing due to that. All I did was to undo that and rebased so it can be merged again

Unless I missed something, that git-log screenshot isn't master, but all rather pull request commits, right? I git-cloned a full copy of awesomeWM/awesome and none of the commits in you screenshots are in master. Plus, AFAIK, we have branch protection on master to prevent accidental force-push

**Comment by Elv13** [comment]
Ah nvm, I see what you mean, I misunderstood the comment as me rebasing the real master branch. Anyway, that would have merged correctly anyway, the important part was removing the part that messed mergify

**Comment by blueyed** [comment]
It's unfortunate that now also the merge-master-branch commit (that mergify created in this PR) is being merged into master.

**Comment by jd** [comment]
@blueyed @Elv13 This is only the case because you enabled strict mode. If you disable it, you won't have those merge (but you'll also be open to a small window of merging patch that only *appears* to work).

**Pull request merged**
