### PR TITLE
ci: codecov: improve flags/env

### PR DESCRIPTION
**Pull request by blueyed**
Wasn't showing up at https://codecov.io/gh/awesomeWM/awesome/commit/df9ed76418e54407d8d101b257d61fecd595b9ce/build.

### CODE REVIEW

**Comment by blueyed** [comment]
Env vars do not show up with the files though (only the job can be selected there).
So I think we should re-add the flags "lua_code" and "c_code".

**Comment by psychon** [comment]
> So I think we should re-add the flags "lua_code" and "c_code".

I may be missing something but... doesn't the file name already provide this information? If it ends with `.lua`, then it is lua code. If it ends with `.c` or `.h`, then it is C code.

**Comment by blueyed** [comment]
@psychon 
Yeah, "c_code" is not really good - that's why I've used "gcov" now for what was "c_code" before.
And all the others are "luacov" - so we have only two flags now, saying where the coverage is coming from.

**Comment by blueyed** [comment]
https://codecov.io/gh/awesomeWM/awesome/compare/df9ed76418e54407d8d101b257d61fecd595b9ce...d1b7f8993fa88faf294acca3dd2dfe0d62e3fa4d times out though again.. :/

**Comment by blueyed** [comment]
Now it worked (did not timeout).

**Comment by blueyed** [comment]
btw: we only have a single job reporting to codecov after all (with regard to duplicate comments etc).

Might pick up #2564 soon again, and then we could upload more often there also, which likely would also help to reduce the flaky coverage.

**Pull request merged**
