### PR TITLE
Fix the documentation warnings

### PR DESCRIPTION
**Pull request by Elv13**
They were added because the PRs which added those APIs predated the warnings, but were merged later.

And also fix some rendering bugs caused by the shims not behaving correctly.

### CODE REVIEW

**Comment by Elv13** [comment]
I will merge this soon because it's a doc only change and getting rid of those warning makes foxing other bugs easier

**Comment by actionless** [comment]
> They were added because the PRs which added those APIs predated the warnings, but were merged later.

mb then CI should fail on such warnings, to prevent it in the future?

**Comment by sclu1034** [comment]
> mb then CI should fail on such warnings, to prevent it in the future?

That would still not prevent such a PR from being merged, since CI runs on commit push, not on merge. Also known as "merge skew" or "semantic merge conflicts".
We'd also have to use something like GitHub's Merge Queues or [bors](https://bors.tech).

**Comment by actionless** [comment]
> runs on commit push, not on merge.

we had it before, when using Travis - but didn't moved to the current setup, idk if that was a purpose choice or just an overlook during the migration

**Comment by sclu1034** [comment]
What Travis did doesn't help here. Travis does merge the newly pushed commits into the base branch, but the crucial part is, it does it _at the time of the push_. That still doesn't cover the issue here of

1. Push to PR 1
2. CI builds PR 1
3. Push to PR 2
4. CI builds PR 2
5. Merge PR 2
6. Merge PR 1 <-- here, the result from `2.` is outdated, but there is no push to PR 1, so CI doesn't trigger again

Merge queues trigger at that `6.`. _At the time of the merge_, they first merge head and base branch into a staging area, run CI on that, and then merge into the actual target branch. And they do those in sequence, even if two PRs are triggered to merge at the same time.

**Pull request merged**
