### PR TITLE
Add c.requests_no_titlebar based on motif hints

### PR DESCRIPTION
**Pull request by psychon**
As requested/suggested in #2334

### CODE REVIEW

**Comment by psychon** [comment]
Rebased on master so that this gets the build fix from there.

**Comment by Elv13** [comment]
to bikeshed a little, I propose:

```patch
diff --git a/awesomerc.lua b/awesomerc.lua
index 94a9de95f..10994c993 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -521,10 +521,7 @@ awful.rules.rules = {
     -- @DOC_DIALOG_RULE@
     -- Add titlebars to normal clients and dialogs
     { rule_any = {type = { "normal", "dialog" }
-      -- If you want programs to be able to request no titlebars, use:
-      -- For client side decorations, clients might request no titlebars via
-      -- Motif WM hints. To honor these hints, use:
-      -- titlebars_enabled = function(c) return c.requests_no_titlebar end
+      -- @DOC_CSD_TITLEBARS@
       }, properties = { titlebars_enabled = true }
     },
 
diff --git a/docs/05-awesomerc.md.lua b/docs/05-awesomerc.md.lua
index dd336e8b5..ac56cf7d5 100644
--- a/docs/05-awesomerc.md.lua
+++ b/docs/05-awesomerc.md.lua
@@ -217,6 +217,12 @@ sections.DOC_TITLEBARS = [[
  &nbsp;
 ]]
 
+sections.DOC_CSD_TITLEBARS = [[
+ If you want programs to be able to request no titlebars, use:
+ For client side decorations, clients might request no titlebars via
+ Motif WM hints. To honor these hints, use:
+ titlebars_enabled = function(c) return c.requests_no_titlebar end
+]]
 
 sections.DOC_BORDER = [[
  &nbsp;
```

Because otherwise it would be the largest comment in `rc.lua` and it's a bit unwarranted.

**Comment by psychon** [comment]
Do you really mean
```diff
+sections.DOC_CSD_TITLEBARS = [[
+ If you want programs to be able to request no titlebars, use:
+ For client side decorations, clients might request no titlebars via
+ Motif WM hints. To honor these hints, use:
+ `titlebars_enabled = function(c) return c.requests_no_titlebar end`
+ 
+ See `client.requests_no_titlebar` for more details.
+]]
```
or do you rather mean this (one line removed)?
```diff
+sections.DOC_CSD_TITLEBARS = [[
+ For client side decorations, clients might request no titlebars via
+ Motif WM hints. To honor these hints, use:
+ `titlebars_enabled = function(c) return c.requests_no_titlebar end`
+ 
+ See `client.requests_no_titlebar` for more details.
+]]
```

**Comment by Elv13** [comment]
oops, copy/paste mistake.

**Comment by psychon** [comment]
Okay, as you wish. Added as a new commit.
foo

**Comment by Elv13** [comment]
thanks

**Pull request merged**
