### PR TITLE
Add some (busted) unit tests for systray and fix #2981

### LINKED ISSUE #2981: systray doesn't respect margin container
Output of `awesome --version`:

awesome v4.3-687-gb350ffcb9-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

add systray inside of margin container. same problem occured in "normal" lua version

**Actual result:**
margin containers right side doesn't stretch to fit around systray, ovrelaps to over widget right of it.

image with visible margins: https://i.ibb.co/swKBBTw/margin.png

**Expected result:**

container fits around systray

### PR DESCRIPTION
**Pull request by psychon**
While trying to fix #2981, I felt like this needs some tests. This is what I ended up with.

### CODE REVIEW

**Comment by psychon** [comment]
Uhm. The "test intermediate commits"-magic failed when testing the first commit of this. Error is:
```
[ 68%] Generating API documentation (fatal warnings)
reading configuration from config.ld
found master module	/home/travis/build/awesomeWM/awesome/build/luaa.c
found master module	/home/travis/build/awesomeWM/awesome/build/luaa.c
found master module	/home/travis/build/awesomeWM/awesome/build/objects/client.c
/home/travis/build/awesomeWM/awesome/build/lib/awful/keyboard.lua:10: ?: unknown tag: 'inputmodule' nil
/home/travis/build/awesomeWM/awesome/build/lib/awful/keyboard.lua:1: contains no items
found master module	/home/travis/build/awesomeWM/awesome/build/lib/awful/layout/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/awful/layout/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/awful/layout/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/awful/layout/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/awful/layout/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/awful/layout/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/awful/layout/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/awful/layout/init.lua
/home/travis/build/awesomeWM/awesome/build/lib/awful/mouse/client.lua:21: ?: unknown tag: 'request' nil
/home/travis/build/awesomeWM/awesome/build/lib/awful/mouse/client.lua:106: ?: unknown tag: 'request' nil
found master module	/home/travis/build/awesomeWM/awesome/build/mouse.c
/home/travis/build/awesomeWM/awesome/build/lib/awful/permissions/init.lua:604: ?: unknown tag: 'usebeautiful' nil
found master module	/home/travis/build/awesomeWM/awesome/build/root.c
found master module	/home/travis/build/awesomeWM/awesome/build/objects/screen.c
/home/travis/build/awesomeWM/awesome/build/lib/awful/screen/dpi.lua:1: contains no items
found master module	/home/travis/build/awesomeWM/awesome/build/objects/tag.c
found master module	/home/travis/build/awesomeWM/awesome/build/lib/beautiful/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/beautiful/init.lua
found master module	/home/travis/build/awesomeWM/awesome/build/lib/naughty/core.lua
/home/travis/build/awesomeWM/awesome/build/lib/ruled/client.lua:238: ?: unknown tag: 'ruleslib' nil
/home/travis/build/awesomeWM/awesome/build/lib/ruled/client.lua:1: contains no items
/home/travis/build/awesomeWM/awesome/build/lib/ruled/init.lua:4: no module() call found; no initial doc comment
/home/travis/build/awesomeWM/awesome/build/lib/ruled/client.lua:3: function not found: rules in this module rules
output written to /home/travis/build/awesomeWM/awesome/build/doc
CMakeFiles/ldoc.dir/build.make:284: recipe for target 'doc/index.html' failed
```
I'd say "that wasn't me". No idea what is going on here... Well, okay, random guess: I still have my ancient git checkout here. At first, Travis tested a merge between git/master and this PR. That succeeded. Then it tried to test only my first commit, thus going back to my ancient version of git/master. However, the first build left behind some stuff that now caused this to fail...?

**Comment by actionless** [comment]
regarding travis failure, mb it require rebasing on the latest master?

**Comment by Elv13** [comment]
@psychon Travis cherry picks commits. It starts with whatever would happen if the PR was merged, thus in this scenario, `@ruleslib` exists. Then it cherry pick the older commit, where `@ruleslib` does not yet exist. Because the build dir is dirty, then `$build/lib/ruled` is still there. Then `ldoc` catch it in the RegEx, then you get this error.

Is there any reason/bug why you don't just git-rebase your install to `master`?

**Comment by psychon** [comment]
> Is there any reason/bug why you don't just git-rebase your install to master?

Time. I expect stuff to break and then need to investigate. Also, my current git/master points to where I stopped looking carefully at commits. I still have the idea that I go through everything that was merged since then and see if I spot anything obviously wrong. However, the longer I wait with this, the more stuff there is to look at and the less I want to take the time to look at this... (my master is dc98eade3b080e66c910be98b61c1ec4228df9c6 which is four months ago)

**Comment by psychon** [comment]
Rebased on master

**Pull request merged**
