### PR TITLE
chore(travis): add lua 5.4-based env

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by Elv13** [comment]
Is there a way to allow this one to fail until we are ready to support Lua 5.4?

**Comment by psychon** [comment]
Yes, but I do not know how the specific text for this case would look like: https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail

However, what's the point? lgi will fail to build and that makes the resulting build output not really interesting.

**Comment by Elv13** [comment]
> However, what's the point? lgi will fail to build and that makes the resulting build output not really interesting.

I know, I did a small test in docker just for fun and it indeed doesn't work. I will probably have some time next weekend for Awesome related stuff. I might take a look (or actually finish the PR I was working on in March when my schedule was turned upside down with COVID)

**Comment by psychon** [comment]
LGI git/master should at least build against Lua 5.4: https://github.com/pavouk/lgi/pull/249

If wanted, this could be used for making progress on this PR and figuring out how much of awesomeWM breaks with Lua 5.4.

**Comment by actionless** [comment]
@psychon it seems too old cmake version couldn't find lua 5.4:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4959

**Comment by psychon** [comment]
```
-- Could NOT find Lua (missing: LUA_INCLUDE_DIR) 
CMake Error at awesomeConfig.cmake:68 (message):
  Could not find Lua.  See the error above.

  You might want to hint it using the LUA_DIR environment variable, or set
  the LUA_INCLUDE_DIR / LUA_LIBRARY CMake variables.
```
Hm... If I understand that correctly, `-DLUA_INCLUDE_DIR=/usr/include/lua5.4 -DLUA_LIBRARY=/usr/lib/liblua.so` should do the trick. Reading a bit the code in `FindLua.cmake` a bit, `-DLua_FIND_VERSION=5.4` could also help.

**Comment by psychon** [comment]
Got it to work. I 'installed' Lua via
```sh
(cd src && make SYSCFLAGS="-DLUA_USE_LINUX -ULUA_COMPAT_5_2 -DLUA_USE_APICHECK" SYSLIBS="-Wl,-E -ldl -lreadline" LUA_A=liblua.so MYCFLAGS="-fPIC" RANLIB=: AR="gcc -shared -ldl -o" liblua.so && make linux)              
make INSTALL_TOP=/tmp/lua-inst/ TO_LIB=liblua.so linux install 
```
Then I built awesome with
```sh
mkdir build
cd build
cmake .. -D LUA_LIBRARY=/tmp/lua-inst/lib/liblua.so -D LUA_INCLUDE_DIR=/tmp/lua-inst/include/ -D Lua_FIND_VERSION=5.4 -D Lua_FIND_VERSION_MAJOR=5 -D Lua_FIND_VERSION_MINOR=4
```
The actual build then failed with "undefined reference to dlopen". I hacked around that with the following (which should not be needed on Travis since hopefully that builds `liblua.so` correctly so that it links against `libdl`). `LUA_Debug` helped in making the previous command work.
```diff
diff --git a/awesomeConfig.cmake b/awesomeConfig.cmake
index 5e341abc7..0b1d00453 100644
--- a/awesomeConfig.cmake
+++ b/awesomeConfig.cmake
@@ -63,6 +63,7 @@ a_find_program(CONVERT_EXECUTABLE convert TRUE)
 # pkg-config
 include(FindPkgConfig)
 # lua
+set(LUA_Debug 1)
 include(FindLua)
 if (NOT LUA_FOUND)
     message(FATAL_ERROR
@@ -70,6 +71,7 @@ if (NOT LUA_FOUND)
         "You might want to hint it using the LUA_DIR environment variable, "
         "or set the LUA_INCLUDE_DIR / LUA_LIBRARY CMake variables.")
 endif()
+SET(LUA_LIBRARIES "${LUA_LIBRARIES};dl")
 # }}}
 
 # {{{ Check if documentation can be build
```
The result:
```
$ ./awesome --version
awesome v4.3-809-g5d1394b91-dirty (Too long)
 • Compiled against Lua 5.4.0 (running with Lua 5.4)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: [string "return require('lgi.version')"]:1: module 'lgi.version' not found:
	no field package.preload['lgi.version']
	no file '/usr/local/share/lua/5.4/lgi/version.lua'
	no file '/usr/local/share/lua/5.4/lgi/version/init.lua'
	no file '/usr/local/lib/lua/5.4/lgi/version.lua'
	no file '/usr/local/lib/lua/5.4/lgi/version/init.lua'
	no file './lgi/version.lua'
	no file './lgi/version/init.lua'
	no file '/usr/local/lib/lua/5.4/lgi/version.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './lgi/version.so'
	no file '/usr/local/lib/lua/5.4/lgi.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './lgi.so'
 • Transparency enabled: yes
 • Custom search paths: no
```

**Comment by psychon** [comment]
Heh. To quote myself:
>  (which should not be needed on Travis since hopefully that builds liblua.so correctly so that it links against libdl).

To quote Travis:
```
[  0%] Linking C executable lgi-check
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblua.so: undefined reference to `dlopen'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblua.so: undefined reference to `dlclos
```

**Comment by actionless** [comment]
still can't get something right :(

**Comment by psychon** [comment]
I hacked something together. Since I cannot push patches to your PR, I created a new branch. I started by partially reverting b67e0a123cb2c013f6b4665cb6030717a1463422 and then working from there (so I did not use that Lua patch that you used). The key to getting Lua to build was to build it in two steps. I build a `liblua.so` like you do, but I let the Lua interpreter be statically linked (this seems to be necessary since it uses non-public API of Lua).
The branch: https://github.com/awesomeWM/awesome/tree/lua54 (I wanted to push it to my fork, but I mistyped and here we are).
The latest Travis build: https://travis-ci.com/github/awesomeWM/awesome/builds/178282775
The build runs until it tries to run tests:
```
== Running /home/travis/build/awesomeWM/awesome/tests/test-awesomerc.lua ==
Error: failed to wait for awesome startup via awesome-client!
Last reply: Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.awesomewm.awful was not provided by any .service files.
Log:
2020-08-03 15:58:58 W: awesome: luaA_panic:854: unprotected error in call to Lua API (bad argument #1 to 'math.randomseed' (number has no integer representation))
2020-08-03 15:58:58 W: awesome: luaA_panic:857: dumping backtrace
/home/travis/build/awesomeWM/awesome/build/awesome(backtrace_get+0x54) [0x425267]
/home/travis/build/awesomeWM/awesome/build/awesome() [0x418def]
/usr/lib/liblua.so(+0x11f42) [0x7fb50910bf42]
/usr/lib/liblua.so(+0x11578) [0x7fb50910b578]
/usr/lib/liblua.so(+0xc74d) [0x7fb50910674d]
/usr/lib/liblua.so(luaL_error+0xc4) [0x7fb509125114]
/usr/lib/liblua.so(luaL_argerror+0x88) [0x7fb5091251c8]
/usr/lib/liblua.so(luaL_checkinteger+0x91) [0x7fb509125ff1]
/usr/lib/liblua.so(+0x31433) [0x7fb50912b433]
/usr/lib/liblua.so(+0x131e2) [0x7fb50910d1e2]
/usr/lib/liblua.so(+0x134ac) [0x7fb50910d4ac]
/usr/lib/liblua.so(lua_callk+0x8f) [0x7fb509105d3f]
/home/travis/build/awesomeWM/awesome/build/awesome(main+0xe9a) [0x410fbe]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fb508b04830]
/home/travis/build/awesomeWM/awesome/build/awesome(_start+0x29) [0x40f9f9]
2020-08-03 15:58:58 W: awesome: luaA_panic:858: restarting awesome
```
That panic does not seem to hard to fix.... In fact, I just cherry-picked #3124 into that branch.

Anyone wants to continue on this? My time for this week should be over soon. I'll continue playing with this a bit for today, but then anyone else can pick this up (and you do not have to credit me for this Travis shell script stuff).

**Comment by actionless** [comment]
@psychon thanks! then i'm closing this in favor of lua54 branch

**Pull request closed without merging**
