### PR TITLE
lua: Use pushinteger for int type

### LINKED ISSUE #238: os.setlocale(os.getenv("LANG")) in lua 5.3 with LANG = pl_PL.UTF-8 cause errors
I have arch linux - and now the latest lua version is 5.3, in lua 5.2.5 the same rc.lua have worked fine...

I find that line: os.setlocale(os.getenv("LANG"))
with:
echo $LANG
pl_PL.UTF-8 
Cause a lot of errors: https://bugs.archlinux.org/task/45008?getfile=13052

it seem similar to:
https://github.com/awesomeWM/awesome/issues/75
http://comments.gmane.org/gmane.comp.window-managers.awesome/8950

I also reported this bug on archlinux bugs: https://bugs.archlinux.org/task/45008#comment135576

### PR DESCRIPTION
**Pull request by Elv13**
Attempt to fix #238 

This is a contribution from someone on IRC, but using an anonymous email, so I will commit with my account. I tested on lua 5.1 and luajit. This has been reported to work in 5.3

### CODE REVIEW

**Comment by salorium** [comment]
It ok, good, thank you :+1:

**Comment by psychon** [comment]
:+1:

**Comment by Elv13** [comment]
So, do we merge that?

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
