### PR TITLE
Improve floating movetoscreen

### PR DESCRIPTION
**Pull request by blueyed**
This contains a fix and an improvement:

1. handle fullscreen/maximized clients properly: skip storing some properties for them
2. save floating property per screen: this allows to position the client differently per screen, and fixes moving it around on different screen sizes

The issue with 2. is that the client first appears at the "fixed" position and then gets moved to the old one.
I guess this could be fixed by really redrawing clients only once per main loop?

### CODE REVIEW

**Comment by Elv13** [comment]
Can this be closed?

**Comment by Elv13** [comment]
Closing for lack of activity, re-open when needed

**Comment by blueyed** [comment]
@actionless 
> nice

Thanks!  Please consider finishing it.. :)

**Comment by actionless** [comment]
@Elv13 what do you think, can restoring the windows (pt.2 from original description) could be implemented as `awful.placement.restore_floating`?

**Pull request closed without merging**
