### PR TITLE
test(awful: hotkeys_popup): add a minimal test

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by actionless** [comment]
the tests were passing unless i added a string with comments and amended.. :nauseated_face: 
https://travis-ci.org/awesomeWM/awesome/jobs/198638180#L2748

**Comment by actionless** [comment]
here are two passing ones:
https://travis-ci.org/awesomeWM/awesome/builds/198628848
https://travis-ci.org/awesomeWM/awesome/builds/198629188

i can't get what's wrong

**Comment by Elv13** [comment]
I can reproduce the error locally and it's caused by the commit

**Comment by actionless** [comment]
i think found -- i had to do key_release after key_pres, waiting for the travis now

**Comment by Elv13** [comment]
You know, you can run these locally. Run execute the `run.sh`, as long as you have Xephyr, it will run.

**Comment by Elv13** [comment]
Thanks for this, finally 80%! Now the last anchor dragging the tests are the menubar (poke @Crazylemon64 😈 )

**Pull request merged**
