### PR TITLE
awful.screen: Fix regression

### PR DESCRIPTION
**Pull request by Elv13**
a missing `capi.`

### CODE REVIEW

**Comment by psychon** [comment]
Sorry for missing that... but why is it a regression? The original `screen` should still be available in the global env...

Anyway: The same issue exists in this file in the `get_screen` function and the function you are fixing does `screen[i]` a few lines down. Could you fix both of these as well in this PR?

**Comment by Elv13** [comment]
> The original screen should still be available in the global env...

`local screen = {}` nope ;)

**Comment by Elv13** [comment]
Updated, ready?

**Comment by psychon** [comment]
Sounds like we need more multi-monitor tests on Travis... Yup, looks fine.

**Pull request merged**
