### PR TITLE
Fix missing workarea updates with client struts

### LINKED ISSUE #1335: Docking windows affects other tags
Output of `awesome --version`:

    awesome devel (Harder, Better, Faster, Stronger)
     • Compiled against Lua 5.2.3 (running with Lua 5.2)
     • D-Bus support: ✔
     • execinfo support: ✔
     • RandR 1.5 support: ✔
     • LGI version: 0.7.2

(Build from current master branch)

**How to reproduce the issue:**

* make window dockable on tag 2
* dock window on tag 2
* switch to tag 1
* open window there

**Actual result:**

* the window ignores the spaces taken up by a docked window on tag 2

**Expected result:**

* The fact that something is docked on tag 2 doesn't affect tag 1 at all

**Note:**
I'm not really sure that my idea of what should happen is correct but the current behaviour seems strange to me.

### PR DESCRIPTION
**Pull request by psychon**
This fixes #1335 and all other, similar issues that I could find. The `TEST_PREV_COMMITS=1` build will fail, but I cannot really do much about it, I guess. My commits are small and each one fixes some partial bug.

### CODE REVIEW

**Comment by Elv13** [comment]
Coverall seems MIA. Beside that 👍

**Comment by blueyed** [comment]
> The `TEST_PREV_COMMITS=1` build will fail, but I cannot really do much about it, I guess. My commits are small and each one fixes some partial bug.

Hmm, but it could be fixed by squashing the fixes and the changed test?!

**Comment by blueyed** [comment]
@Elv13 
> MIA

Please elaborate.

**Comment by Elv13** [comment]
> Please elaborate.

It is not in the "check" section. Chances are it crashed on their cloud and we have nothing to do about it. I just noticed it wasn't listed. I restarted the build, lets see how this goes.

**Comment by Elv13** [comment]
Still missing (I don't see how this PR could have broken it, but other PRs from today have it, so it isn't a breakage that's already introduced in `master`)

**Pull request merged**
