### PR TITLE
Fix Error while drawing widget

### PR DESCRIPTION
**Pull request by salorium**
I'm error :
```
Error while drawing widget: /usr/share/awesome/lib/wibox/widget/systray.lua:48: bad argument #2 to 'systray' (number has no integer representation)
```
I am looking : /usr/share/awesome/lib/wibox/widget/systray.lua:48 and i am printing x and y
```
function systray:draw(wibox, cr, width, height)
    local x, y, _, _ = lbase.rect_to_device_geometry(cr, 0, 0, width, height)
    local num_entries = capi.awesome.systray()
    local bg = beautiful.bg_systray or beautiful.bg_normal or "#000000"
    local spacing = beautiful.systray_icon_spacing or 0

    -- Figure out if the cairo context is rotated
    local dir_x, dir_y = cr:user_to_device_distance(1, 0)
    local is_rotated = abs(dir_x) < abs(dir_y)

    local in_dir, ortho, base
    if horizontal then
        in_dir, ortho = width, height
        is_rotated = not is_rotated
    else
        ortho, in_dir = width, height
    end
    if ortho * num_entries <= in_dir then
        base = ortho
    else
        base = in_dir / num_entries
    end
    print(x)
    print(y)
    capi.awesome.systray(wibox.drawin, x, y, base, is_rotated, bg, reverse, spacing)
end
```
Result :
```
948,88888888889
0.0
Error while drawing widget: /usr/share/awesome/lib/wibox/widget/systray.lua:48: bad argument #2 to 'systray' (number has no integer representation)
```
I am patching :
```
function systray:draw(wibox, cr, width, height)
    local x, y, _, _ = lbase.rect_to_device_geometry(cr, 0, 0, width, height)
    local num_entries = capi.awesome.systray()
    local bg = beautiful.bg_systray or beautiful.bg_normal or "#000000"
    local spacing = beautiful.systray_icon_spacing or 0

    -- Figure out if the cairo context is rotated
    local dir_x, dir_y = cr:user_to_device_distance(1,
    print()
    print(x)
    print(math.ceil(y))
    print(y)0)
    local is_rotated = abs(dir_x) < abs(dir_y)

    local in_dir, ortho, base
    if horizontal then
        in_dir, ortho = width, height
        is_rotated = not is_rotated
    else
        ortho, in_dir = width, height
    end
    if ortho * num_entries <= in_dir then
        base = ortho
    else
        base = in_dir / num_entries
    end
    capi.awesome.systray(wibox.drawin, math.ceil(x), math.ceil(y), base, is_rotated, bg, reverse, spacing)
end
```

### CODE REVIEW

**Comment by Elv13** [comment]
Hello,. thanks for this, can you check the `type()` of `x` and `y`? If one of them is string, then there is also a problem elsewhere that has to be fixed first.

**Comment by salorium** [comment]
Result type() of x and y : 

    number
    number
    Error while drawing widget: /usr/share/awesome/lib/wibox/widget/systray.lua:48: bad argument #2 to 'systray' (number has no integer representation)

**Comment by Elv13** [comment]
Ok... One has a `.` and the other a `,`... There is something really wrong with that. In no one has an objection, I will merge this PR, but I still think there is something else hidden under this.

**Comment by blueyed** [comment]
> One has a . and the other a ,

Is this maybe another case of the locale having an influence?

It seems to come from `lbase.rect_to_device_geometry`, right?

Which is:

    --- Figure out the geometry in device coordinate space. This gives only tight
    -- bounds if no rotations by non-multiples of 90° are used.
    function base.rect_to_device_geometry(cr, x, y, width, height)
        local x1, y1 = cr:user_to_device(x, y)
        local x2, y2 = cr:user_to_device(x, y + height)
        local x3, y3 = cr:user_to_device(x + width, y + height)
        local x4, y4 = cr:user_to_device(x + width, y)
        local x = min(x1, x2, x3, x4)
        local y = min(y1, y2, y3, y4)
        local width = max(x1, x2, x3, x4) - x
        local height = max(y1, y2, y3, y4) - y

        return x, y, width, height
    end

@salorium 
Are you using a non-default locale currently?
Does it have an influence?

Can you add more print-debugging to `rect_to_device_geometry` (`lib/wibox/layout/base.lua.in`).

**Comment by salorium** [comment]
I am use a locale, if i am disabled my locale, i have always the bug

    function base.rect_to_device_geometry(cr, x, y, width, height)
    print("Type (cr)"..type(cr))
    print("Type (x)"..type(x).." value =>"..x)
    print("Type (y)"..type(y).." value =>"..y)
    print("Type (width)"..type(width).." value =>"..width)
    print("Type (height)"..type(height).." value =>"..height)
    local x1, y1 = cr:user_to_device(x, y)
    local x2, y2 = cr:user_to_device(x, y + height)
    local x3, y3 = cr:user_to_device(x + width, y + height)
    local x4, y4 = cr:user_to_device(x + width, y)
    print("x1 => "..x1.." y1 => "..y1)
    print("x2 => "..x2.." y2 => "..y2)
    print("x3 => "..x3.." y3 => "..y3)
    print("x4 => "..x4.." y4 => "..y4)
    local x = min(x1, x2, x3, x4)
    local y = min(y1, y2, y3, y4)
    print("x => "..x.." y => "..y)
    local width = max(x1, x2, x3, x4) - x
    local height = max(y1, y2, y3, y4) - y

    return x, y, width, height
    end

Result : 

    Type (cr)userdata
    Type (x)number value =>0
    Type (y)number value =>0
    Type (width)number value =>0
    Type (height)number value =>22.0
    x1 => 1040.2345679012 y1 => 0.0
    x2 => 1040.2345679012 y2 => 22.0
    x3 => 1040.2345679012 y3 => 22.0
    x4 => 1040.2345679012 y4 => 0.0 
    x => 1040.2345679012 y => 0.0
    1040.2345679012
    0.0
    Error while drawing widget: /usr/share/awesome/lib/wibox/widget/systray.lua:48: bad argument #2 to 'systray' (number has no integer representation)

**Comment by Elv13** [comment]
Last call, I will merge this is nobody else have a better idea.

**Comment by salorium** [comment]
What is the return of the function cr:user_to_device ? (int or float)

**Comment by blueyed** [comment]
The line number does not match the place where you replaced it (48): /usr/share/awesome/lib/wibox/widget/systray.lua:48 (in the initial report)

It mentions the name where `capi.awesome.systray()` is called, doesn't it?

    function systray:fit(width, height)
        local num_entries = capi.awesome.systray()


@salorium 
> What is the return of the function cr:user_to_device ? (int or float)

Should be a float, but I've only quickly grepped the lgi source:

    lgi/override/cairo.lua
    287:	 user_to_device = { { ti.double, dir = 'inout' },
    288-			    { ti.double, dir = 'inout' } },

From your last post it looks like it also happens with a "proper" float (using a dot)?

> I am use a locale, if i am disabled my locale, i have always the bug

I don't understand this.
Was the above / last printed without a specific locale?
Does it happen with both your locale (which) and without?

**Comment by salorium** [comment]
> It mentions the name where capi.awesome.systray() is called, doesn't it?

No
```
capi.awesome.systray(wibox.drawin, x, y, base, is_rotated, bg, reverse, spacing)
```

> Was the above / last printed without a specific locale?

No 

> Does it happen with both your locale (which) and without?

Yes

I am testing : 
```lua
function systray:draw(wibox, cr, width, height)
    local x, y, _, _ = lbase.rect_to_device_geometry(cr, 0, 0, width, height)
    local num_entries = capi.awesome.systray()
    local bg = beautiful.bg_systray or beautiful.bg_normal or "#000000"
    local spacing = beautiful.systray_icon_spacing or 0

    -- Figure out if the cairo context is rotated
    local dir_x, dir_y = cr:user_to_device_distance(1, 0)
    local is_rotated = abs(dir_x) < abs(dir_y)

    local in_dir, ortho, base
    if horizontal then
        in_dir, ortho = width, height
        is_rotated = not is_rotated
    else
        ortho, in_dir = width, height
    end
    if ortho * num_entries <= in_dir then
        base = ortho
    else
        base = in_dir / num_entries
    end
--    print(math.ceil(x))
    print(x)
--    print(math.ceil(y))
    print(y)
    y = y + 0.1 --produce the bug
    print(y)
    capi.awesome.systray(wibox.drawin, x, y, base, is_rotated, bg, reverse, spacing)
end

```

Result : 
```
848.0
0.0
0.1
Error while drawing widget: /usr/share/awesome/lib/wibox/widget/systray.lua:50: bad argument #3 to 'systray' (number has no integer representation)
```

comment out `y = y + 0.1 --produce the bug` : 
```lua
function systray:draw(wibox, cr, width, height)
    local x, y, _, _ = lbase.rect_to_device_geometry(cr, 0, 0, width, height)
    local num_entries = capi.awesome.systray()
    local bg = beautiful.bg_systray or beautiful.bg_normal or "#000000"
    local spacing = beautiful.systray_icon_spacing or 0

    -- Figure out if the cairo context is rotated
    local dir_x, dir_y = cr:user_to_device_distance(1, 0)
    local is_rotated = abs(dir_x) < abs(dir_y)

    local in_dir, ortho, base
    if horizontal then
        in_dir, ortho = width, height
        is_rotated = not is_rotated
    else
        ortho, in_dir = width, height
    end
    if ortho * num_entries <= in_dir then
        base = ortho
    else
        base = in_dir / num_entries
    end
--    print(math.ceil(x))
    print(x)
--    print(math.ceil(y))
    print(y)
--    y = y + 0.1 --produce the bug
    print(y)
    capi.awesome.systray(wibox.drawin, x, y, base, is_rotated, bg, reverse, spacing)
end
```

Result
```
848.0
0.0
0.0
```
I dont have a bug :+1: 

if x or y is decimal (1.01; 1.25 etc), then the bug occurs.
if x or y is number (1 ; 2.0 etc ), then there is no bug.

Sorry for my english, i'm french

**Comment by blueyed** [comment]
Hmm, it seems to have been some corner case then initially (where the bug happened for you).

Do you use different screen setups (which might have an influence)?

Anyway, I think the fix it to use `math.floor` in rect_to_device_geometry, like this: https://github.com/awesomeWM/awesome/compare/master...blueyed:floor-with-rect_to_device_geometry

**Comment by salorium** [comment]
>Do you use different screen setups (which might have an influence)?

Yes 
```zsh
Xephyr :1 -ac -br -noreset -screen 1280x720 & // Bugs
Xephyr :1 -ac -br -noreset -screen 1680x1050 & //Bugs
Xephyr :1 -ac -br -noreset -screen 1440x900 &  //Bugs
1920x1080 my screen //Bugs
```
> Anyway, I think the fix it to use math.floor in rect_to_device_geometry, like this: 
https://github.com/awesomeWM/awesome/compare/master...blueyed:floor-with-rect_to_device_geometry

Good :+1:  
Thank you !

**Comment by blueyed** [comment]
Thanks for the report and the help with debugging this!

I am closing this PR in favour of #250.

**Comment by psychon** [comment]
I guess I'd prefer this one (if it also rounds the base size (or someone tells me that this is not necessary)).

**Comment by blueyed** [comment]
Reopening.

@salorium 
Can you check if `base` needs to be rounded, too?

And shouldn't it use `floor` instead?

**Comment by salorium** [comment]
> Can you check if base needs to be rounded, too?
> And shouldn't it use floor instead?

I do not know where to look


I found it, I do not know if this can serve `systray.c:L316-L324` : 
```c
        drawin_t *w = luaA_checkudata(L, 1, &drawin_class);
        int x = luaL_checkinteger(L, 2);
        int y = luaL_checkinteger(L, 3);
        int base_size = luaL_checkinteger(L, 4);
        bool horiz = lua_toboolean(L, 5);
        const char *bg = luaL_checklstring(L, 6, &bg_len);
        bool revers = lua_toboolean(L, 7);
        int spacing = luaL_checkinteger(L, 8);
        color_t bg_color;
```

**Comment by salorium** [comment]
No news?

**Comment by blueyed** [comment]
@salorium 
We were referring to the `base` argument (which can be seen in your commit's diff).

As for `math.ceil` vs. `math.floor`, I still think it should be `math.floor` to "round" it downwards, not upwards.

**Comment by Elv13** [comment]
well, the advantage of `ceil` is that the widget actually have enough space, with `floor`, it will be too small and this could cause rendering side effects like `...`  with pango. Maybe not with the systray, but overall, I would favor `ceil`

**Comment by blueyed** [comment]
@Elv13 
Makes sense.  Thanks for clarifying!

**Comment by blueyed** [comment]
Thanks!
Merged / cherry-picked.

I've edited the commit message, and wrapped the line.

If it's needed for `base` also, this can be fixed still later.

**Pull request closed without merging**
