### PR TITLE
Add code coverage support

### PR DESCRIPTION
**Pull request by psychon**
Having messed up https://github.com/awesomeWM/awesome/pull/673 badly, here is a new attempt that makes me look less stupid:

This runs the unit and functional tests under LuaCov and uploads the results to coveralls.io. This service provides web access to the coverage information and shows the coverage change on any PR.

### CODE REVIEW

**Comment by psychon** [comment]
Updated for @blueyed's suggestions from https://github.com/psychon/awesome/commit/e8494fd5cfb8796766391da6a93d166cae1fcebd.
Apparently the new `test-leak-client.lua`-test fails when run under LuaCov. I will have to investigate this, but not today (at least I already know that this can be reproduced locally).

**Comment by blueyed** [comment]
Have you also considered codecov.io?

**Comment by psychon** [comment]
@blueyed My approach was "Oh, https://github.com/moteus/luacov-coveralls looks shiny, let's use that". So no, I haven't really considered anything. Does anyone know about a good way to find alternative projects that take output from LuaCov and upload that somewhere useful? (If we don't find anything like that, then coveralls.io wins because there are no alternatives :-) )

**Comment by psychon** [comment]
I fixed the test failure (and rebased this on master). The problem was that the wibox wasn't updated yet when the leak check was run and thus the tasklist prevented garbage collection of the client.

**Pull request merged**
