### PR TITLE
Travis: try dist=trusty

### PR DESCRIPTION
**Pull request by blueyed**
http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/

### CODE REVIEW

**Comment by blueyed** [comment]
No cmake by default?!

`cmake --version` fails.

**Comment by blueyed** [comment]
We still need to build CMake:

> CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
> CMake 3.0.0 or higher is required.  You are running version 2.8.12.2

**Comment by blueyed** [comment]
For reference, cmake is likely to be available by default (but probably too old): https://github.com/travis-infrastructure/packer-templates/issues/42

**Comment by blueyed** [comment]
Should be good for now, but could be cleaned up more.

**Comment by psychon** [comment]
@coveralls Huh?!?!?

**Pull request closed without merging**
