### PR TITLE
Add a textbox widget that shows the output of a command and updates it

### PR DESCRIPTION
**Pull request by b80905**

### CODE REVIEW

**Comment by actionless** [comment]
idea itself is nice, but can it be async?

**Comment by blueyed** [comment]
See https://github.com/Elv13/awesome-configs/blob/master/utils/fd_async.lua for @Elv13's async lib.
I think it would be great to get this into awesome first.

**Comment by actionless** [comment]
@blueyed on my config it segfaults awesome when doing a nested async call

**Comment by actionless** [comment]
@b80905 are you going to re-open it?
otherwise i can take it

**Comment by b80905** [comment]
@actionless, no, you can take it.

**Pull request closed without merging**
