### PR TITLE
More gears.table tests

### PR DESCRIPTION
**Pull request by SethBarberee**
Slowly working on #2869 but ended up doing these simple tests first to help... learning to write these in order to test iterate_value correctly

* Added tests for gears.table.hasitem and gears.table.find_keys

### CODE REVIEW

**Comment by Elv13** [comment]
Thanks a lot for this. 

The current build fails because of : 

    spec/gears/table_spec.lua:48:54: unused argument 'v'

**Comment by SethBarberee** [comment]
> Thanks a lot for this.
> 
> The current build fails because of :
> 
> ```
> spec/gears/table_spec.lua:48:54: unused argument 'v'
> ```

Fixed that right up. Thanks for the review.

**Comment by Elv13** [comment]
Thanks. Can you squash all commits? Right now there is a revert and a fixup. To get merged, all commits have to pass the test. If they didn't that would break our ability to git-bisect the code.

If that's too much work, I can do it "soon".

**Comment by SethBarberee** [comment]
> Thanks. Can you squash all commits? Right now there is a revert and a fixup. To get merged, all commits have to pass the test. If they didn't that would break our ability to git-bisect the code.
> 
> If that's too much work, I can do it "soon".

Done.

**Pull request merged**
