### PR TITLE
Fix background of transparent systray icons. (#2449)

### PR DESCRIPTION
**Pull request by petoju**
Fixes background, that was not refreshed before and is refreshed and stable with this patch.

### CODE REVIEW

**Comment by petoju** [comment]
Hmm, so I just noticed this works almost all the time, but it stops working when the applet shows context menu after my rightclick.
I will try to fix that tomorrow.

**Comment by psychon** [comment]
What's the story behind this patch? How did you come up with it and which specs say you should do stuff like this?

According to the specs that I know, systray icons should set their background to `XCB_BACK_PIXMAP_PARENT_RELATIVE`, meaning they get the background of their parent window applied. Awesome then sets the background of this parent window (the systray container window) to whatever is needed in `luaA_systray`. Thus... I would expect that this patch does not make any difference.

Also, your patch says that this provides systray icons with transparent background with the correct background. However, it just changes the background of all systray icons. I bet I could come up with an example program that e.g. just sets a solid green background. Your patch would then break this and make the icon disappear.

**Comment by psychon** [comment]
Also, what did you test this with? Some GTK- or Qt- using app? Something that uses its own systray implementation? What is it specifically?

**Comment by petoju** [comment]
> What's the story behind this patch? How did you come up with it and which specs say you should do stuff like this?

Transparent background of GTK systray icons stopped working after upgrading to newer Ubuntu, so I just tried to find a fix and this one was the obvious one. I don't know XCB nor X specs.

> According to the specs that I know, systray icons should set their background to `XCB_BACK_PIXMAP_PARENT_RELATIVE`, meaning they get the background of their parent window applied. Awesome then sets the background of this parent window (the systray container window) to whatever is needed in `luaA_systray`. Thus... I would expect that this patch does not make any difference.

It makes a difference on this GTK 3.24. It's not perfect, as it stops working after I right-click the affected icons. I know it works otherwise, because once it stops working, I cannot say from icon state, that I got dropped from my wifi network.
I know nothing about how it affects different environments.

> Also, your patch says that this provides systray icons with transparent background with the correct background. However, it just changes the background of all systray icons. I bet I could come up with an example program that e.g. just sets a solid green background. Your patch would then break this and make the icon disappear.

Note again: I don't know the specs. However, if an example program sets green background, won't it happen after we did it, so behaving correctly? In any case, if it breaks anyone, then I am not interested in pushing the patch in.

> Also, what did you test this with? Some GTK- or Qt- using app? Something that uses its own systray implementation? What is it specifically?

Yes, I am using network-manager-gnome as well as xfce4-power-manager. Both depend on GTK 3, so these are GTK apps.

**Comment by psychon** [comment]
Okay, sorry then, but you are just working around a known bug in GTK 3.24. GTK no longer sets its tray icon's background to `ParentRelative`, but to `None`. Thus, it gets `None` and this leads to the behaviour that you see.

Bug is in GTK (as you already figured out in #2449 as well).

**Comment by n1-cz** [comment]
I'm another victim to this :)

@psychon so according to your words the solution is to wait for fixed GTK version or is there anything we can do for that (monkey patch?). My tray is so screwed up I can't recognize the icons anymore.

**Comment by McSinyx** [comment]
@n1-cz you can try to downgrade GTK+ 3 to 3.22.

**Comment by n1-cz** [comment]
I wouls like to but the version is not int apt anymore. Is there any hack how to do that without breaking the whole dependency system in apt?

**Comment by blueyed** [comment]
btw: just restarting awesome also fixes it for the moment.

**Comment by n1-cz** [comment]
Does anyone of you have link to GTK bug tracker which reports this particular issue? Or is it already fixed in newer versions?

**Comment by psychon** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/1280

**Comment by n1-cz** [comment]
seems like GTK guys advanced...not merged yet but getting close...

**Pull request closed without merging**
