### PR TITLE
WIP: Extend the clipboard API

### PR DESCRIPTION
**Pull request by psychon**
This is my today's work on #492. So far you cannot monitor for selection changes and `INCR`-transfers are not supported. Besides that, the API more-or-less works, I guess (and there are more roundtrips involved than I anticipated).

### CODE REVIEW

**Comment by psychon** [comment]
This can now do `INCR` transfers, too. From a quick look at #492, this still needs some "the selection's content changed"-signal. However, right now I have no idea how that is supposed to work and (as always when touching low-level X11 stuff) not much motivation to figure it out.

**Comment by psychon** [comment]
Oh and of course the API is currently awful:
```lua
selection("CLIPBOARD"):request("UTF8_STRING", function(part)
    if part then
        print("Next part of the clipboard is:", part)
    else
        print("Transfer done")
    end
end)
```
The C code hands each part to Lua as soon as it is received.

**Comment by psychon** [comment]
I figured out how to get notifications that the clipboard changes. Now, there is a `selection_changed` signal that is emitted on selection objects. However, this now introduces some kind of memory leak: The C code pretty much leaks a reference to each selection object so that it can later find the object when an event comes in and the notification has to be emitted. If anyone has a good idea on how a better API for this would look like, I'd welcome it. The current version is:
```lua
selection("CLIPBOARD"):connect_signal("selection_changed", function() print("clipboard changed") end)
```

**Comment by actionless** [comment]
seems like it should be rebased

**Pull request closed without merging**
