### PR TITLE
Use xcb-util-xrm

### PR DESCRIPTION
**Pull request by psychon**
Instead of using Xlib for parsing resource files, this now uses the
dedicated xcb-based library that is meant for exactly this task.

Fixes: https://github.com/awesomeWM/awesome/issues/1176

CC @AirBlader just for your information

### CODE REVIEW

**Comment by Airblader** [comment]
Completely forgot about putting this into awesome. Glad to see it happen now. :-)

**Comment by psychon** [comment]
In that case I won't mention cairo ;-)

**Comment by Airblader** [comment]
If only I knew someone working on cairo... :-P Perhaps I'll find the time at some point to clone cairo and get that done as well. :-)

**Comment by actionless** [comment]
works for me

**Comment by blueyed** [comment]
The package is quite new (https://packages.debian.org/search?searchon=sourcenames&keywords=xcb-util-xrm, https://launchpad.net/ubuntu/+source/xcb-util-xrm), so maybe we should keep the old custom code with `#ifdef`s?!

**Comment by Airblader** [comment]
i3 and rofi have been using it for a while now. I'm happy to say that not one bug has since been found in the library. Most distros should also have added the package by now.

**Comment by actionless** [comment]
i think if for somebody it will be a showstopper that person will create issue/PR on that problem and we can return to it then

**Comment by blueyed** [comment]
I see.
It came up on IRC, that's why I've wanted to mention it here.
And while most distros include it, it will not be available in LTS ones etc.
(sorry to be annoying.. ;))

**Comment by Airblader** [comment]
> And while most distros include it, it will not be available in LTS ones etc

Neither will this version of awesome be. And if they use a PPA they can use one for the library.

**Pull request merged**
