### PR TITLE
Find fallback config

### PR DESCRIPTION
**Pull request by psychon**
This hardcodes the path to the default config into the binary. This will make awesome try the default config twice for most people, but will make things actually work for people who do not have the default config in `/etc/xdg/awesome`.

### CODE REVIEW

**Comment by Elv13** [comment]
Still wont fix the issue if they modified the config or have an older one and didn't do make install but added `--search ./lib` (or $LUA_PATH). I still think putting a copy of `rc.lua` in the binary is the safest bet. +/- 25kB wont be noticed by most.

**Comment by psychon** [comment]
#1346 is titled "awesome 4.0 debian installs default rc.lua to /usr/local/etc/xdg/awesome/ not /etc/xdg/awesome/", so yes, this does fix that issue.

For #1417 I am still waiting for someone to actually show the error that makes the default config fail. I have a feeling that it might be "the user config messes up the Lua state in a way that also makes the default config fail" and so putting the config into the binary still would not help.

**Comment by psychon** [comment]
Putting the default config into the binary is not that easy. It is generated by `docs/05-awesomerc.md.lua` during `make`, so we would need something that afterwards takes the generated file, escapes it properly and puts it into a generated header or source file. All of that while getting the make-dependencies right so that the code is not compiled before the default config is added.
Also: If we want to protect against someone editing the default config, should we also protect against someone editing the libs and put e.g. all of `awful` into the binary?

But this is all off topic. This PR is about: When we install the config to some non-xdg-basedir-compliant directory, we should also look there and load the config from there. It is a bit amazing that we never did so.

**Comment by psychon** [comment]
Any reason against this?

**Pull request merged**
