### PR TITLE
Handle fit(-1, -1) more consistent / use base.fit_widget / use margin's fit()

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by psychon** [comment]
Did I mention that I don't like this -1 hack and would rather remove it?

**Comment by blueyed** [comment]
> Did I mention that I don't like this -1 hack and would rather remove it?

Got it.. :)

**Comment by psychon** [comment]
Do you agree that #535 seems saner? Can this be closed?

**Comment by blueyed** [comment]
Yes, thanks!

**Pull request closed without merging**
