### PR TITLE
Add and use gears.timer.run_delayed_calls_now()

### PR DESCRIPTION
**Pull request by psychon**
Here is the part of #2656 that @Elv13 did not complain about so far. Let's see if this is okay. :-)

(The changes to `test/` where done with `sed`)

### CODE REVIEW

**Comment by Elv13** [comment]
> Here is the part of #2656 that @Elv13 did not complain about so far. 

I did not complain about the design of the other PR. All I wanted was to replace `@module gears.delayed_call` with `@submodule gears.timer`. I actually prefer #2656 over this one. It renders differently. `@submodules` have their own sections in their "topic page".

**Comment by psychon** [comment]
> All I wanted was to replace `@module gears.delayed_call` with `@submodule gears.timer`.

And then I also move `gears.delayed_call` to `gears.timer.delayed_call`, or what? I already started to type this and then noticed this problem (because currently in that PR it is `gears.delayed_call` which is most definitely not a submodule of `gears.timer`).

**Comment by Elv13** [comment]
> And then I also move gears.delayed_call to gears.timer.delayed_call, or what?

`@submodule gears.timer` will add a `delayed_call` section in the `gears.timer` documentation page. See the client page.

**Comment by psychon** [comment]
Well, okay.. so, if someone were to search for the docs for `gears.delayed_call`, how would he find that?

**Comment by Elv13** [comment]
> Well, okay.. so, if someone were to search for the docs for gears.delayed_call, how would he find that?

If it's a submodule, then it is still `gears.timer.delayed_call`. Your `= require("...")` in `gears.timer takes care of that. You can rename the file to `gears/timer/delayed_call.lua` if you wish.

**Comment by psychon** [comment]
```
[snip]/lib/gears/delayed_call.lua:44: 'gears.timer' not found for submodule
```
I'll just give up on this module structure stuff for now and instead look into the change that I actually want to do.

**Comment by psychon** [comment]
Oh wait, this PR is exactly that: A step towards getting rid of the `refresh` signal. Hence, I reopen this one and leave "move stuff around in a way that both LDoc and Emmanuel are happy with" for someone else to work on.

**Pull request merged**
