### PR TITLE
naughty.dbus: Switch to using Gio for DBus bindings

### PR DESCRIPTION
**Pull request by psychon**
This starts the switch from our own, semi-broken DBus bindings to using
the sane bindings that Gio provides.

Part-of: https://github.com/awesomeWM/awesome/issues/1093
Signed-off-by: Uli Schlachter <psychon@znc.in>

------

This will break on Travis because of #2721, because LGI/Gio actually checks that a number is a number and not a table.

### CODE REVIEW

**Comment by dtzWill** [comment]
Seems to work! One fixup noticed introspecting dbus signatures: 485eee9a2c8d7441d853a54eea1447baf6489447

**Comment by psychon** [comment]
Whoops. Thanks for spotting that. I cherry-picked your commit into this PR.
(And since you write "it is magical enough not to need them": The types for everything are specified in `on_bus_acquire` when the `Gio.DBusInterfaceInfo` is constructed. It says here that `GetCapabilities` returns an array of strings ("as") called "caps": ` method{ name = "GetCapabilities", out_args = { arg("caps", "as") } }`)

**Comment by psychon** [comment]
Rebased on master to get the fix for #2721 and to fix the merge conflict with the fix (#2728). I expect that the Travis build will pass now.

**Comment by dtzWill** [comment]
Here's a commit I put together that fixes handling of `icon_data` when using this PR's changes:

https://github.com/dtzWill/awesome/commit/eecdeb7d469b061a2499eff3a60c6847d5cee020

I'm new to lua so this very likely can/should be improved, but this does seem to fix things for me, so thought I'd share.
I believe this is a problem introduced by the changes in this PR,
but honestly not sure if it was working with master previously.

-------

What was happening is the `icon_data` hint was unpacked as a "string" that was empty for some reason-- looking at the lgi docs for variants I think it's because complex types need to be indexed using the provided methods not just `unpack`? Anyway this gets icons sent as bytes working again.  LMK if you have any questions or this seems unrelated to changes here.

**Comment by psychon** [comment]
@dtzWill Thanks for testing this and fixing stuff. Also, sorry for causing so much breakage.

Per https://developer.gnome.org/notification-spec/#icons-and-images-formats, the image data is sent as signature `iiibiiay` (yay for DBus type readability). So, we have here:
- int32
- int32
- int32
- boolean
- int32
- int32
- array of bytes

Anyway... I'm not completely happy with your patch (sorry!) and will (hopefully) find some time to look more closely at this on Saturday.

**Comment by psychon** [comment]
After some "fun", I figured out that LGI truncates GVariant bytestrings at the first embedded nul byte, because the C API that it is based on does so. More details can be found in https://github.com/pavouk/lgi/pull/223.
Since I doubt AwesomeWM can wait for a fix in a released version of LGI, I'll do a work-around similar to what @dtzWill came up with.

**Comment by psychon** [comment]
I pushed a commit that also works around this problem. It is based heavily on the one from @dtzWill so thanks a lot for figuring out how to work around the problem!

I tested my commit with the following C program:
```C
#include <gio/gio.h>
#include <libnotify/notify.h>
int main() {
	notify_init ("Hello world!");
	NotifyNotification * Hello = notify_notification_new ("Hello world", "This is an example notification.", NULL);
	notify_notification_set_image_from_pixbuf(Hello, gdk_pixbuf_new_from_file("/tmp/gradient.png", NULL));
	notify_notification_show (Hello, NULL);
	g_object_unref(G_OBJECT(Hello));
	notify_uninit();
	return 0;
}
```

**Comment by dtzWill** [comment]
On Fri, 22 Mar 2019 10:13:04 -0700, Uli Schlachter <notifications@github.com> wrote:
> I pushed a commit that also works around this problem. It is based heavily on the one from @dtzWill so thanks a lot for figuring out how to work around the problem!

Thanks for tackling this! Switched to your much nicer patch, works great!

\o/

**Comment by psychon** [comment]
> One little "downside" of this PR is that the old dbus.c lost a lot of coverage. 

Well, let's just say that everyone who wants to change/fix something in `dbus.c` is "doing it wrong". That way, we do not need coverage for `dbus.c` since it does not change. Once nothing in AwesomeWM uses it anymore, we can deprecate it and remove it in something like 10 years.

**Comment by Elv13** [comment]
If there is no no other reviews, I will merge this soon. It needs more widespread testing before we can release v4.4.

**Comment by Elv13** [comment]
Should there be a CMakeLists.txt and README.md change to detect GDBus support for Gio?

**Comment by psychon** [comment]
I do not understand the question. `CMakeLists.txt` does not check for dependencies that are only accessed through LGI. Instead, `build-utils/lgi-check.c` does. Also, GDBus is part of Gio (e.g. `require("lgi").Gio.DBusMethodInfo`) and this file already checks for Gio. Same for `README.md`: Gio is already listed as a dependency.

So... could you clarify what you mean with your comment?

**Comment by Elv13** [comment]
> So... could you clarify what you mean with your comment?

Sorry, I was under the impression is was an optional part of Gio like GVFS, but it isn't.

**Pull request merged**
