### PR TITLE
Fix for Issue 2527

### PR DESCRIPTION
**Pull request by Sorky**
Fix for hotkey_popup via awful menu showing on wrong screen

https://github.com/awesomeWM/awesome/issues/2527

Next comments will show local testing and confirmation

### CODE REVIEW

**Comment by Sorky** [comment]
Confirming local development git is up to date and has no other changes...

clone@OH-Server:/_testing/awesome$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
(use "git add ..." to update what will be committed)
(use "git checkout -- ..." to discard changes in working directory)

    modified:   awesomerc.lua
    modified:   lib/awful/hotkeys_popup/init.lua

Untracked files:
(use "git add ..." to include in what will be committed)

    .orig.awesomerc.lua
    lib/awful/hotkeys_popup/.orig.init.lua

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by Sorky** [comment]
Confirming changes are the same...

clone@OH-Server:/_testing/awesome$ diff awesomerc.lua .orig.awesomerc.lua 
17c17
< local hotkeys_popup = require("awful.hotkeys_popup")
---
> local hotkeys_popup = require("awful.hotkeys_popup").widget
107c107
<    { "hotkeys", hotkeys_popup.show },
---
>    { "hotkeys", function() return false, hotkeys_popup.show_help end},

**Comment by Sorky** [comment]
Confirming changes are the same...

clone@OH-Server:/_testing/awesome$ diff lib/awful/hotkeys_popup/init.lua lib/awful/hotkeys_popup/.orig.init.lua 
8a9
> 
12,27d12
< local awful = { screen = require( "awful.screen" ) }
< 
< --- awful.menu callable version of show popup with hotkeys help.
< --
< -- example usage: myawesomemenu = {{ "hotkeys", hotkeys_popup.show },
< --
< -- see `awful.hotkeys_popup.widget.show_help` for more information
< 
< hotkeys_popup.show = function() hotkeys_popup.widget.show_help( _, awful.screen.focused() ) end
< 
< --- Show popup with hotkeys help (shortcut to awful.hotkeys_popup.widget.show_help).
< --
< -- example usage: myawesomemenu = {{ "hotkeys", function() return false, hotkeys_popup.show_help end},
< --
< -- see `awful.hotkeys_popup.widget.show_help` for more information
<

**Comment by Sorky** [comment]
Confirming running build versiion with modified awesomerc.lua...

clone@OH-Server:~$ ps -a | grep awesome
10062 tty1     00:01:54 awesome
25434 tty6     00:00:01 awesome
clone@OH-Server:~$ ps -Flww -p 25434
F S UID        PID  PPID  C PRI  NI ADDR SZ WCHAN    RSS PSR STIME TTY          TIME CMD
0 S clone    25434 25423  0  80   0 - 66525 poll_s 42472   3 20:32 tty6     00:00:01 /_testing/awesome/build/awesome -c /_testing/awesome/build/awesomerc.lua

**Comment by actionless** [comment]
and second question: how do you it's fixing multi-screen issue if you told in another ticket what you don't have env to test it?

**Comment by Sorky** [comment]
> and second question: how do you it's fixing multi-screen issue if you told in another ticket what you don't have env to test it?

Second question first...

I have a dual head system but it is running 4.2 and I used Xephyr to test the mods, but I only have that working with one display

I did actually mention that I found a way to test it in the 'Issue' - "I cloned my user and set it up so startx runs /_testing/awesome/build/awesome"

Here's a more detailed explanation...

I cloned my user and set it up so startx runs /_testing/awesome/build/awesome

I'm now able to login as 'clone' on a separate tty 'and simply startx running the build version

All this can be see in the 4 testing comments I posted with this PR...
1) Shows the test build is up to date and only has the changed stipulated
2) Shows my local awesomerc.lua changes so you can confirm they are the same as in this PR
3) Shows my local lib/awful/hotkeys_popup/init.lua changes so you can confirm they are the same as in this PR
4) Shows that I am running the build version on tty6 as user clone

**Comment by Sorky** [comment]
> i've already explained to you what changing hotkeys_popup to add function which makes sense only in context of using it as callback in menu won't be welcome
> 
> please redo it normally

While I didn't understand you saying that, it works in any context (ie: the following will also work)...
```
globalkeys = gears.table.join(
    awful.key({ modkey,           }, "s",      hotkeys_popup.show,
``
The difference between the two is that `hotkeys_popup.show` shows on the display where the mouse is whereas `hotkeys_popup.show_help` opens on the display where the last used client is (nice for keyboard only users so I didn't want to replace/alter it)

**Comment by actionless** [comment]
> it works in any context

but it drops first argument specifically for compatibility with with being used as menu callback

**Comment by actionless** [comment]
> The difference between the two is that hotkeys_popup.show shows on the display where the mouse is whereas hotkeys_popup.show_help opens on the display where the last used client is (nice for keyboard only users so I didn't want to replace/alter it)

instead i recommend you adding optional argument to function show_help to define that behavior explicitly

**Comment by Sorky** [comment]
> > it works in any context
> 
> but it drops first argument specifically for compatibility with with being used as menu callback

That is far from the case - The menu callback behaviour only occurs when the function call is done without brackets which is why `function() hotkeys_popup.show_help() end` works in the menu (not in 4.2 but in the master thanks to your fixes). In short, the menu compatibility comes from the new 'show' function not having any arguments, so whatever the menu passes goes nowhere

The reason I drop the first argument is because the client isn't a factor. In fact, if no client is currently in focus (the error case that I am fixing) the existing code `c = c or capi.client.focus` results in a value of nil for c, so in fact that code still executes and still returns nil

Furthermore, the 's' argument actually specifies the screen to use and is what does the work - see the following excerpt from awesome/lib/awful/hotkeys_popup/widget.lua...
```
    function widget_instance:show_help(c, s, show_args)
<snip>
        c = c or capi.client.focus
        s = s or (c and c.screen or awful.screen.focused())
<snip>
        local help_wibox = self._cached_wiboxes[s][joined_groups]
        help_wibox:show()
```

**Comment by Sorky** [comment]
Note: Comment above was updated for greater accuracy and clarity

**Comment by actionless** [comment]
anyway the described problem should be solved by creating new optional arg, not new function wrapper

**Comment by Sorky** [comment]
> anyway the described problem should be solved by creating new optional arg, not new function wrapper

Why add that sort of complexity? The wrapper is IMHO quite elegant, aligns with the existing one in init.lua and allows a very neat rc.lua

**Comment by Sorky** [comment]
Damn - Github merged my fork - I will close this and redo

**Pull request closed without merging**
