### PR TITLE
Multi-row support of systray.

### PR DESCRIPTION
**Pull request by xinhaoyuan**
Also, fix the fitting logic so that the result width and height are fitted in the available space. Previously the result dimensions can be larger than the input, but cropped in https://github.com/awesomeWM/awesome/blob/e7a21947e6785f53042338c684b9b96cc9b0f500/lib/wibox/widget/base.lua#L547. But still it can cause problems e.g. when used inside wibox.container.place.

### CODE REVIEW

**Comment by Elv13** [comment]
Thanks for this contribution, I am AFK for a few more weeks. So it mght take some time before I review/test this. However it looks very nice. I wonder if it's possible to make the API a bit more dynamic/flexible rather than only expose a `beautiful` variable? Maybe adding an `icon_size` and `maximum_row_count`/`maximum_column_count` property to the `systray.lua` object?

**Comment by xinhaoyuan** [comment]
Thanks for the suggestions!

> Maybe adding an icon_size

There is the `systray.base_size` property for the desired icon size - is this what you were thinking of?

> maximum_row_count/maximum_column_count property

I guess the two properties cannot be used at once (since I'm not sure what to do when there are more icons than `max_row * max_column`). I realized that `max_rows` + `base_size` + some wibox container can subsume the original `forced_rows` mechanism I was proposing. Thus I now changed to introduce only the `max_rows` property. `max_column` can be achieved by setting `horizontal` to false and use `max_rows` instead.

About whether to keep `max_rows` as a beautiful constant or systray property. I don't have a strong opinion, but given that I don't have the need to change the value, similarly to the `icon_spacing` constant, keeping it as a beautiful constant is enough for me. But I can be missing something.

**Review by Aire-One — COMMENTED** [review]
I think it would be great to have some examples in the doc. Maybe that's not something we want to do in the scope of this PR, tho.

**Review by actionless — APPROVED** [review]
so, let's try this? :)

**Review by Aire-One — APPROVED** [review]

**Review by Elv13 — APPROVED** [review]

**Pull request merged**
