### PR TITLE
Fix some possible errors with resizes

### PR DESCRIPTION
**Pull request by psychon**
This fixes at least the X11 errors part from #1340 (at least I think so, original reporter didn't test this patch yet).

### CODE REVIEW

**Comment by vitek** [comment]
Created its own issue for this issue https://github.com/awesomeWM/awesome/issues/1368

**Comment by vitek** [comment]
Cannot reproduce the issue with this PR

**Comment by psychon** [comment]
> Cannot reproduce the issue with this PR

Which one exactly? #1368?

**Comment by vitek** [comment]
Yes, #1368. I've created its own issue for each problem

**Comment by blueyed** [comment]
Sounded like this should have `Fixes: https://github.com/awesomeWM/awesome/issues/1368` when merging - so I did that.

**Pull request merged**
