### PR TITLE
fix(themes: xresources): explicit bg and fg for tooltip

### PR DESCRIPTION
**Pull request by actionless**
should address https://github.com/awesomeWM/awesome/pull/929#issuecomment-229145404

### CODE REVIEW

**Comment by psychon** [comment]
The travis failure seems unrelated (but annoying), so: :+1: 
I think @blueyed "started this" and gets to decide if this is the right fix.

**Comment by blueyed** [comment]
LGTM, given that the default was changed (accidentally(?) - but I think it makes sense).

**Comment by blueyed** [comment]
@actionless 
You were just added to the team (after speaking to @psychon and @Elv13).. :boom: 

Please (squash-)merge it yourself.. :)

**Comment by actionless** [comment]
thanks :)

i rebased it on master, but those two travis setups are still failing

**Comment by psychon** [comment]
Ignore that, it's not yet fixed. It's tracked in #982 and worked around by #987 (which wasn't merged yet and I don't know if it should be merged). The problem is that all code-coverage builds suddenly fail.

**Comment by actionless** [comment]
then it's probably a permission problem, i first can't merge because of the failing travis

**Comment by psychon** [comment]
Heh. Thanks GitHub. You set us up a so-called "Team". Membership in which gains you... no access rights.

@actionless Can you try again? You should now be able to push to awesome (and awesome-www, but that's not really important, I guess)

**Pull request merged**
