### PR TITLE
Fix awful.rules.does_match

### PR DESCRIPTION
**Pull request by blueyed**
This includes a fix (https://github.com/awesomeWM/awesome/commit/eb01e969f68ca577224bdf8693c5d13c5211be04) and some refactoring / improvement.

I am not sure about the new method name `entry_matches`.
There is `does_match` already for a list of rules, although it has never been working apparently (added in adbc7ac).

Maybe we could use `matches` and `list_matches`?

### CODE REVIEW

**Comment by psychon** [comment]
Urgh. Fine with me, but when did `awful.rules` become so complicated?

**Comment by blueyed** [comment]
What is fine with you?  The supposed change?

> Maybe we could use matches and list_matches?

**Comment by psychon** [comment]
Yeah

**Comment by blueyed** [comment]
Done, moving to "next".

**Pull request closed without merging**
