### PR TITLE
feat(awful: titlebar): expose fallback title

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by actionless** [comment]
@psychon  a lot of dialog windows have ugly for my taste `<unknown>` title

**Comment by actionless** [comment]
i think it's not good idea setting client's name instead of overriding the default value of in titlebar implementation

i'll update ldoc now

**Comment by actionless** [comment]
@Elv13 i've made the change you suggested but i don't think it looks better now:

before:
2018-12-17--1545064043_953x178_scrot
2018-12-17--1545064056_770x275_scrot





after:
2018-12-17--1545064031_673x195_scrot
2018-12-17--1545064020_908x386_scrot

**Comment by Elv13** [comment]
The first one is correct, the second one isn't, right?

**Comment by actionless** [comment]
the second is using `@field`, the last commit

**Comment by Elv13** [comment]
I pushed a proposed fix

**Comment by actionless** [comment]
i see, however `opt` is not parsed for some reason:

2018-12-17--1545066187_683x345_scrot

**Comment by Elv13** [comment]
yeah, that would be an `ldoc` bug... I am fine with this for now given it is technically rendering the fields correctly. Squash merge if you agree.

**Comment by actionless** [comment]
:+1:

**Pull request merged**
