### PR TITLE
Various doc improvements nr. 4

### PR DESCRIPTION
**Pull request by sclu1034**
There's a small code refactor in there, but it merely changes a few variable names to make them more readable.

### CODE REVIEW

**Review by Aire-One — APPROVED** [review]
This is very good work, thanks a lot for the effort! :heart: 

Only comment I have is about 05ca439ed5dfa4b2e7e41866d495c00954f7377b: If we have to replace this table with something, I would have preferred to have a real HTML list here. What are the beneficts from a flex div in this situation?

**Review by Aire-One — CHANGES_REQUESTED** [review]
Uh, well, given you even kept the `*` to create bullets, I'm moving my concern to an actual change request. I think we better go with an HTML list here.

**Comment by sclu1034** [comment]
I did not keep `*` to create markdown bullet points. Those are required for the file to be properly imported into a C comment. If this was imported into Lua, they would be replaced by `--`.
The CMake "magic" that copies these files into the actual code comments doesn't prefix the lines individually. So if I were to make that file plain HTML, it would break the doc comment.

The benefit of the `<div>` structure is better screen space utilization.

On master, 1440p is not enough to show even half the options, 1080p requires even more scrolling.
90% is wasted white space, and a list wouldn't be much better.

Also notice the HTML list dot at the start, created by the fact that CMake's substitution does add the comment prefix for the first line (or rather, keeps one that's already there), but subsequent ones don't create additional `<li>`s.
image

Now, everything is visible in half a screen. And `flex-wrap` and a `width` in `em` makes it adjust properly, down to mobile.
image

**Comment by Aire-One** [comment]
> I did not keep the `*` to create markdown bullet points. Those are required for the file to be properly imported into a C comment. 

Oh yes! I should have get it from the first look... My bad. 

Thanks for the additional details and screenshots comparison about the use of flexbox over a list on this situation. Now I understand your point. I think I don't really like this grid-like list style, but I can't think of a better alternative... 

Good job 👍

**Review by Aire-One — APPROVED** [review]

**Review by Elv13 — APPROVED** [review]

**Pull request merged**
