### PR TITLE
More robust errors: make sure errors are strings

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
@psychon 
I think we should merge it as-is for now, and then you could provide your change on top?

**Comment by blueyed** [comment]
@psychon 
Sorry, rebasing and force-pushing removed your eloquent / verbose comment.. :(

**Comment by blueyed** [comment]
..re-pushed the old commit to make it appear again..

**Comment by psychon** [comment]
My comment is on commit 5c446c9c09ef7f6c30de6a330e4cc652f2d5f024. Yay for these kind of things getting easily lost on github, but at least we have a pointer now.

@blueyed Feel free to merge this. Let's hope I will remember to implement `luaA_tolstring`....

**Pull request merged**
