### PR TITLE
textclock: Produce reproducible output

### PR DESCRIPTION
**Pull request by psychon**
When $SOURCE_DIRECTORY is set, we are most likely currently running the
examples test, i.e. generating images. These images end up in the
documentation.

To make the images reproducable, i.e. independent from the current time,
this commit makes the textclock honor $SOURCE_DATE_EPOCH if
$SOURCE_DIRECTORY is set.

See commit 9d7eaf02 for some more details.

Signed-off-by: Uli Schlachter <psychon@znc.in>

### CODE REVIEW

**Comment by psychon** [comment]
CC @reinerh Do you have a better idea for this? This feels a bit hacky, but might still be the cleanest option...

**Comment by reinerh** [comment]
It works for the texclock, but I also see differences in the calendar widget (i.e. a different day is highlighted in AUTOGEN_awful_popup_wiboxtypes.svg when e.g. building in different timezones).
And a different date is also displayed in AUTOGEN_awful_tooltip_textclock.svg (the date+time in the tooltip) and in AUTOGEN_awful_tooltip_textclock2.svg.

**Comment by psychon** [comment]
>  (i.e. a different day is highlighted in AUTOGEN_awful_popup_wiboxtypes.svg when e.g. building in different timezones).
> And a different date is also displayed in AUTOGEN_awful_tooltip_textclock.svg (the date+time in the tooltip) and in AUTOGEN_awful_tooltip_textclock2.svg.

Oh, I'm stupid. All of them do indeed use `os.date`. I will re-open #2621 (well, re-submit, I cannot re-open that one since the branch was already deleted).

**Comment by psychon** [comment]
@reinerh Oh and of course: Thanks for testing!

**Pull request merged**
