### PR TITLE
Remove awful.{spawn.,}pread (#184)

### PR DESCRIPTION
**Pull request by psychon**
Signed-off-by: Uli Schlachter <psychon@znc.in>

### CODE REVIEW

**Comment by blueyed** [comment]
Hmm, I think it's a good convenience wrapper, but am using it anyway wrapped with `rtrim`:

```lua
--- Remove trailing whitespace from string.
local rtrim = function(s)
  local n = #s
  while n > 0 and s:find("^%s", n) do n = n - 1 end
  return s:sub(1, n)
end
```

**Comment by blueyed** [comment]
I support your comment at https://github.com/awesomeWM/awesome/issues/184#issuecomment-215947469 though: I can write my own wrapper and/or should make this async anyway.

Maybe the documentation could have a section regarding how to convert your `pread` calls (in case it's not there already)?

**Comment by psychon** [comment]
How about making the deprecation message point to `awful.spawn.easy_async` and `with_line_callback`? That way people can find the async alternatives more easily.

**Comment by blueyed** [comment]
Good idea!

**Comment by blueyed** [comment]
What do you think about an even easier helper, which would automatically print `stderr` for example (in case of errors)?

Something like `function spawn_async(cmd, success_handler, error_handler)`, where the handlers would get `stdout` and `stderr`?
This way you could just call `spawn_async({'sh', '-c', '…'}, function(stdout) … end)`.

Without `error_handler` it would default to printing the error to stderr and/or create a notification.

**Comment by blueyed** [comment]
Something like this:
```lua
my_easy_async = function(cmd, cb, cb_error, cb_signal)
  if not cb_error then
    cb_error = function(stdout, stderr, exitcode)
      gears.debug.print_error(string.format(
        '"%s" exited with %d. stderr: %s', cmd, exitcode, stderr))
    end
  end
  if not cb_signal then
    cb_signal = function(stdout, stderr, exitcode)
      gears.debug.print_error(string.format(
        '"%s" exited due to signal %d. stderr: %s', cmd, exitcode, stderr))
    end
  end

  awful.spawn.easy_async(cmd, function(stdout, stderr, exitreason, exitcode)
    if exitreason == 'exit' then
      if exitcode == 0 then
        if cb then
          cb(stdout, stderr)
        end
      else
        cb_error(stdout, stderr, exitcode)
      end
    else
      cb_signal(stdout, stderr, exitcode)
    end
  end)
end
```

**Comment by psychon** [comment]
Fine by me, but I don't know what a good name for that would be. If we have too many functions in `awful.spawn` it will become confusing at some point.
Also: I'd print both stdout and stderr (perhaps only if non-empty?) because someone will find something which prints on stdout instead of stderr.

**Comment by blueyed** [comment]
What about changing `easy_async` to make it that easy?

> Also: I'd print both stdout and stderr (perhaps only if non-empty?) because someone will find something which prints on stdout instead of stderr.

Agreed.

**Comment by blueyed** [comment]
Let's discuss further on https://github.com/awesomeWM/awesome/pull/1001.

**Comment by psychon** [comment]
How about this fixup commit? Does it make the deprecation warning clear enough?

**Comment by blueyed** [comment]
Very good!
Thanks.
Please squash-merge yourself - not moving to "next" since there can only be one milestone.
Should we better use a label for "next" instead of a milestone?
Might also be worth checking out https://www.zenhub.com/ for this and in general (free for OSS).

**Pull request merged**
