### PR TITLE
naughty: mouse: only react on release events

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/awesomeWM/awesome/issues/1445.

### CODE REVIEW

**Comment by blueyed** [comment]
Tested by @Veratil.

**Comment by Elv13** [comment]
Wont that just move the problem from "things that act on mouse release events" to "things that act on mouse press events"? I think both press and release events need to be set. Also, #1447 might happen/

**Comment by Veratil** [comment]
> Wont that just move the problem from "things that act on mouse release events" to "things that act on mouse press events"? I think both press and release events need to be set. Also, #1447 might happen/

This actually causes a notification to act like it should, destroying itself when the button is released rather than pressed and causing whatever is below the mouse after the notification is destroyed getting a mouse release event.

I've tested every notification I have in various places so far. This makes things act as expected without passing events anywhere else. It doesn't interfere with dbus notifications with internal commands (tested with Pithos popups for skip/pause/play). The notifications are working exactly as expected with this patch.

As for #1447, I haven't had propagated events from notifications yet. I'm not discounting the possibility, just noting that that has not happened to me throughout all the testing with notifications I've done.

**Comment by psychon** [comment]
> Wont that just move the problem from "things that act on mouse release events" to "things that act on mouse press events"? I think both press and release events need to be set. 

That's not how the C code works here. It does not care if a callback is set. You could even set both to `nil` and the C code would still do the same things, X11-wise.

What happens is:

- The button is pressed over a notification
- The X11 server sends an event to awesome about the press
- Awesome reacts by removing the notification window
- The mouse cursor is now over whatever was below the notification
- The button is released
- The release event is sent to whatever window is below the mouse cursor

You could get the same behaviour by having a wibox destroyed via a timer. If you press the button before the wibox is destroyed and release it afterwards, the release event gets sent to the window below the wibox. What I am trying to say is: This has nothing to do with "is there a press/release callback".

**Comment by psychon** [comment]
Merged with dd339fd62a835e1f5899ff73a1d8837b9cbf1c27, but I seem to have mixed something up while rebasing.

**Comment by blueyed** [comment]
@psychon 
> but I seem to have mixed something up while rebasing.

The commit looks fine to me?!

**Comment by psychon** [comment]
>> but I seem to have mixed something up while rebasing.

>The commit looks fine to me?!

...but I didn't make it point back here like you always do.

**Comment by blueyed** [comment]
@psychon 
Oh.. then you did not use GitHub's squash UI probably.

**Comment by psychon** [comment]
yup

**Comment by blueyed** [comment]
I find this very useful - but it will use your GitHub email then..

**Pull request closed without merging**
