### PR TITLE
fix(awful: key): clone table with user data

### LINKED ISSUE #1401: User data for awful.key cannot be shared
Output of `awesome --version`:
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.0
```

**How to reproduce the issue:**
Somewhere in your config where you define keys, replace a local table with description/group with a variable that contains this table. Use the same variable in some other key.
E.g.
```lua
local aud = { description = "Raise the volume", group = "audio" }
local globalkeys = awful.util.table.join(
    awful.key({}, "XF86AudioRaiseVolume", apw.up, aud),
    awful.key({ modkey }, "Right", apw.up, aud),
)
```
Restart with the new config, open hotkeys popup.

**Actual result:**
image

**Expected result:**
There should have been two records for different keys with the same description/group. Or at least there should be a documentation notice on `awful.key` that you can't reuse `data` argument.

### PR DESCRIPTION
**Pull request by actionless**
closes #1401 

i've accidentially noticed what the change is not for the hotkey widget itself so no need to wait for its tests

### CODE REVIEW

**Comment by psychon** [comment]
No idea why, but this causes:
```
== Running /home/travis/build/awesomeWM/awesome/tests/test-awesomerc.lua ==

Error: running function for step 2/11 (@1): [string "local awful = require("awful")..."]:60: attempt to call a nil value
```

@Elv13 Unrelated, but I noticed it due to this (next step would be to inline this so that no anonymous function is created):
```diff
diff --git a/tests/test-awesomerc.lua b/tests/test-awesomerc.lua
index 9076945..5db2646 100644
--- a/tests/test-awesomerc.lua
+++ b/tests/test-awesomerc.lua
@@ -5,10 +5,9 @@ local awful = require("awful")
 local old_c = nil
 
 local function get_callback(mod, key)
-    local inf = {}
-    awful.key(mod, key, nil, nil, inf)
-
-    return inf.execute
+    return function()
+        awful.key.execute(mod, key)
+    end
 end
 
 -- Get a tag and a client
```

**Comment by psychon** [comment]
Actually... it's trivial why this breaks this `execute` callback. The better question is: Why does `awful.key` add an `execute` entry to the data table that it gets? I can't find any (reasonable) use of this (but I only did a quick grep). This is not even documented, so would it be an API break to just get rid of that `execute` entry?

**Comment by actionless** [comment]
https://awesomewm.org/apidoc/libraries/awful.key.html#execute

i think we shoud drop get_callback helper from the test and replace `get_callback({modkey}, "t")()` to  `awful.key.execute({"modkey"}, "t")`

**Comment by psychon** [comment]
> or do you mean what it's not documented as field of data table arg?

Yup. That's what your patch breaks, but the test depends on that.

> i think we shoud drop get_callback helper from the test and replace get_callback({modkey}, "t")() to awful.key.execute({"modkey"}, "t")

Yup.

**Comment by actionless** [comment]
now travis seems happy

**Comment by Elv13** [comment]
Thanks

**Pull request merged**
