### PR TITLE
PARTIAL: Add useless gap utility functions

### PR DESCRIPTION
**Pull request by Elv13**
This PR take the awful.tag part of my previous useless gap issue ( https://github.com/awesomeWM/awesome/issues/80 ) as this part is less or more ready. It doesn't add the actual useless gap logic based on ( https://github.com/awesomeWM/awesome/pull/101 ). This commit can be used as base for the actual implementation

### CODE REVIEW

**Comment by psychon** [comment]
I would propose `tag.setgap` to do `gap = math.max(0, gap)` instead of silently ignoring negative arguments. Also, I'd vote for removing the "useless" everywhere and have it only called "gap".

Besides that, looks good to me.

**Comment by silverhammermba** [comment]
I didn't see that you were working on this, so I also [implemented gaps](https://github.com/silverhammermba/awesome/compare/gaps). The big difference is that I made them a client property rather than a tag property.

My reasoning was that border widths are a client property, and gaps are similar in terms of how they are computed and in the resulting effect. But I can also see how the tag property makes sense, since you're most likely going to want uniform gaps on each tag (though I'd say the same for border widths...).

**Comment by Elv13** [comment]
I am not sure, I think it belong to the tag, not the client. Also, having to change the `C` core for something like that is usually a sign a solution is too complicated. I Think it make more sense per tag.

Imagine a client in multiple tags, do you really think the distorted layout it will create is really what the user wish for? Any tags with client with multiple gaps will look very wierd. No?

**Comment by silverhammermba** [comment]
I agree that it would look weird, but isn't the same true for border widths?

You do raise a good point about the C core, and now I realize that I could have just set the new property in Lua as you did with the tags. If there is a great outcry to have gaps per-client rather than per-tag, I'll go back and do that.

**Comment by Elv13** [comment]
There is some use case where you want border per clients. For example, some clients have build in borders or special shapes. In that case, you might want to disable borders on them. This use case doesn't really apply to the gaps.

**Comment by Elv13** [comment]
Deprecated by https://github.com/awesomeWM/awesome/pull/279

**Pull request closed without merging**
