### PR TITLE
Fix 4 "new API" notification bugs

### PR DESCRIPTION
**Pull request by Elv13**
Well, updating now works "better". Better as-in, I have zero apps that use this, but tested using some Lua scripts and it now works for me. 2 of the "fixes" are more for general robustness than major issues. The signal typo is quite a facepalm.

```lua
local Gio       = require("lgi"        ).Gio
local GLib      = require("lgi"        ).GLib
local main_loop = GLib.MainLoop()

local dbus_connection = assert(Gio.bus_get_sync(Gio.BusType.SESSION))

local counter = 1

local actions = { "1", "one", "2", "two", "3", "three" }

local function send_notify(app, id, icon, summary, body, actions, hints, timeout, callback)
    local parameters = GLib.Variant("(susssasa{sv}i)", {
        app, id, icon, summary, body, actions, hints, timeout
    })
    local reply_type = GLib.VariantType.new("(u)")

    local function invoke_callback(conn, result)
        local new_id = conn:call_finish(result).value[1]
        print("RESULT", new_id)
        counter = counter + 1

        if counter >= 5 then os.exit(0) end

        os.execute("sleep 3")

        send_notify("app", new_id, "", "one two three"..counter, "body"..counter, actions, {}, 25000)
    end

    print("CALL")

    dbus_connection:call("org.freedesktop.Notifications",
        "/org/freedesktop/Notifications", "org.freedesktop.Notifications",
        "Notify", parameters, reply_type, Gio.DBusCallFlags.NO_AUTO_START, -1,
        nil, invoke_callback)
end

GLib.idle_add(GLib.PRIORITY_DEFAULT_IDLE, function()
    send_notify("app", 9999, "", "one two three", "body", actions, {}, 25000)
end)

main_loop:run()
```

### CODE REVIEW

**Comment by vn-ki** [comment]
@Elv13 This doesn't work with the new `naughty.notification`. See image

2019 07 09-22 35 38 screenshot

With the old `naughty.notify` api, it works. But the timeout for the notification uses the first notification's timer (I think). This makes the timeout different for later notifications.

<details>
<summary>The code I used, in case</summary>

```lua
  if naughty.notification ~= nil then
    notification = naughty.notification({
        title = title,
        text = artist,
        icon = notification_icon,
        timeout = 20,
        replaces_id = last_notification_id,
        actions = {
          naughty.action {
            name = 'Prev',
            icon = beautiful.playerctl_prev_icon,
            icon_only=true
          },
          naughty.action {
            name = 'Play/Pause',
            icon = beautiful.playerctl_toggle_icon,
            icon_only=true
          },
          naughty.action {
            name = 'Next',
            icon = beautiful.playerctl_next_icon,
            icon_only=true
          },
        }
    })
    last_notification_id = notification.id
  else
    notification = naughty.notify({
        title = title,
        text = artist,
        icon = notification_icon,
        timeout = 4,
        replaces_id = last_notification_id
    })
    last_notification_id = notification.id
  end

```

</details>

**Comment by Elv13** [comment]
@vn-ki This is normal, the new API doesn't have a `replace_id`. You are creating a new notification object, which is a new notification. You need to update the old notification object (`my_old_notification.message = "foo"`). `naughty.notify` is a proxy that may or may not create new objects, `naughty.notification()` is directly the constructor of a new notification.

**Comment by Elv13** [comment]
> Does any of this warrant the addition of a new test?

Yes. I will add them when I submit the last part. As seen in @vn-ki example, having custom notification for some apps is currently cumbersome. The last series of patches will add support for an `awful.rules` like API (sharing most of the code) to filter and modify notifications before they are displayed. There is a work done in that PR, but given I "saw big" and went on to add `awful.rules` to tags, screens, notifications, clipboard (and of course clients), this is still not polished enough.

I say that because one of the pull request will add a better test template/framework to test those details, see https://elv13.github.io/declarative%20rules/ruled.tag.html (disregard the API, it is a very early draft, but look at the "pretty pictures"). It has steps like the integration tests, but better built in tooling to compare stuff across steps.

**Comment by vn-ki** [comment]
> This is normal, the new API doesn't have a replace_id.

Oh. Alright. I think I saw replaces_id in the docs.

> This makes the timeout different for later notifications.

You might have missed this @Elv13

**Comment by Elv13** [comment]
> You might have missed this @Elv13

Indeed. Please report another issue (or better, a pull request). It's a bit unrelated to what this PR attempts to fix.

**Comment by actionless** [comment]
> This is normal, the new API doesn't have a replace_id. You are creating a new notification object, which is a new notification. You need to update the old notification object (my_old_notification.message = "foo"). naughty.notify is a proxy that may or may not create new objects, naughty.notification() is directly the constructor of a new notification.

what about printing deprecation warning when it used?


also documentation for naughty.notification{} still have it documented: file:///usr/share/doc/awesome/doc/core%20components/naughty.notification.html#naughty.notification

**Comment by Ryuno-Ki** [comment]
We can't access your machine, @actionless (i.e. file: protocol instead of a web resource with https:).

**Comment by Elv13** [comment]
> also documentation for naughty.notification{} still have it documented: file:///usr/share/doc/awesome/doc/core%20components/naughty.notification.html#naughty.notification

whoops. I will remove it. It cannot work the way it's implemented. `naughty.notification()` is a constructor, if it was to try to supersede another object, it would explode elsewhere.

**Comment by actionless** [comment]
@Ryuno-Ki everybody _must_ have there docs from the latest git master ;)

**Comment by Elv13** [comment]
Merging this for now. I will open a new one for the next batch.

**Pull request merged**
