### PR TITLE
Migrate Mergify configuration to v2

### PR DESCRIPTION
**Pull request by jd**
This just convert the file to the new configuration format.
The action "delete_head_branch" is added to clean up branches after they are
merged.

### CODE REVIEW

**Comment by jd** [comment]
@Elv13 You can do that indeed. :)

**Comment by Elv13** [comment]
> @Elv13 You can do that indeed. :)

Great, so the next step is to have the rebase+merge_commit and skip merge commit for single commit PRs ;)? I really miss this. One of the issue I have with mergify right now is that the commit log looks like spaghetti

screenshot_20181015_150021

All those twisted branches are really not necessary. If it was rebased on HEAD before merging, it would not happen and that screenshot would look like a "vertical snake".

**Comment by actionless** [comment]
we could make two extra rulesets with:

```
    conditions:
      - label=rebase
```

and 

```
    conditions:
      - label=squash
```

for choosing explicitly action, right?

**Comment by Elv13** [comment]
Almost, I will open another issue there to request adding a "commit-count" or "#commit" condition.

**Comment by actionless** [comment]
yeah, that would be even better :+1:

**Pull request merged**
