### PR TITLE
Exclude tests/ on codecov

### PR DESCRIPTION
**Pull request by psychon**
I _think_ that this fixes the part of #962 that is not part of the title, namely that codecov also showed code coverage for the tests runners. Let's see what codecov says after this ran...

### CODE REVIEW

**Comment by psychon** [comment]
Hm.. this seems to break coverage for the "examples tests". `gears.shape` is completely uncovered in both coveralls and codecov.

**Comment by psychon** [comment]
Heh, I guess that this found the problem that #982 tracks before the new luacov release brought this problem to master. :-)

**Comment by blueyed** [comment]
This needs to be rebased.

**Comment by blueyed** [comment]
Closing this as per the discussion in https://github.com/awesomeWM/awesome/pull/1239#issuecomment-270336596: it appears to be a workaround only, and I think it is better to track coverage of tests also instead.

**Pull request closed without merging**
