### PR TITLE
tests: Prevent locking

### PR DESCRIPTION
**Pull request by Elv13**
I need to figure out why I need this on my laptop

### CODE REVIEW

**Comment by psychon** [comment]
Some random ideas:
- set `CI=true` so that `run.sh` does `set -x` and prints all commands
- alternatively: run `pstree` when this locked up to see which command the shell script is waiting for
- if it's `awesome-client`: Somehow get a `dbus-monitor` onto the dbus bus that `run.sh` starts

**Comment by Elv13** [comment]
```
+ '[' '' = true ']'
++ dirname -- ../tests/run.sh
+ cd -P -- ../tests
+ this_dir=/home/lepagee/dev/awesome/tests
+ '[' 0 '!=' 0 ']'
+ tests='/home/lepagee/dev/awesome/tests/test*.lua'
+ root_dir=/home/lepagee/dev/awesome/tests/..
+ '[' '' = true ']'
+ HEADLESS=0
+ TEST_PAUSE_ON_ERRORS=0
+ TEST_QUIT_ON_TIMEOUT=1
+ export TEST_PAUSE_ON_ERRORS
+ XEPHYR=Xephyr
+ XVFB=Xvfb
+ AWESOME=/home/lepagee/dev/awesome/tests/../build/awesome
+ '[' -x /home/lepagee/dev/awesome/tests/../build/awesome ']'
+ RC_FILE=/home/lepagee/dev/awesome/tests/../build/awesomerc.lua
+ AWESOME_CLIENT=/home/lepagee/dev/awesome/tests/../utils/awesome-client
+ D=:5
+ SIZE=1024x768
+ '[' 0 = 1 ']'
+ xserver_pid=13357
+ cd /home/lepagee/dev/awesome/tests/../build
+ Xephyr :5 -ac -name xephyr_:5 -noreset -screen 1024x768
++ lua -e 'print(package.path)'
+ LUA_PATH='./?.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib64/lua/5.1/?.lua;/usr/lib64/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;lib/?.lua;lib/?/init.lua'
+ LUA_PATH='./?.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;/usr/lib64/lua/5.1/?.lua;/usr/lib64/lua/5.1/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/share/lua/5.1/?/init.lua;lib/?.lua;lib/?/init.lua;/home/lepagee/dev/awesome/tests/?.lua'
+ XDG_CONFIG_HOME=./
+ export LUA_PATH
+ export XDG_CONFIG_HOME
+ cd -
+ trap cleanup 0 2 3 15
++ mktemp -d
+ tmp_files=/tmp/tmp.p9m2e2mHaY
+ awesome_log=/tmp/tmp.p9m2e2mHaY/_awesome_test.log
+ echo 'awesome_log: /tmp/tmp.p9m2e2mHaY/_awesome_test.log'
awesome_log: /tmp/tmp.p9m2e2mHaY/_awesome_test.log
+ wait_until_success 'setup xrdb' 'printf '\''Xft.dpi: 96
    *.background: #002b36
    *.foreground: #93a1a1
    *.color0:     #002b36
    *.color1:     #dc322f
    *.color10:    #859900
    *.color11:    #b58900
    *.color12:    #268bd2
    *.color13:    #6c71c4
    *.color14:    #2aa198
    *.color15:    #fdf6e3
    *.color16:    #cb4b16
    *.color17:    #d33682
    *.color18:    #073642
    *.color19:    #586e75
    *.color2:     #859900
    *.color20:    #839496
    *.color21:    #eee8d5
    *.color3:     #b58900
    *.color4:     #268bd2
    *.color5:     #6c71c4
    *.color6:     #2aa198
    *.color7:     #93a1a1
    *.color8:     #657b83
    *.color9:     #dc322f'\'' | DISPLAY='\'':5'\'' xrdb 2>&1'
+ '[' '' = true ']'
+ max_wait=60
+ true
+ set +e
+ eval 'reply=$(printf '\''Xft.dpi: 96
    *.background: #002b36
    *.foreground: #93a1a1
    *.color0:     #002b36
    *.color1:     #dc322f
    *.color10:    #859900
    *.color11:    #b58900
    *.color12:    #268bd2
    *.color13:    #6c71c4
    *.color14:    #2aa198
    *.color15:    #fdf6e3
    *.color16:    #cb4b16
    *.color17:    #d33682
    *.color18:    #073642
    *.color19:    #586e75
    *.color2:     #859900
    *.color20:    #839496
    *.color21:    #eee8d5
    *.color3:     #b58900
    *.color4:     #268bd2
    *.color5:     #6c71c4
    *.color6:     #2aa198
    *.color7:     #93a1a1
    *.color8:     #657b83
    *.color9:     #dc322f'\'' | DISPLAY='\'':5'\'' xrdb 2>&1)'
+++ printf 'Xft.dpi: 96
    *.background: #002b36
    *.foreground: #93a1a1
    *.color0:     #002b36
    *.color1:     #dc322f
    *.color10:    #859900
    *.color11:    #b58900
    *.color12:    #268bd2
    *.color13:    #6c71c4
    *.color14:    #2aa198
    *.color15:    #fdf6e3
    *.color16:    #cb4b16
    *.color17:    #d33682
    *.color18:    #073642
    *.color19:    #586e75
    *.color2:     #859900
    *.color20:    #839496
    *.color21:    #eee8d5
    *.color3:     #b58900
    *.color4:     #268bd2
    *.color5:     #6c71c4
    *.color6:     #2aa198
    *.color7:     #93a1a1
    *.color8:     #657b83
    *.color9:     #dc322f'
+++ DISPLAY=:5
+++ xrdb
++ reply='xrdb: Connection refused
xrdb: Can'\''t open display '\'':5'\'''
+ ret=1
+ set -e
+ '[' 1 = 0 ']'
++ expr 60 - 1
+ max_wait=59
+ '[' 59 -lt 0 ']'
+ sleep 0.05
+ true
+ set +e
+ eval 'reply=$(printf '\''Xft.dpi: 96
    *.background: #002b36
    *.foreground: #93a1a1
    *.color0:     #002b36
    *.color1:     #dc322f
    *.color10:    #859900
    *.color11:    #b58900
    *.color12:    #268bd2
    *.color13:    #6c71c4
    *.color14:    #2aa198
    *.color15:    #fdf6e3
    *.color16:    #cb4b16
    *.color17:    #d33682
    *.color18:    #073642
    *.color19:    #586e75
    *.color2:     #859900
    *.color20:    #839496
    *.color21:    #eee8d5
    *.color3:     #b58900
    *.color4:     #268bd2
    *.color5:     #6c71c4
    *.color6:     #2aa198
    *.color7:     #93a1a1
    *.color8:     #657b83
    *.color9:     #dc322f'\'' | DISPLAY='\'':5'\'' xrdb 2>&1)'
+++ printf 'Xft.dpi: 96
    *.background: #002b36
    *.foreground: #93a1a1
    *.color0:     #002b36
    *.color1:     #dc322f
    *.color10:    #859900
    *.color11:    #b58900
    *.color12:    #268bd2
    *.color13:    #6c71c4
    *.color14:    #2aa198
    *.color15:    #fdf6e3
    *.color16:    #cb4b16
    *.color17:    #d33682
    *.color18:    #073642
    *.color19:    #586e75
    *.color2:     #859900
    *.color20:    #839496
    *.color21:    #eee8d5
    *.color3:     #b58900
    *.color4:     #268bd2
    *.color5:     #6c71c4
    *.color6:     #2aa198
    *.color7:     #93a1a1
    *.color8:     #657b83
    *.color9:     #dc322f'
+++ DISPLAY=:5
+++ xrdb
++ reply=
+ ret=0
+ set -e
+ '[' 0 = 0 ']'
+ break
+ '[' '' = true ']'
++ DISPLAY=:5
++ dbus-launch --sh-syntax --exit-with-session
+ eval 'DBUS_SESSION_BUS_ADDRESS='\''unix:abstract=/tmp/dbus-Cpgo6UHfla,guid=5b127c5bdb8eb32aa4b3f38c572eccaa'\'';' export 'DBUS_SESSION_BUS_ADDRESS;' 'DBUS_SESSION_BUS_PID=13376;' 'DBUS_SESSION_BUS_WINDOWID=2097153;'
++ DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-Cpgo6UHfla,guid=5b127c5bdb8eb32aa4b3f38c572eccaa
++ export DBUS_SESSION_BUS_ADDRESS
++ DBUS_SESSION_BUS_PID=13376
++ DBUS_SESSION_BUS_WINDOWID=2097153
+ '[' '' '!=' true ']'
+ '[' -f /home/lepagee/dev/awesome/tests/../awesomerc.lua.in ']'
+ RC_FILE=/tmp/tmp.p9m2e2mHaY/awesomerc.lua
+ THEME_FILE=/tmp/tmp.p9m2e2mHaY/theme.lua
+ sed -e 's:.*beautiful.init(.*default/theme.lua.*:beautiful.init('\''/tmp/tmp.p9m2e2mHaY/theme.lua'\''):' /home/lepagee/dev/awesome/tests/../awesomerc.lua
+ sed -e s:@AWESOME_THEMES_PATH@/default/titlebar:/home/lepagee/dev/awesome/tests/../build/themes/default/titlebar: -e s:@AWESOME_THEMES_PATH@:/home/lepagee/dev/awesome/tests/../themes/: -e s:@AWESOME_ICON_PATH@:/home/lepagee/dev/awesome/tests/../icons: /home/lepagee/dev/awesome/tests/../themes/default/theme.lua
+ errors=0
+ for f in '$tests'
+ echo '== Running /home/lepagee/dev/awesome/tests/test-aaaaaaaaaaaaa.lua =='
== Running /home/lepagee/dev/awesome/tests/test-aaaaaaaaaaaaa.lua ==
+ start_awesome
+ export DISPLAY=:5
+ DISPLAY=:5
+ cd /home/lepagee/dev/awesome/tests/../build
+ awesome_pid=13379
+ cd -
+ wait_until_success 'wait for awesome startup via awesome-client' 'echo '\''return 1'\'' | DISPLAY=:5 '\''/home/lepagee/dev/awesome/tests/../utils/awesome-client'\'' 2>&1'
+ DISPLAY=:5
+ /home/lepagee/dev/awesome/tests/../build/awesome -c /tmp/tmp.p9m2e2mHaY/awesomerc.lua
+ '[' '' = true ']'
+ max_wait=60
+ true
+ set +e
+ eval 'reply=$(echo '\''return 1'\'' | DISPLAY=:5 '\''/home/lepagee/dev/awesome/tests/../utils/awesome-client'\'' 2>&1)'
+++ echo 'return 1'
+++ DISPLAY=:5
+++ /home/lepagee/dev/awesome/tests/../utils/awesome-client
++ reply='Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.naquadah.awesome.awful was not provided by any .service files
E: dbus-send failed.'
+ ret=1
+ set -e
+ '[' 1 = 0 ']'
++ expr 60 - 1
+ max_wait=59
+ '[' 59 -lt 0 ']'
+ sleep 0.05
+ true
+ set +e
+ eval 'reply=$(echo '\''return 1'\'' | DISPLAY=:5 '\''/home/lepagee/dev/awesome/tests/../utils/awesome-client'\'' 2>&1)'
+++ echo 'return 1'
+++ DISPLAY=:5
+++ /home/lepagee/dev/awesome/tests/../utils/awesome-client
```

```
    |                                   `-urxvtd-+-zsh-+-grep
     |                                            |     `-pstree
     |                                            |-zsh---run.sh-+-Xephyr
     |                                            |              |-awesome---{gmain}
     |                                            |              `-tail
     |                                            `-zsh
```

**Comment by Elv13** [comment]
And eventually:

```
++ reply='Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.naquadah.awesome.awful was not provided by any .service files
E: dbus-send failed.'
```

So, this is because my SSD is too fast :P. Awesome is not yet ready when the command start to be added to the queue, so the service is not yet available, so it lock, then timeout, then work. That's why the sleep is necessary for me. It would be replaced by a python (or lua) script to watch the bus and return when the service become available. But a short sleep will do too ;)

**Comment by psychon** [comment]
I'd say: This needs something like `--reply-timeout=100` in the call to `dbus-send`. This means we either add some way to make `awesome-client` use that argument or we replace `echo return 1 | awesome-client` with `dbus-send --reply-timeout=100 --dest=org.naquadah.awesome.awful --type=method_call / org.naquadah.awesome.awful..Remote.Eval "string:return 1"`. I guess this second idea is easier/simpler...

@Elv13 Could you try this? (The above should just be what awesome-client does internally, with `--reply-timeout=100` added and `--print-reply` removed (since it should be unnecessary).

**Comment by Elv13** [comment]
@psychon I did not have luck when I last tried this (nothing happened), however, I may not have tried hard enough. Can this be merged? I still have to cherry-pich this commit everytime I need to run the tests locally.

**Comment by psychon** [comment]
Did you try what I wrote in my last comment? To make it more explicit, try if the following fixes your issue:
```diff
diff --git a/tests/run.sh b/tests/run.sh
index 19de148..57d86eb 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -188,7 +188,7 @@ start_awesome() {
     cd - >/dev/null
 
     # Wait until the interface for awesome-client is ready (D-Bus interface).
-    wait_until_success "wait for awesome startup via awesome-client" "echo 'return 1' | DISPLAY=$D '$AWESOME_CLIENT' 2>&1"
+    wait_until_success "wait for awesome startup via awesome-client" "dbus-send --reply-timeout=100 --dest=org.naquadah.awesome.awful --type=method_call / org.naquadah.awesome.awful..Remote.Eval 'string:return 1' 2>&1"
 }
 
 # Count errors.
```

**Comment by psychon** [comment]
Did #1116 fix your problem or do you still need your `sleep 0.05`?

**Comment by psychon** [comment]
I claim that this was fixed by cea5d41518c08b91fed9881391ab8d14a1ea882a

**Pull request closed without merging**
