### PR TITLE
awful.widget.tasklist: Add an align option

### PR DESCRIPTION
**Pull request by Akulen**
This adds an align option to the textboxes of the tasklist
(supported options are "left", "center", and "right")

### CODE REVIEW

**Comment by actionless** [comment]
Looks good :+1:

**Comment by blueyed** [comment]
Thanks!

**Comment by blueyed** [comment]
Woah, I think that was merged too fast: shouldn't `base_widget` be a complete widget always, and shouldn't that somehow get aligned already then?
Or the other way around: shouldn't the doc refer to the constructor of widgets?
Or is the tasklist meant to handle the widget in a specific way?

/cc @Elv13 

I was looking into improving the doc (using `opt` mostly):

```diff
diff --git i/lib/awful/widget/tasklist.lua w/lib/awful/widget/tasklist.lua
index 74e2e98..8be4659 100644
--- i/lib/awful/widget/tasklist.lua
+++ w/lib/awful/widget/tasklist.lua
@@ -140,21 +140,23 @@ local function tasklist_update(s, w, buttons, filter, data, style, update
     update_function(w, buttons, label, data, clients)
 end
 
---- Create a new tasklist widget. The last two arguments (update_function
--- and base_widget) serve to customize the layout of the tasklist (eg. to
+--- Create a new tasklist widget. The last two arguments (`update_function`
+-- and `base_widget`) allow to customize the layout of the tasklist (eg. to
 -- make it vertical). For that, you will need to copy the
--- awful.widget.common.list_update function, make your changes to it
--- and pass it as update_function here. Also change the base_widget if the
+-- `awful.widget.common.list_update` function, make your changes to it
+-- and pass it as `update_function` here. Also change the `base_widget` if the
 -- default is not what you want.
+--
 -- @param screen The screen to draw tasklist for.
 -- @param filter Filter function to define what clients will be listed.
 -- @param buttons A table with buttons binding to set.
 -- @param style The style overrides default theme.
 -- @param[opt] update_function Function to create a tag widget on each
 --   update. See `awful.widget.common.list_update`.
--- @tparam[opt] table base_widget Container widget for tag widgets. Default
---   is `wibox.layout.flex.horizontal`.
--- @param base_widget.align The alignment ("left", "center" or "right").
+-- @tparam[opt=wibox.layout.flex.horizontal] table base_widget Container widget
+--   for tag widgets.
+-- @param base_widget.align[opt="left"] The alignment ("left", "center" or
+--   "right").
 -- @param base_widget.bg_normal The background color for unfocused client.
 -- @param base_widget.bg_normal The background color for unfocused client.
```

**Comment by Akulen** [comment]
> Woah, I think that was merged too fast: shouldn't base_widget be a complete widget always, and shouldn't that somehow get aligned already then?
> Or the other way around: shouldn't the doc refer to the constructor of widgets?
> Or is the tasklist meant to handle the widget in a specific way?

No, the tasklist is special, because it's a wrapper around a list of textboxes placed in margin containers that are updated by the tasklist widget. There is no similar need for the other widgets because they can be aligned externally

**Comment by Elv13** [comment]
@blueyed If you have improvements, please add them to #1044 and notify me so I don't override them. I already documented some (most?) of the missing stuff.

**Pull request merged**
