### PR TITLE
import vim hotkeys from user config, not hotkeys_popup module

### PR DESCRIPTION
**Pull request by actionless**
i remember one of the users was complaining what they are enabled by default

### CODE REVIEW

**Comment by actionless** [comment]
i forecast wht it will reduce the coverage for hotkeys module to 0% :)

**Comment by Elv13** [comment]
I am not sure adding vim related stuff to rc.lua is such a good idea, it's out of scope and confusing.

**Comment by actionless** [comment]
IMO it's better than loading vim hotkeys by default when loading widget itself

**Comment by actionless** [comment]
any more opinions?

**Comment by actionless** [comment]
let's see if any of users will complain what vim hotkeys disappeared in their local configs, mb we should put that into release notes for 4.1

**Pull request merged**
