### PR TITLE
test-menubar.lua changes

### PR DESCRIPTION
**Pull request by psychon**
Address https://github.com/awesomeWM/awesome/pull/1872#issuecomment-311224439 and disable the test on LuaJIT.

### CODE REVIEW

**Comment by Elv13** [comment]
Still fails

**Comment by psychon** [comment]
> Still fails

No. Travis tested without the "disable test on LuaJIT"-commit and, well, LuaJIT raised an error. That's not this PR's fault.
```
Testing commit 914b4b7c8b3531a48e8b11b5102f8e6e36c049a1
++git checkout 914b4b7c8b3531a48e8b11b5102f8e6e36c049a1
Warning: you are leaving 2 commits behind, not connected to
any of your branches:
  673f67c Merge 19fbae7f74ed13a3226375922b5f8dcaa5d9f019 into 6d5cf6cdbb7d54624bf8b44cf3354fc98bee7317
  19fbae7 test-menubar.lua: Also skip the test with LuaJIT
[...]
 ===> ERROR running /home/travis/build/awesomeWM/awesome/tests/test-menubar.lua <===
2017-06-27 07:04:00 W: awesome: luaA_panic:541: unprotected error in call to Lua API (attempt to call a number value)
```

**Comment by Elv13** [comment]
> No. Travis tested without the "disable test on LuaJIT"-commit and, well, LuaJIT raised an error. That's not this PR's fault.

Can you swap the commits?

**Comment by blueyed** [comment]
For the sake of git-bisect: it was broken before already (and this PR could have been two).
But to make this PR green really (and prove that it is working as expected), the commits should be swapped - but I am OK with just merging it as-is.

**Comment by blueyed** [comment]
Thank you!

**Pull request merged**
