### PR TITLE
wibox.drawable: Draw black if no wallpaper is available

### PR DESCRIPTION
**Pull request by psychon**
I-hope-this-fixes: https://github.com/awesomeWM/awesome/issues/1411
Signed-off-by: Uli Schlachter <psychon@znc.in>

### CODE REVIEW

**Comment by psychon** [comment]
I now actually tested this with `theme.bg_normal = "#00000000"` and `theme.wallpaper = nil`. I can reproduce the original problem and this patch does indeed fix the problem. Merge?

**Comment by blueyed** [comment]
@psychon
Yes, please adjust the commit message then.

**Comment by psychon** [comment]
Updated the commit message (Removed the "I-hope-this-"-part).

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
