### PR TITLE
Another attempt at making -Werror work on Travis

### PR DESCRIPTION
**Pull request by psychon**
Follow up for #2310 (apparently I cannot reopen a PR after a force-push).

### CODE REVIEW

**Comment by psychon** [comment]
This now fails in the intended way:
```
[ 79%] Building C object CMakeFiles/awesome.dir/objects/client.c.o
/home/travis/build/awesomeWM/awesome/build/objects/client.c:938:5: error: no previous prototype for ‘client_set_startup_id’ [-Werror=missing-prototypes]
     client_set_##prop(lua_State *L, int cidx, char *value) \
     ^
/home/travis/build/awesomeWM/awesome/build/objects/client.c:956:1: note: in expansion of macro ‘DO_CLIENT_SET_STRING_PROPERTY2’
 DO_CLIENT_SET_STRING_PROPERTY2(startup_id, startup_id)
 ^
cc1: all warnings being treated as errors
```

**Comment by actionless** [comment]
but we can't merge it anyway until the warnings causes themselves will fixed, right?

**Comment by psychon** [comment]
Right. It's just nice to know that this works as intended. :-)

The idea is to rebase this on master when #2309 is fixed and hope that the build then just works.

**Comment by actionless** [comment]
now it's fine but squashing is needed for PREV_COMMITS

**Comment by psychon** [comment]
Rebased on master. The only change is to fix the typo that I always do and that @blueyed found.

@actionless The order of the commits is already fine for `TEST_PREV_COMMITS` (I think). GitHub just displays the commits in a different order, because I used a rebase to re-order them. The earlier commit now has a latter commit date, and I guess GitHub orders by commit date and not by parent relationship.

**Comment by blueyed** [comment]
> mergify/pr — Merge fail

**Comment by actionless** [comment]
should we postpone the merging because of https://github.com/awesomeWM/awesome/pull/2320#issuecomment-408193408 ?

**Comment by actionless** [comment]
@psychon i was asking if current config will produce any warnings on gcc 8

just checked now on gcc 8.1 -- no warnings seen

**Comment by Elv13** [comment]
> @psychon i was asking if current config will produce any warnings on gcc 8

GCC has 4 level of warnings:

 * Default (really bad stuff)
 * Wall (still critical stuff like non-void not retuning)
 * Wextra (less important warnings)
 * All the other (not always relevant or prone to false positive)

And then there is the pedantic mode, but that's something else.

The default and Wall sets of warning rarely changes because it annoys distributions like OpenSUSE that have Werror default for most of their packages. If GCC would add too many warnings by default in each release, the effort required from these distro rebuild the world would not be manageable.

It is why #2320 exists. With GCC, past Wextra, you have to curate your warnings suits. Clang has a better system where it has -Weverything, then you must curate the ones you wish to ignore. I like it better since new versions require no "RTFM" to get the new good ones. And it's also explicit that you didn't forget one because it's opt-out instead of opt-in.

**Pull request merged**
