### PR TITLE
Add Travis for the 3.5 branch

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by psychon** [comment]
Fine by me. Feel free to merge this to the 3.5 branch (although I wonder if the apidoc stuff in there might still trigger and "do something"?).

Thanks!

**Comment by blueyed** [comment]
We could maybe build the API doc for the stable / 3.5 branch also, possibly in another directory of https://github.com/awesomeWM/apidoc?

**Comment by psychon** [comment]
Why would we want that? I don't think there are many documentation changes for 3.5 and the apidoc for the latest release should be "good enough".
(At least that's my opinion, but I'm a bad api-documentation-user and rather read the source code.)

**Comment by blueyed** [comment]
Merged in https://github.com/awesomeWM/awesome/commit/91743f01b8a26793a780686f5896c76928120f5b.

**Comment by psychon** [comment]
Thanks!

**Pull request closed without merging**
