### PR TITLE
chore(awful: hotkeys: vim): small improvements in hotkeys descriptions

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by actionless** [comment]
i think i will also add `Ctrl+` bindings too

**Comment by actionless** [comment]
i will do more changes tomorrow

**Comment by psychon** [comment]
While you are at it, do we have some docs/example on how to enable these Vim descriptions? Perhaps as a comment in the default config, or something?

**Comment by actionless** [comment]
they're enabled automatically when the rule matches: https://github.com/actionless/awesome/blob/vim-bindings-improvements/lib/awful/hotkeys_popup/keys/vim.lua#L12

**Comment by psychon** [comment]
Ah, I didn't know that. Does the rule match gvim? (Yup, I should just try this...)

**Comment by actionless** [comment]
here is the fix for that: https://github.com/awesomeWM/awesome/pull/685

**Comment by actionless** [comment]
i think i am done for now

**Comment by psychon** [comment]
Fine by me (= doesn't look like it can break something): :+1:

**Comment by blueyed** [comment]
Thanks!

**Pull request merged**
